window.SERIES_POSTS = [
  {
    "slug": "00-timeline",
    "file": "00-发展时间线总览.md",
    "kind": "overview",
    "day": 0,
    "year": null,
    "title": "大语言模型发展时间线：表示、规模、对齐与推理系统",
    "cardTitle": "发展时间线总览",
    "question": "各阶段的问题、方法与继承关系",
    "excerpt": "语言模型并不是从聊天界面开始的。它最初要解决的是一个概率问题：给定前文，下一个词是什么？围绕这个问题形成的表示、优化和计算技术，后来逐步支撑翻译、问答、代码、多模态理解和工具使用。阅读这条时间线时，应始终区分三个层面：模型怎样训练、推理时怎样调用、结果怎样评价。",
    "eraId": "overview",
    "eraYears": "",
    "eraLabel": "总览"
  },
  {
    "slug": "001-lstm",
    "file": "001-lstm.md",
    "kind": "paper",
    "day": 1,
    "year": 1997,
    "title": "001｜LSTM：让远处的误差仍能教会网络记忆",
    "cardTitle": "LSTM：让远处的误差仍能教会网络记忆",
    "question": "序列建模",
    "excerpt": "一句话的前面给出一个条件，结尾才要求使用它，中间全是不相关内容。普通循环网络形式上可以把条件一直传下去，但训练时，结尾的误差信号往前传播，可能很快变小，无法告诉网络最初应该保存什么。LSTM 的核心不是笼统地“增加记忆”，而是为内部状态构造一条有利于误差长期传播的路径，再用可学习的门控制信息进入和离开。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "002-nnlm",
    "file": "002-nnlm.md",
    "kind": "paper",
    "day": 2,
    "year": 2003,
    "title": "002｜神经概率语言模型：用共享表示跨越没见过的句子",
    "cardTitle": "神经概率语言模型：用共享表示跨越没见过的句子",
    "question": "序列建模",
    "excerpt": "训练语料出现过“猫坐在垫子上”，却没有出现“狗坐在垫子上”，模型应该怎样利用已知句子帮助预测未知句子？传统 n-gram 主要围绕离散计数和回退规则共享统计量。本文把词映射为连续向量，再根据这些向量预测下一个词，让相似上下文可以通过参数共享发生联系。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "003-rnnlm",
    "file": "003-rnnlm.md",
    "kind": "paper",
    "day": 3,
    "year": 2010,
    "title": "003｜RNN 语言模型：让预测器携带一个不断更新的过去",
    "cardTitle": "RNN 语言模型：让预测器携带一个不断更新的过去",
    "question": "序列建模",
    "excerpt": "有限窗口神经语言模型每次只看最近几个词。RNN 语言模型额外维护一个循环状态：读入一个词，就更新对历史的压缩表示，再预测下一个词。这个状态允许更早信息参与预测，而不必把所有历史词显式拼接成越来越长的输入。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "004-word2vec",
    "file": "004-word2vec.md",
    "kind": "paper",
    "day": 4,
    "year": 2013,
    "title": "004｜word2vec：把昂贵语言模型拆成便宜的表示学习任务",
    "cardTitle": "word2vec：把昂贵语言模型拆成便宜的表示学习任务",
    "question": "词表示",
    "excerpt": "如果主要目的是得到好用的词向量，是否一定要训练一个复杂、昂贵的完整神经语言模型？本文把任务简化：CBOW 根据邻近词预测中心词，Skip-gram 根据中心词预测邻近词。省去较昂贵的非线性隐藏层后，能够在更多文本上学习表示。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "005-negative-sampling",
    "file": "005-negative-sampling.md",
    "kind": "paper",
    "day": 5,
    "year": 2013,
    "title": "005｜负采样与短语表示：把全词表预测改成可扩展的局部判别",
    "cardTitle": "负采样与短语表示：把全词表预测改成可扩展的局部判别",
    "question": "词表示",
    "excerpt": "训练一个中心词与邻词的关系，是否需要每次都计算几十万个候选词？负采样把这个问题改成较小的二分类：提高真实词对得分，降低从噪声分布抽出的少量词对得分。论文还减少常见词的训练占比，并把一些高关联词组并成短语，使同样计算能学习更丰富的表示。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "006-seq2seq",
    "file": "006-seq2seq.md",
    "kind": "paper",
    "day": 6,
    "year": 2014,
    "title": "006｜Seq2Seq：用一个条件生成模型连接两种长度不同的序列",
    "cardTitle": "Seq2Seq：用一个条件生成模型连接两种长度不同的序列",
    "question": "序列建模",
    "excerpt": "翻译输入有十个词，输出可能有十二个词，如何用一个统一模型处理？编码器先读完整输入，把它压缩到状态；解码器从这个状态出发，逐词生成目标序列，直到结束符。不同长度被转化为条件概率建模，而不再要求输入输出位置一一对应。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "007-attention",
    "file": "007-attention.md",
    "kind": "paper",
    "day": 7,
    "year": 2014,
    "title": "007｜可学习对齐：解码每个词时，重新决定该看输入的哪里",
    "cardTitle": "可学习对齐：解码每个词时，重新决定该看输入的哪里",
    "question": "注意力",
    "excerpt": "如果源句很长，让编码器先把全部信息压成一个向量，再要求解码器逐词取用，可能形成瓶颈。本文为源句每个位置保留一个表示，并让解码器每生成一个词，都计算一组对齐权重，形成当前需要的上下文向量。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "008-glove",
    "file": "008-glove.md",
    "kind": "paper",
    "day": 8,
    "year": 2014,
    "title": "008｜GloVe：让词向量解释全局共现统计",
    "cardTitle": "GloVe：让词向量解释全局共现统计",
    "question": "词表示",
    "excerpt": "“冰”和“蒸汽”都可能出现在谈论水的文章中，但“固体”对二者的关联差异更有区分度。GloVe 从全局词共现统计出发，试图让向量关系反映这种相对差异。它通过加权最小二乘拟合共现次数的对数，把统计矩阵与连续表示连接起来。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "009-adam",
    "file": "009-adam.md",
    "kind": "paper",
    "day": 9,
    "year": 2014,
    "title": "009｜Adam：同时估计梯度方向与每个参数的更新尺度",
    "cardTitle": "Adam：同时估计梯度方向与每个参数的更新尺度",
    "question": "训练优化",
    "excerpt": "不同参数收到的梯度频率和尺度可能差别很大。一个统一学习率既可能让某些参数变化过猛，也可能让另一些长期学不动。Adam 为每个参数维护梯度的一阶与二阶滑动统计：前者平滑方向，后者调整尺度，再修正零初始化带来的早期偏差。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "010-distillation",
    "file": "010-distillation.md",
    "kind": "paper",
    "day": 10,
    "year": 2015,
    "title": "010｜知识蒸馏：让学生学习教师的概率关系，而不只复制答案",
    "cardTitle": "知识蒸馏：让学生学习教师的概率关系，而不只复制答案",
    "question": "训练效率",
    "excerpt": "教师把图片判成数字 3，但它也可能给 8 较高概率、给数字 1 极低概率。一个硬标签只告诉学生“正确类是 3”，软分布还传递哪些类别更容易混淆。蒸馏让较小或较便宜的学生拟合这些概率关系，从而把教师或集成模型的部分能力转移到单模型。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "011-bpe",
    "file": "011-bpe.md",
    "kind": "paper",
    "day": 11,
    "year": 2015,
    "title": "011｜BPE 子词翻译：有限词表怎样生成没见过的词",
    "cardTitle": "BPE 子词翻译：有限词表怎样生成没见过的词",
    "question": "分词",
    "excerpt": "完整单词词表再大，也会遇到新名字、复合词与变形。把未知词统一写成 UNK，模型便丢失了其内部结构。本文用可复用子词表示单词，让新词能够由已知片段组成，再由翻译网络学习复制、音译和组合关系。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "012-layernorm",
    "file": "012-layernorm.md",
    "kind": "paper",
    "day": 12,
    "year": 2016,
    "title": "012｜Layer Normalization：让归一化不再依赖同批其他样本",
    "cardTitle": "Layer Normalization：让归一化不再依赖同批其他样本",
    "question": "训练优化",
    "excerpt": "Batch Normalization 依赖一批样本计算统计量，小批量、可变长度序列和在线执行时可能不方便。Layer Normalization 对单个样本内部的一组隐藏单元计算均值与方差，让每个样本自己的表示得到归一化，不依赖同批其他输入。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "013-fasttext",
    "file": "013-fasttext.md",
    "kind": "paper",
    "day": 13,
    "year": 2016,
    "title": "013｜fastText 子词表示：让稀有词共享拼写片段的统计",
    "cardTitle": "fastText 子词表示：让稀有词共享拼写片段的统计",
    "question": "词表示",
    "excerpt": "“walk”“walked”“walking”共享拼写和部分含义，为什么每个词都要从零学习一个完全独立向量？本文把一个词表示为多个字符片段向量的组合，让不同词通过共享片段交换统计信息。即便某个完整词没有出现在训练中，也可能从已学片段构造表示。",
    "eraId": "early",
    "eraYears": "1997–2016",
    "eraLabel": "序列与词表示"
  },
  {
    "slug": "014-sparse-moe",
    "file": "014-sparse-moe.md",
    "kind": "paper",
    "day": 14,
    "year": 2017,
    "title": "014｜稀疏 MoE：让模型拥有更多参数，却只为当前输入激活一部分",
    "cardTitle": "稀疏 MoE：让模型拥有更多参数，却只为当前输入激活一部分",
    "question": "稀疏架构",
    "excerpt": "稠密网络每个输入都计算几乎全部参数，扩大容量通常也扩大单样本计算。MoE 放置许多专家网络，由路由器为当前输入选择少数专家，只计算被选部分，再组合输出。总参数因此可以很大，而激活计算增长较慢。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "015-transformer",
    "file": "015-transformer.md",
    "kind": "paper",
    "day": 15,
    "year": 2017,
    "title": "015｜Transformer：用注意力连接序列位置，让训练不必逐步递归",
    "cardTitle": "Transformer：用注意力连接序列位置，让训练不必逐步递归",
    "question": "注意力",
    "excerpt": "循环模型训练一段序列时，后一步隐藏状态依赖前一步计算。Transformer 改为让位置之间通过注意力直接交换信息，配合逐位置前馈网络，使已知训练序列的多数位置可以并行处理。位置编码提供顺序信息，因果掩码阻止解码器看到未来答案。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "016-elmo",
    "file": "016-elmo.md",
    "kind": "paper",
    "day": 16,
    "year": 2018,
    "title": "016｜ELMo：一个词的表示，应由它在当前句子中的用法决定",
    "cardTitle": "ELMo：一个词的表示，应由它在当前句子中的用法决定",
    "question": "预训练",
    "excerpt": "“银行”出现在金融句子和河流句子里，静态词向量通常相同。ELMo 用预训练双向语言模型为每个具体位置生成表示，让同一个词随着上下文变化。下游任务还能学习不同层的组合，而不是只能拿最后一层。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "017-gpt",
    "file": "017-gpt.md",
    "kind": "paper",
    "day": 17,
    "year": 2018,
    "title": "017｜GPT：先学习文本生成，再用少量任务接口完成迁移",
    "cardTitle": "GPT：先学习文本生成，再用少量任务接口完成迁移",
    "question": "预训练",
    "excerpt": "很多语言任务的标注数据有限，但无标签文本很多。GPT 先用因果 Transformer 学习预测下一个 token，再把分类、蕴含或选择题转换成适合该模型的输入形式，用任务标签微调。预训练提供较好的语言表示与初始化，减少从零学习的负担。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "018-bert",
    "file": "018-bert.md",
    "kind": "paper",
    "day": 18,
    "year": 2018,
    "title": "018｜BERT：隐藏部分输入，才能联合学习左右上下文",
    "cardTitle": "BERT：隐藏部分输入，才能联合学习左右上下文",
    "question": "预训练",
    "excerpt": "若直接让双向网络预测当前位置的原词，它可能从输入中抄答案。BERT 先破坏部分 token，再要求模型利用左右上下文恢复这些位置，由此训练深层双向表示。另一个预训练任务判断句段是否连续，微调时再接入具体任务输出。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "019-transformer-xl",
    "file": "019-transformer-xl.md",
    "kind": "paper",
    "day": 19,
    "year": 2019,
    "title": "019｜Transformer-XL：跨片段复用状态，避免每段都从失忆开始",
    "cardTitle": "Transformer-XL：跨片段复用状态，避免每段都从失忆开始",
    "question": "长上下文",
    "excerpt": "把长文本切成固定片段训练，每段开头会失去前面的上下文；评价时反复重算重叠前缀也昂贵。Transformer-XL 缓存上一片段的隐藏状态，让当前片段可以读取它们，同时采用适合状态复用的相对位置信息。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "020-adapters",
    "file": "020-adapters.md",
    "kind": "paper",
    "day": 20,
    "year": 2019,
    "title": "020｜Adapters：每个任务只保存一小组新增参数",
    "cardTitle": "Adapters：每个任务只保存一小组新增参数",
    "question": "参数高效微调",
    "excerpt": "一个大模型服务许多任务，若每个任务都完整微调并保存一份权重，总存储会随任务数快速增加。Adapters 冻结主要预训练参数，在各层插入较小可训练模块，让任务变化由这些模块承担。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "021-gpt2",
    "file": "021-gpt2.md",
    "kind": "paper",
    "day": 21,
    "year": 2019,
    "title": "021｜GPT-2：网页里的自然任务示例，能否转化为零样本能力",
    "cardTitle": "GPT-2：网页里的自然任务示例，能否转化为零样本能力",
    "question": "预训练",
    "excerpt": "网页里自然包含问答、翻译、摘要和各种说明。若模型足够善于预测这些文本，它是否也会在相应前缀后继续完成任务？GPT-2 扩大生成式语言模型和较多样的网页语料，在不为每个任务微调参数的条件下检验迁移。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "022-xlnet",
    "file": "022-xlnet.md",
    "kind": "paper",
    "day": 22,
    "year": 2019,
    "title": "022｜XLNet：改变预测顺序，让自回归目标学习双向信息",
    "cardTitle": "XLNet：改变预测顺序，让自回归目标学习双向信息",
    "question": "预训练",
    "excerpt": "标准自回归只按从左到右预测，BERT 则通过破坏输入获得双向表示。XLNet 尝试另一路线：对同一原序列采样不同的概率分解顺序，让某个位置有时根据左侧、有时根据右侧词预测，同时避免用自己的真实内容预测自己。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "023-roberta",
    "file": "023-roberta.md",
    "kind": "paper",
    "day": 23,
    "year": 2019,
    "title": "023｜RoBERTa：在提出新目标之前，先把旧模型训练充分",
    "cardTitle": "RoBERTa：在提出新目标之前，先把旧模型训练充分",
    "question": "数据与配方",
    "excerpt": "当一种新预训练目标优于 BERT，差距究竟来自目标，还是 BERT 训练得不够充分？RoBERTa 保留核心双向掩码建模，系统研究遮盖方式、文本组织、batch、数据和训练量。更强配方让原有架构达到很有竞争力的表现。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "024-megatron",
    "file": "024-megatron.md",
    "kind": "paper",
    "day": 24,
    "year": 2019,
    "title": "024｜Megatron-LM：按矩阵结构切分 Transformer，减少模型并行通信",
    "cardTitle": "Megatron-LM：按矩阵结构切分 Transformer，减少模型并行通信",
    "question": "分布式训练",
    "excerpt": "当一份模型放不进单张 GPU，普通数据并行无法解决，因为每张卡仍需完整模型。Megatron 按 Transformer 矩阵计算的结构切分参数与运算，使多卡共同处理一个样本，同时尽量减少必须交换中间结果的次数。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "025-albert",
    "file": "025-albert.md",
    "kind": "paper",
    "day": 25,
    "year": 2019,
    "title": "025｜ALBERT：共享参数可以减少存储，但不会取消重复计算",
    "cardTitle": "ALBERT：共享参数可以减少存储，但不会取消重复计算",
    "question": "参数效率",
    "excerpt": "BERT 的词嵌入和多层独立权重占用大量参数。ALBERT 将词嵌入维度与隐藏维度分开，并在不同层共享参数，减少总权重；同时用句序预测 SOP 代替较容易利用主题差异的句段任务。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "026-zero",
    "file": "026-zero.md",
    "kind": "paper",
    "day": 26,
    "year": 2019,
    "title": "026｜ZeRO：数据并行中，没必要让每张卡保存全部训练状态",
    "cardTitle": "ZeRO：数据并行中，没必要让每张卡保存全部训练状态",
    "question": "分布式训练",
    "excerpt": "混合精度 Adam 训练不仅保存模型权重，还要保存梯度、主精度副本和两个矩状态。普通数据并行让每张卡重复保存这些内容，浪费大量总显存。ZeRO 把不同状态分片到各卡，需要时通信取得或汇总，从而减少每卡冗余。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "027-t5",
    "file": "027-t5.md",
    "kind": "paper",
    "day": 27,
    "year": 2019,
    "title": "027｜T5：把不同语言任务变成同一种文本输入输出接口",
    "cardTitle": "T5：把不同语言任务变成同一种文本输入输出接口",
    "question": "预训练",
    "excerpt": "分类输出标签，翻译输出句子，问答输出答案，是否必须使用完全不同的模型头？T5 把任务输入写成文本，把输出也写成文本，通过任务前缀区分要求。这样架构、损失和解码接口能够共享，便于比较预训练策略。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "028-bart",
    "file": "028-bart.md",
    "kind": "paper",
    "day": 28,
    "year": 2019,
    "title": "028｜BART：用双向编码器读破坏文本，用因果解码器恢复原文",
    "cardTitle": "BART：用双向编码器读破坏文本，用因果解码器恢复原文",
    "question": "预训练",
    "excerpt": "BERT 擅长双向编码，因果语言模型擅长顺序生成，能否在一个预训练框架中结合？BART 先对文本做删除、遮盖、片段填充或句序破坏，再由编码器读取破坏文本、解码器恢复完整原文。",
    "eraId": "pretrain",
    "eraYears": "2017–2019",
    "eraLabel": "Transformer 与预训练"
  },
  {
    "slug": "029-scaling-laws",
    "file": "029-scaling-laws.md",
    "kind": "paper",
    "day": 29,
    "year": 2020,
    "title": "029｜语言模型规模定律：把模型、数据与计算放进同一个预算问题",
    "cardTitle": "语言模型规模定律：把模型、数据与计算放进同一个预算问题",
    "question": "规模定律",
    "excerpt": "预算增加时，该扩大参数、增加数据，还是训练更久？本文通过一系列语言模型实验，观察测试损失与这些资源之间的平滑关系，并拟合幂律，尝试预测给定计算下较合适的模型规模。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "030-realm",
    "file": "030-realm.md",
    "kind": "paper",
    "day": 30,
    "year": 2020,
    "title": "030｜REALM：让语言模型在预训练时学会检索外部知识",
    "cardTitle": "REALM：让语言模型在预训练时学会检索外部知识",
    "question": "检索增强",
    "excerpt": "事实都写进参数，需要大容量且更新困难。REALM 给语言模型外部文本库，并让检索器学习哪些文档能帮助恢复被遮盖内容。检索不是只有人工标注的匹配任务，而可从最终词预测是否改善获得训练信号。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "031-electra",
    "file": "031-electra.md",
    "kind": "paper",
    "day": 31,
    "year": 2020,
    "title": "031 · ELECTRA：让每个位置都成为预训练信号",
    "cardTitle": "031 · ELECTRA：让每个位置都成为预训练信号",
    "question": "预训练",
    "excerpt": "论文：Kevin Clark、Minh-Thang Luong、Quoc V. Le、Christopher D. Manning，ELECTRA: Pre-training Text Encoders as Discriminators Rather Than Generators，ICLR 2020。原始论文。以下以方法、§3实验和对应图表为阅读依据；未",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "032-dpr",
    "file": "032-dpr.md",
    "kind": "paper",
    "day": 32,
    "year": 2020,
    "title": "032 · DPR：把海量文档检索变成可学习的向量搜索",
    "cardTitle": "032 · DPR：把海量文档检索变成可学习的向量搜索",
    "question": "检索增强",
    "excerpt": "论文：Vladimir Karpukhin 等，Dense Passage Retrieval for Open-Domain Question Answering，EMNLP 2020。原始论文。阅读依据为§3–6、表1–4及附录中的诊断实验；没有独立重建全量索引。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "033-longformer",
    "file": "033-longformer.md",
    "kind": "paper",
    "day": 33,
    "year": 2020,
    "title": "033 · Longformer：长文本不必让所有词两两相看",
    "cardTitle": "033 · Longformer：长文本不必让所有词两两相看",
    "question": "长上下文",
    "excerpt": "论文：Iz Beltagy、Matthew E. Peters、Arman Cohan，Longformer: The Long-Document Transformer，2020。原始论文。阅读重点为§3注意力结构、§4实验、表2与表5；未独立复现底层计算核。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "034-rag",
    "file": "034-rag.md",
    "kind": "paper",
    "day": 34,
    "year": 2020,
    "title": "034 · RAG：让生成模型在参数记忆之外查阅证据",
    "cardTitle": "034 · RAG：让生成模型在参数记忆之外查阅证据",
    "question": "检索增强",
    "excerpt": "论文：Patrick Lewis 等，Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks，NeurIPS 2020。原始论文。阅读范围包括§2模型、§3–4实验与附录的训练解码设置；没有独立复现全量检索库。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "035-gpt3",
    "file": "035-gpt3.md",
    "kind": "paper",
    "day": 35,
    "year": 2020,
    "title": "035 · GPT-3：示例可以成为模型的临时任务接口",
    "cardTitle": "035 · GPT-3：示例可以成为模型的临时任务接口",
    "question": "上下文学习",
    "excerpt": "论文：Tom B. Brown 等，Language Models are Few-Shot Learners，NeurIPS 2020。原始论文。依据§2训练与评价、§3任务实验、§4污染分析及附录任务格式阅读；不将所选实验核查等同完整复现。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "036-fid",
    "file": "036-fid.md",
    "kind": "paper",
    "day": 36,
    "year": 2020,
    "title": "036 · FiD：先分段阅读，再在解码时融合证据",
    "cardTitle": "036 · FiD：先分段阅读，再在解码时融合证据",
    "question": "检索增强",
    "excerpt": "论文：Gautier Izacard、Edouard Grave，Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering，首次公开2020，EACL 2021。原始论文。以下依据2021年修订版的§3–4、图2–3与表1–2；未独立复现全量实",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "037-gshard",
    "file": "037-gshard.md",
    "kind": "paper",
    "day": 37,
    "year": 2020,
    "title": "037 · GShard：稀疏专家如何真正分布到数千个设备",
    "cardTitle": "037 · GShard：稀疏专家如何真正分布到数千个设备",
    "question": "稀疏架构",
    "excerpt": "论文：Dmitry Lepikhin 等，GShard: Scaling Giant Models with Conditional Computation and Automatic Sharding，首次公开2020，ICLR 2021。原始论文。依据§2路由、§3编译分片、§4–5训练与系统实验；未复现TPU集群。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "038-bigbird",
    "file": "038-bigbird.md",
    "kind": "paper",
    "day": 38,
    "year": 2020,
    "title": "038 · BigBird：用稀疏连接保留长序列的信息通路",
    "cardTitle": "038 · BigBird：用稀疏连接保留长序列的信息通路",
    "question": "长上下文",
    "excerpt": "论文：Manzil Zaheer 等，Big Bird: Transformers for Longer Sequences，NeurIPS 2020。原始论文。阅读依据为§2–4、理论定理与命题、附录E配置和表1–3、8–10；未复现全部语言及基因组实验。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "039-mmlu",
    "file": "039-mmlu.md",
    "kind": "paper",
    "day": 39,
    "year": 2020,
    "title": "039 · MMLU：模型的平均分掩盖了哪些知识盲区",
    "cardTitle": "039 · MMLU：模型的平均分掩盖了哪些知识盲区",
    "question": "评估",
    "excerpt": "论文：Dan Hendrycks 等，Measuring Massive Multitask Language Understanding，首次公开2020，ICLR 2021。原始论文。依据§3数据构造、§4评估、表1及图6–8、附录格式与污染分析；未重新调用原始模型接口。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "040-performer",
    "file": "040-performer.md",
    "kind": "paper",
    "day": 40,
    "year": 2020,
    "title": "040 · Performer：不存注意力矩阵，也能近似全局注意力",
    "cardTitle": "040 · Performer：不存注意力矩阵，也能近似全局注意力",
    "question": "高效注意力",
    "excerpt": "论文：Krzysztof Choromanski 等，Rethinking Attention with Performers，首次公开2020，ICLR 2021。原始论文。阅读依据为§2–4、图3–4、附录B算法及附录C表1–2；未独立复现随机特征核与训练实验。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "041-pile",
    "file": "041-pile.md",
    "kind": "paper",
    "day": 41,
    "year": 2020,
    "title": "041 · The Pile：训练语料的组成也是模型设计",
    "cardTitle": "041 · The Pile：训练语料的组成也是模型设计",
    "question": "数据",
    "excerpt": "论文：Leo Gao 等，The Pile: An 800GB Dataset of Diverse Text for Language Modeling，2020年12月公开。原始论文。依据§2构造、§3–4评价、§5–6统计与数据分析，以及表1–4；没有重新下载和处理全部语料。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "042-switch",
    "file": "042-switch.md",
    "kind": "paper",
    "day": 42,
    "year": 2021,
    "title": "042 · Switch Transformer：每个词只选一个专家",
    "cardTitle": "042 · Switch Transformer：每个词只选一个专家",
    "question": "稀疏架构",
    "excerpt": "论文：William Fedus、Barret Zoph、Noam Shazeer，Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity，2021年公开，JMLR 2022。原始论文。依据§2路由与稳定性、§3–4实验及表1–4",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "043-clip",
    "file": "043-clip.md",
    "kind": "paper",
    "day": 43,
    "year": 2021,
    "title": "043 · CLIP：用语言定义视觉分类器",
    "cardTitle": "043 · CLIP：用语言定义视觉分类器",
    "question": "多模态",
    "excerpt": "论文：Alec Radford等，Learning Transferable Visual Models From Natural Language Supervision，2021。原始论文 · 官方代码。依据方法§2、零样本实验§3.1、鲁棒性实验及数据重叠讨论；未重新训练4亿图文对模型。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "044-prefix-tuning",
    "file": "044-prefix-tuning.md",
    "kind": "paper",
    "day": 44,
    "year": 2021,
    "title": "044 · Prefix-Tuning：把任务知识放进每层的虚拟上下文",
    "cardTitle": "044 · Prefix-Tuning：把任务知识放进每层的虚拟上下文",
    "question": "参数高效微调",
    "excerpt": "论文：Xiang Lisa Li、Percy Liang，Prefix-Tuning: Optimizing Continuous Prompts for Generation，2021。原始论文。依据§3–7、表1–5及附录的训练设置和外推实例；未独立复现。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "045-prompt-tuning",
    "file": "045-prompt-tuning.md",
    "kind": "paper",
    "day": 45,
    "year": 2021,
    "title": "045 · Prompt Tuning：模型越大，任务接口能否越小",
    "cardTitle": "045 · Prompt Tuning：模型越大，任务接口能否越小",
    "question": "参数高效微调",
    "excerpt": "论文：Brian Lester、Rami Al-Rfou、Noah Constant，The Power of Scale for Parameter-Efficient Prompt Tuning，2021。原始论文。依据§2–7、图1与图3、表1–3及附录A的预算和重复设置；未独立运行训练。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "046-rope",
    "file": "046-rope.md",
    "kind": "paper",
    "day": 46,
    "year": 2021,
    "title": "046 · RoFormer：用旋转把相对位置写进注意力",
    "cardTitle": "046 · RoFormer：用旋转把相对位置写进注意力",
    "question": "位置表示",
    "excerpt": "论文：Jianlin Su等，RoFormer: Enhanced Transformer with Rotary Position Embedding，2021年首次公开。本文公式、图表按2023年修订版v5定位，覆盖§3推导、§4实验与限制；官方实现。未重新训练模型，修订版结果不全部视为2021初稿同时报告。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "047-lora",
    "file": "047-lora.md",
    "kind": "paper",
    "day": 47,
    "year": 2021,
    "title": "047 · LoRA：冻结大矩阵，只学习低秩改动",
    "cardTitle": "047 · LoRA：冻结大矩阵，只学习低秩改动",
    "question": "参数高效微调",
    "excerpt": "论文：Edward J. Hu等，LoRA: Low-Rank Adaptation of Large Language Models，2021年公开，ICLR 2022。原始论文。依据§4方法、§5实验、§7秩与矩阵选择分析及附录D；未复现175B训练。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "048-codex",
    "file": "048-codex.md",
    "kind": "paper",
    "day": 48,
    "year": 2021,
    "title": "048 · Codex：代码生成必须测“能运行”，也必须说明采样预算",
    "cardTitle": "048 · Codex：代码生成必须测“能运行”，也必须说明采样预算",
    "question": "代码与评估",
    "excerpt": "论文：Mark Chen等，Evaluating Large Language Models Trained on Code，2021。原始论文v2 · HumanEval官方数据与评估代码。依据§2评估、§3代码训练、§4监督适配与§6限制；未执行模型生成代码，也未复现训练。本篇讨论2021研究模型，不把它等同于后来同名产品。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "049-truthfulqa",
    "file": "049-truthfulqa.md",
    "kind": "paper",
    "day": 49,
    "year": 2021,
    "title": "049 · TruthfulQA：学会模仿人类，不等于学会避免错误",
    "cardTitle": "049 · TruthfulQA：学会模仿人类，不等于学会避免错误",
    "question": "评估",
    "excerpt": "论文：Stephanie Lin、Jacob Hilton、Owain Evans，TruthfulQA: Measuring How Models Mimic Human Falsehoods，2021年公开，ACL 2022。原始论文 · 官方基准。依据§2定义与建集、§3–4实验、附录B.1–B.2；原PDF包含后续模型附录，本篇主结论限定原始基线，不",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "050-flan",
    "file": "050-flan.md",
    "kind": "paper",
    "day": 50,
    "year": 2021,
    "title": "050 · FLAN：从会续写文本，到能按说明执行新任务",
    "cardTitle": "050 · FLAN：从会续写文本，到能按说明执行新任务",
    "question": "指令学习",
    "excerpt": "论文：Jason Wei等，Finetuned Language Models Are Zero-Shot Learners，2021年公开，ICLR 2022。原始论文。依据§2训练与划分、§3–4结果及附录C的完整表格；未复现137B训练。本篇是原始FLAN，不将后来的FLAN-T5、Flan Collection等结果混为同一论文。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "051-t0",
    "file": "051-t0.md",
    "kind": "paper",
    "day": 51,
    "year": 2021,
    "title": "051 · T0：把提示多样性变成训练数据的一部分",
    "cardTitle": "051 · T0：把提示多样性变成训练数据的一部分",
    "question": "指令学习",
    "excerpt": "论文：Victor Sanh等，Multitask Prompted Training Enables Zero-Shot Task Generalization，2021年公开，ICLR 2022。原始论文 · 模型与代码 · PromptSource。阅读范围为主文方法与结果、附录B预算、D划分、F数值表；长篇模板附录未逐模板审计，未复现训练。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "052-gsm8k",
    "file": "052-gsm8k.md",
    "kind": "paper",
    "day": 52,
    "year": 2021,
    "title": "052 · GSM8K与验证器：不会一次做对，能否从多份解答中选对？",
    "cardTitle": "052 · GSM8K与验证器：不会一次做对，能否从多份解答中选对？",
    "question": "推理与验证",
    "excerpt": "论文：Karl Cobbe等，Training Verifiers to Solve Math Word Problems，2021。原始论文 · 官方数据与代码。本文依据v2主文方法、实验及附录A—C；没有独立复现训练。论文中的数据规模使用其取整口径，不把发布仓库的文件行数与正文数字混用。",
    "eraId": "scale",
    "eraYears": "2020–2021",
    "eraLabel": "规模、检索与指令"
  },
  {
    "slug": "053-cot",
    "file": "053-cot.md",
    "kind": "paper",
    "day": 53,
    "year": 2022,
    "title": "053 · 思维链提示：把中间步骤放到答案之前",
    "cardTitle": "053 · 思维链提示：把中间步骤放到答案之前",
    "question": "推理",
    "excerpt": "论文：Jason Wei等，Chain-of-Thought Prompting Elicits Reasoning in Large Language Models，2022。原始论文。阅读范围为主文、附录A的提示分析、附录B数值表及部分错误分析；未逐条审计全部提示样本，也未复现实验。这里解读的是带有PaLM、Codex等扩展结果的论文版本，不把全部后续表",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "054-instructgpt",
    "file": "054-instructgpt.md",
    "kind": "paper",
    "day": 54,
    "year": 2022,
    "title": "054 · InstructGPT：让语言模型学习人更愿意接受的回答",
    "cardTitle": "054 · InstructGPT：让语言模型学习人更愿意接受的回答",
    "question": "对齐",
    "excerpt": "论文：Long Ouyang等，Training language models to follow instructions with human feedback，2022。原始论文 · 全文。阅读范围为主文方法与结果、附录A数据、C训练以及相关评估说明；未审计全部人工标注样例，未独立复现。本文讨论论文中的模型与流程，不以此推断后续产品的内部实现。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "055-star",
    "file": "055-star.md",
    "kind": "paper",
    "day": 55,
    "year": 2022,
    "title": "055 · STaR：把自己答对的推导变成下一轮训练数据",
    "cardTitle": "055 · STaR：把自己答对的推导变成下一轮训练数据",
    "question": "推理",
    "excerpt": "论文：Eric Zelikman、Yuhuai Wu、Jesse Mu、Noah D. Goodman，STaR: Self-Taught Reasoner — Bootstrapping Reasoning With Reasoning，2022。原始论文 · 全文。阅读范围为v2方法、主要实验、附录H超参数及相关失败分析；没有独立复现，也未逐条检查全部生",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "056-self-consistency",
    "file": "056-self-consistency.md",
    "kind": "paper",
    "day": 56,
    "year": 2022,
    "title": "056 · 自一致性：对多条推导的最终答案投票",
    "cardTitle": "056 · 自一致性：对多条推导的最终答案投票",
    "question": "推理",
    "excerpt": "论文：Xuezhi Wang等，Self-Consistency Improves Chain of Thought Reasoning in Language Models，2022年公开，ICLR 2023。原始论文 · v4全文。阅读范围为方法、主实验与附录A的资源和消融，不包含全部提示逐项审计；未独立复现。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "057-chinchilla",
    "file": "057-chinchilla.md",
    "kind": "paper",
    "day": 57,
    "year": 2022,
    "title": "057 · Chinchilla：同样的训练算力，该买更多参数还是更多数据？",
    "cardTitle": "057 · Chinchilla：同样的训练算力，该买更多参数还是更多数据？",
    "question": "规模定律",
    "excerpt": "论文：Jordan Hoffmann等，Training Compute-Optimal Large Language Models，2022。原始论文 · 全文。阅读范围为三种拟合方法、Chinchilla训练与主要评估、附录数据和调度分析；未复现数百次训练及拟合。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "058-flamingo",
    "file": "058-flamingo.md",
    "kind": "paper",
    "day": 58,
    "year": 2022,
    "title": "058 · Flamingo：把图像和视频接入语言模型的上下文学习",
    "cardTitle": "058 · Flamingo：把图像和视频接入语言模型的上下文学习",
    "question": "多模态",
    "excerpt": "论文：Jean-Baptiste Alayrac等，Flamingo: a Visual Language Model for Few-Shot Learning，2022。原始论文 · v2全文。阅读范围为方法、主结果与消融、附录A的提示和B的训练说明；未完整审计全部数据卡或视觉案例，未复现私有模型。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "059-flashattention",
    "file": "059-flashattention.md",
    "kind": "paper",
    "day": 59,
    "year": 2022,
    "title": "059 · FlashAttention：少搬运数据，让精确注意力更快",
    "cardTitle": "059 · FlashAttention：少搬运数据，让精确注意力更快",
    "question": "推理训练效率",
    "excerpt": "论文：Tri Dao等，FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness，2022。原始论文 · 全文 · 官方代码。阅读范围为算法1、定理1—2与对应证明思路、主实验和附录训练说明；未编译或测速内核。本文讨论初代论文，不能把后来版本的硬件支持和速度直接移植",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "060-react",
    "file": "060-react.md",
    "kind": "paper",
    "day": 60,
    "year": 2022,
    "title": "060 · ReAct：让推理决定行动，让观察修正推理",
    "cardTitle": "060 · ReAct：让推理决定行动，让观察修正推理",
    "question": "Agent",
    "excerpt": "论文：Shunyu Yao等，ReAct: Synergizing Reasoning and Acting in Language Models，2022年公开，ICLR 2023。原始论文 · v3全文 · 项目与代码。阅读范围为主文方法、四类任务实验、错误分析及相关训练说明；未复现在线检索或全部环境轨迹。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "061-gptq",
    "file": "061-gptq.md",
    "kind": "paper",
    "day": 61,
    "year": 2022,
    "title": "061 · GPTQ：压缩权重时，为什么要让剩下的权重补偿误差",
    "cardTitle": "061 · GPTQ：压缩权重时，为什么要让剩下的权重补偿误差",
    "question": "量化",
    "excerpt": "论文：Elias Frantar等，GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers，2022年公开，ICLR 2023。原始论文 · v2正文 · 官方代码。阅读范围为方法、算法1、语言模型量化与生成实验；没有运行量化内核或独立复现性能。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "062-helm",
    "file": "062-helm.md",
    "kind": "paper",
    "day": 62,
    "year": 2022,
    "title": "062 · HELM：模型评价为什么需要一张地图，而不只是一个分数",
    "cardTitle": "062 · HELM：模型评价为什么需要一张地图，而不只是一个分数",
    "question": "评估",
    "excerpt": "论文：Percy Liang等，Holistic Evaluation of Language Models，2022年公开，TMLR 2023。原始论文 · 正文 · 论文对应结果站v0.1.0 · 官方代码。阅读范围为评价分类、核心指标、提示适配、主实验与缺失范围讨论；未逐项审计全部数据集或重新调用历史模型。本文讨论论文的历史快照，结果站后续版本不应与之",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "063-pal",
    "file": "063-pal.md",
    "kind": "paper",
    "day": 63,
    "year": 2022,
    "title": "063 · PAL：让模型写出解法，让程序执行解法",
    "cardTitle": "063 · PAL：让模型写出解法，让程序执行解法",
    "question": "工具推理",
    "excerpt": "论文：Luyu Gao等，PAL: Program-aided Language Models，2022年公开，ICML 2023。原始论文 · v2正文 · 官方项目。阅读范围为主文、提示与执行消融、三种提示顺序、GSM-hard构造和错误例子；未重新调用历史Codex接口。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "064-speculative",
    "file": "064-speculative.md",
    "kind": "paper",
    "day": 64,
    "year": 2022,
    "title": "064 · 投机解码：小模型先起草，大模型怎样并行验收而不改变分布",
    "cardTitle": "064 · 投机解码：小模型先起草，大模型怎样并行验收而不改变分布",
    "question": "推理效率",
    "excerpt": "论文：Yaniv Leviathan、Matan Kalman、Yossi Matias，Fast Inference from Transformers via Speculative Decoding，2022年公开，ICML 2023。原始论文 · v2正文。阅读范围为算法1、接受采样证明、成本分析、T5实测与附录A；未复现TPU实现。这里解读的是这篇",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "065-constitutional",
    "file": "065-constitutional.md",
    "kind": "paper",
    "day": 65,
    "year": 2022,
    "title": "065 · Constitutional AI：把行为原则变成修改数据与偏好标签",
    "cardTitle": "065 · Constitutional AI：把行为原则变成修改数据与偏好标签",
    "question": "对齐",
    "excerpt": "论文：Yuntao Bai等，Constitutional AI: Harmlessness from AI Feedback，2022年。原始论文 · v1正文 · 官方原则、提示与样例。阅读范围为两阶段方法、训练数据、人工比较、消融及相关附录；未复现模型训练，官方样例仓库也不等于完整训练代码。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "066-blip2",
    "file": "066-blip2.md",
    "kind": "paper",
    "day": 66,
    "year": 2023,
    "title": "066 · BLIP-2：用可训练的查询桥梁连接冻结的视觉与语言模型",
    "cardTitle": "066 · BLIP-2：用可训练的查询桥梁连接冻结的视觉与语言模型",
    "question": "多模态",
    "excerpt": "论文：Junnan Li、Dongxu Li、Silvio Savarese、Steven Hoi，BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models，ICML 2023。原始论文 · v3正文 · 官方实",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "067-toolformer",
    "file": "067-toolformer.md",
    "kind": "paper",
    "day": 67,
    "year": 2023,
    "title": "067 · Toolformer：用后文预测损失筛选值得学习的工具调用",
    "cardTitle": "067 · Toolformer：用后文预测损失筛选值得学习的工具调用",
    "question": "Agent",
    "excerpt": "论文：Timo Schick等，Toolformer: Language Models Can Teach Themselves to Use Tools，2023年。原始论文 · v1正文。阅读范围为调用生成与筛选方法、五类API、主实验、解码消融及附录B训练设置；未复现历史工具后端。论文v1将基础GPT-J记为6.7B，本文以模型名称识别配置，不据此推算",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "068-llama",
    "file": "068-llama.md",
    "kind": "paper",
    "day": 68,
    "year": 2023,
    "title": "068 · LLaMA：把更多训练投入，换成较小模型的长期使用价值",
    "cardTitle": "068 · LLaMA：把更多训练投入，换成较小模型的长期使用价值",
    "question": "预训练",
    "excerpt": "论文：Hugo Touvron等，LLaMA: Open and Efficient Foundation Language Models，2023年。原始论文 · v1正文。阅读范围为数据、架构、训练预算、主要能力表格及偏差与成本分析；未重建完整训练语料或复现预训练。本篇讨论第一代LLaMA，后续Llama版本的架构、许可和训练细节不能倒灌进来。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "069-gpt4",
    "file": "069-gpt4.md",
    "kind": "paper",
    "day": 69,
    "year": 2023,
    "title": "069 · GPT-4技术报告：如何阅读一篇能力证据丰富、训练细节有限的报告",
    "cardTitle": "069 · GPT-4技术报告：如何阅读一篇能力证据丰富、训练细节有限的报告",
    "question": "多模态与评估",
    "excerpt": "论文：OpenAI，GPT-4 Technical Report，2023年首次公开。原始论文 · v6正文。本文采用2024年更新的v6，阅读范围为技术报告主文、考试方法、RLHF比较、污染检查与GSM8K说明；未逐项分析系统卡全部专题，未独立复现内部评测。以下模型表现指报告中的历史快照。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "070-reflexion",
    "file": "070-reflexion.md",
    "kind": "paper",
    "day": 70,
    "year": 2023,
    "title": "070｜Reflexion：把失败经验写成语言，下一次真的会更好吗？",
    "cardTitle": "Reflexion：把失败经验写成语言，下一次真的会更好吗？",
    "question": "Agent",
    "excerpt": "论文：Noah Shinn 等，Reflexion: Language Agents with Verbal Reinforcement Learning，2023。原始来源：论文、正文 v4、官方代码。以下依据 v4 的方法、实验与附录相关部分解读；没有独立运行仓库，也没有把所有提示词逐条复现。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "071-llava",
    "file": "071-llava.md",
    "kind": "paper",
    "day": 71,
    "year": 2023,
    "title": "071｜LLaVA：用文字教师，教会视觉模型听懂指令",
    "cardTitle": "LLaVA：用文字教师，教会视觉模型听懂指令",
    "question": "多模态",
    "excerpt": "论文：Haotian Liu、Chunyuan Li、Qingyang Wu、Yong Jae Lee，Visual Instruction Tuning，2023。原始论文、正文 v2、官方项目。本文依据 v2 的方法、实验、训练细节与限制解读，不把后续 LLaVA-1.5 等版本的配置倒灌进初代方法；没有独立复现训练。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "072-tree-of-thoughts",
    "file": "072-tree-of-thoughts.md",
    "kind": "paper",
    "day": 72,
    "year": 2023,
    "title": "072｜Tree of Thoughts：让语言模型保留岔路，而不是一路写到底",
    "cardTitle": "Tree of Thoughts：让语言模型保留岔路，而不是一路写到底",
    "question": "搜索推理",
    "excerpt": "论文：Shunyu Yao 等，Tree of Thoughts: Deliberate Problem Solving with Large Language Models，2023。论文、正文 v2、官方代码与提示。本文核对方法、三项主实验及附录B；没有独立运行历史 GPT-4 实验。以下 ToT 指外部控制的搜索过程，不是仅在提示词里写一句“请使用思维",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "073-gqa",
    "file": "073-gqa.md",
    "kind": "paper",
    "day": 73,
    "year": 2023,
    "title": "073｜GQA：查询头可以很多，历史记忆不必人手一份",
    "cardTitle": "GQA：查询头可以很多，历史记忆不必人手一份",
    "question": "推理效率",
    "excerpt": "论文：Joshua Ainslie 等，GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints，2023。论文、正文 v3、论文采用的 Flaxformer。本文核对全部方法与实验正文及训练稳定性附录；没有独立运行 TPU 基准。原文主实验是 T",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "074-qlora",
    "file": "074-qlora.md",
    "kind": "paper",
    "day": 74,
    "year": 2023,
    "title": "074｜QLoRA：把大模型放进显存，再用小适配器改变它",
    "cardTitle": "QLoRA：把大模型放进显存，再用小适配器改变它",
    "question": "参数高效微调",
    "excerpt": "论文：Tim Dettmers、Artidoro Pagnoni、Ari Holtzman、Luke Zettlemoyer，QLoRA: Efficient Finetuning of Quantized LLMs，2023。论文、正文 v1、官方代码。本文核对方法、定量实验和训练超参数附录；没有独立复现65B训练，也没有把代码后续版本的默认值当成论文配置",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "075-dpo",
    "file": "075-dpo.md",
    "kind": "paper",
    "day": 75,
    "year": 2023,
    "title": "075｜DPO：把奖励模型藏进概率比，直接学习偏好",
    "cardTitle": "DPO：把奖励模型藏进概率比，直接学习偏好",
    "question": "对齐",
    "excerpt": "论文：Rafael Rafailov 等，Direct Preference Optimization: Your Language Model is Secretly a Reward Model，首次公开于2023年。论文、正文 v3。本文以2024年更新的 v3 方法、理论、实验和实现附录为依据；没有独立复现训练。DPO 属于直接偏好优化，不能只因名称",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "076-awq",
    "file": "076-awq.md",
    "kind": "paper",
    "day": 76,
    "year": 2023,
    "title": "076｜AWQ：量化权重时，为什么要先看激活？",
    "cardTitle": "AWQ：量化权重时，为什么要先看激活？",
    "question": "量化",
    "excerpt": "论文：Ji Lin 等，AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration，2023。论文、正文 v2、官方代码。本文核对 v2 的方法、定量实验、系统测量和限制附录；没有独立运行量化与速度测试。后续实现变化不包含在本文实证结论中。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "077-lost-middle",
    "file": "077-lost-middle.md",
    "kind": "paper",
    "day": 77,
    "year": 2023,
    "title": "077｜Lost in the Middle：上下文装得下，不代表每个位置都用得好",
    "cardTitle": "Lost in the Middle：上下文装得下，不代表每个位置都用得好",
    "question": "长上下文评估",
    "excerpt": "论文：Nelson F. Liu 等，Lost in the Middle: How Language Models Use Long Contexts，首次公开于2023年。论文、正文 v3、作者项目。本文核对正文及歧义、干扰项、模型补充、token统计和完整问答结果附录；没有独立重跑历史API。它是一篇诊断与评测论文，不提出一个已经解决长上下文问题的新训",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "078-llama2",
    "file": "078-llama2.md",
    "kind": "paper",
    "day": 78,
    "year": 2023,
    "title": "078｜Llama 2：把预训练模型变成可持续改进的对话系统",
    "cardTitle": "Llama 2：把预训练模型变成可持续改进的对话系统",
    "question": "预训练与对齐",
    "excerpt": "论文：Hugo Touvron 等，Llama 2: Open Foundation and Fine-Tuned Chat Models，2023。本文依据论文 v2 正文的预训练、SFT、奖励建模、迭代对齐与评价章节，重点核对表 1、3、4、6—8、11 和图 12；不把模型报告理解为所有训练数据均可重建的复现说明。代码与模型入口见官方仓库。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "079-vllm",
    "file": "079-vllm.md",
    "kind": "paper",
    "day": 79,
    "year": 2023,
    "title": "079｜vLLM 与 PagedAttention：不改变模型，也能让更多请求同时运行",
    "cardTitle": "vLLM 与 PagedAttention：不改变模型，也能让更多请求同时运行",
    "question": "推理系统",
    "excerpt": "论文：Woosuk Kwon 等，Efficient Memory Management for Large Language Model Serving with PagedAttention，2023，SOSP。依据论文 v1的方法、系统实现、全部实验与讨论章节；代码见官方仓库。这里分析论文时代的系统配置，仓库后续版本的功能和性能不自动属于原论文证据。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "080-rlaif",
    "file": "080-rlaif.md",
    "kind": "paper",
    "day": 80,
    "year": 2023,
    "title": "080｜RLAIF：让模型提供反馈，能否得到人更喜欢的回答？",
    "cardTitle": "RLAIF：让模型提供反馈，能否得到人更喜欢的回答？",
    "question": "对齐",
    "excerpt": "论文：Harrison Lee 等，RLAIF vs. RLHF: Scaling Reinforcement Learning from Human Feedback with AI Feedback，首次公开于 2023；本文核对2024 年 v3的方法、结果及附录 B—K，因而包括后续版本中的直接反馈实验。没有独立运行 PaLM 2 训练；论文也指出服",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "081-swebench",
    "file": "081-swebench.md",
    "kind": "paper",
    "day": 81,
    "year": 2023,
    "title": "081｜SWE-bench：会写函数之后，还要能修好真实仓库",
    "cardTitle": "SWE-bench：会写函数之后，还要能修好真实仓库",
    "question": "Agent评估",
    "excerpt": "论文：Carlos E. Jimenez 等，SWE-bench: Can Language Models Resolve Real-World GitHub Issues?，2023，ICLR 2024。本文核对论文 v3的构建、评价、检索实验及相关附录；该版本包含后补的模型和 Lite 结果，不能将所有表项都标作 2023 年首版成绩。数据和执行工具见官",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "082-self-rag",
    "file": "082-self-rag.md",
    "kind": "paper",
    "day": 82,
    "year": 2023,
    "title": "082｜Self-RAG：学会决定何时检索，再检查证据是否支持回答",
    "cardTitle": "Self-RAG：学会决定何时检索，再检查证据是否支持回答",
    "question": "检索增强",
    "excerpt": "论文：Akari Asai 等，Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection，2023，ICLR 2024。本文依据首版正文的算法、实验和训练/推理附录；结果数值保留该版口径。部分特殊 token 在 HTML 中渲染不完整，以下以其语义名称解释，",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "083-mamba",
    "file": "083-mamba.md",
    "kind": "paper",
    "day": 83,
    "year": 2023,
    "title": "083｜Mamba：用选择性的状态压缩，重新挑战注意力架构",
    "cardTitle": "Mamba：用选择性的状态压缩，重新挑战注意力架构",
    "question": "序列架构",
    "excerpt": "论文：Albert Gu、Tri Dao，Mamba: Linear-Time Sequence Modeling with Selective State Spaces，2023。本文依据论文 v2的状态空间推导、选择机制、语言及合成实验、消融和效率附录；DNA、音频作为适用边界的补充证据。实现见官方代码。未独立训练模型或重测吞吐。",
    "eraId": "align",
    "eraYears": "2022–2023",
    "eraLabel": "推理、对齐与开源"
  },
  {
    "slug": "084-mixtral",
    "file": "084-mixtral.md",
    "kind": "paper",
    "day": 84,
    "year": 2024,
    "title": "084｜Mixtral：用更多参数储存能力，用少数专家处理每个 token",
    "cardTitle": "Mixtral：用更多参数储存能力，用少数专家处理每个 token",
    "question": "稀疏架构",
    "excerpt": "论文：Albert Q. Jiang 等，Mixtral of Experts，2024。本文依据论文首版的架构、评价、指令微调和路由分析全文；官方实现见代码仓库。论文是较短的模型报告，预训练数据总量、完整优化配置等未披露，不能把架构可运行误称为训练可完整重建。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "085-medusa",
    "file": "085-medusa.md",
    "kind": "paper",
    "day": 85,
    "year": 2024,
    "title": "085｜Medusa：让一个模型提前猜多步，再一次验证候选树",
    "cardTitle": "Medusa：让一个模型提前猜多步，再一次验证候选树",
    "question": "推理效率",
    "excerpt": "论文：Tianle Cai 等，Medusa: Simple LLM Inference Acceleration Framework with Multiple Decoding Heads，2024，ICML。依据论文 v3的方法、主实验、树与接受阈值消融、训练和硬件附录；代码见官方仓库。文中“质量接近”与“分布完全不变”分别讨论，未独立计时。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "086-deepseekmath",
    "file": "086-deepseekmath.md",
    "kind": "paper",
    "day": 86,
    "year": 2024,
    "title": "086｜DeepSeekMath：数学数据、在线探索与组内相对优势",
    "cardTitle": "DeepSeekMath：数学数据、在线探索与组内相对优势",
    "question": "推理与RL",
    "excerpt": "论文：Zhihong Shao、Peiyi Wang 等，DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models，2024。依据原文 v3的语料构建、训练设置、GRPO 公式及实验讨论；模型资源见官方仓库。以下解释区分数学领域继续预训练与强化学习的增",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "087-sweagent",
    "file": "087-sweagent.md",
    "kind": "paper",
    "day": 87,
    "year": 2024,
    "title": "087｜SWE-agent：模型不会稳定修代码，问题可能也在工具接口",
    "cardTitle": "SWE-agent：模型不会稳定修代码，问题可能也在工具接口",
    "question": "Agent",
    "excerpt": "论文：John Yang、Carlos E. Jimenez 等，SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering，2024。依据原文 v3的接口设计、主实验、消融与行为分析附录；代码及配置见官方项目。实验对应文中模型快照和当时 API 价格，不能作为当前产品",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "088-mamba2",
    "file": "088-mamba2.md",
    "kind": "paper",
    "day": 88,
    "year": 2024,
    "title": "088｜Mamba-2：把递归状态写成结构化矩阵，找到更快的计算方式",
    "cardTitle": "Mamba-2：把递归状态写成结构化矩阵，找到更快的计算方式",
    "question": "序列架构",
    "excerpt": "论文：Tri Dao、Albert Gu，Transformers are SSMs: Generalized Models and Efficient Algorithms Through Structured State Space Duality，2024，ICML。依据原文 v1的 SSD 推导、分块算法、架构和实验附录；实现见官方 Mamba 仓库",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "089-sae",
    "file": "089-sae.md",
    "kind": "paper",
    "day": 89,
    "year": 2024,
    "title": "089｜Scaling Sparse Autoencoders：把隐藏激活拆成特征，也要检验解释是否完整",
    "cardTitle": "Scaling Sparse Autoencoders：把隐藏激活拆成特征，也要检验解释是否完整",
    "question": "可解释性",
    "excerpt": "论文：Leo Gao、Tom Dupré la Tour 等，Scaling and evaluating sparse autoencoders，2024。依据原文 v1的方法、评估、规模实验和优化附录；代码见官方仓库。GPT-4 激活与完整底层训练资料并未全部开放，因此开放模型部分和闭源模型部分的可复现范围不同。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "090-graphrag",
    "file": "090-graphrag.md",
    "kind": "paper",
    "day": 90,
    "year": 2024,
    "title": "090｜GraphRAG：当问题问的是整个资料库，检索几段相似文本还够吗",
    "cardTitle": "GraphRAG：当问题问的是整个资料库，检索几段相似文本还够吗",
    "question": "检索增强",
    "excerpt": "论文：Darren Edge 等，From Local to Global: A GraphRAG Approach to Query-Focused Summarization，首次公开于 2024。本文依据2025 年修订的 v2，包括新增的声明数量与多样性评估；实现见官方仓库。版本中的实验范围与当前软件全部功能不等同，未独立重建图索引。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "091-test-time-scaling",
    "file": "091-test-time-scaling.md",
    "kind": "paper",
    "day": 91,
    "year": 2024,
    "title": "091｜Test-Time Scaling：不是一律多想，而是决定把计算花在哪里",
    "cardTitle": "Test-Time Scaling：不是一律多想，而是决定把计算花在哪里",
    "question": "推理预算",
    "excerpt": "论文：Charlie Snell、Jaehoon Lee、Kelvin Xu、Aviral Kumar，Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters，2024。依据原文 v1的搜索、修订、成本比较与附录。主要模型为 PaL",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "092-deepseekv3",
    "file": "092-deepseekv3.md",
    "kind": "paper",
    "day": 92,
    "year": 2024,
    "title": "092｜DeepSeek-V3：让模型、数值精度与通信共同接受成本约束",
    "cardTitle": "DeepSeek-V3：让模型、数值精度与通信共同接受成本约束",
    "question": "架构与训练",
    "excerpt": "大模型训练像一座工厂：增加工位可以扩大产能，但如果原料搬运、设备等待和库存占满了预算，工位越多未必越划算。DeepSeek-V3 的中心问题是，怎样在扩大模型容量时，控制真正活跃的计算、专家之间的数据搬运，以及生成时的历史缓存。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "093-olmo2",
    "file": "093-olmo2.md",
    "kind": "paper",
    "day": 93,
    "year": 2024,
    "title": "093｜OLMo 2：把语言模型的训练过程变成可以研究的对象",
    "cardTitle": "OLMo 2：把语言模型的训练过程变成可以研究的对象",
    "question": "开放训练配方",
    "excerpt": "拿到一份模型权重，像拿到一道成品菜：可以品尝，却不知道哪些原料、火候和处理顺序决定了味道。OLMo 2 希望把原料、训练代码、配方、日志和中间检查点一起提供，让研究者能够追问能力是在什么时候、因为什么形成的。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "094-r1",
    "file": "094-r1.md",
    "kind": "paper",
    "day": 94,
    "year": 2025,
    "title": "094｜DeepSeek-R1：奖励正确答案，为什么能改变解题过程",
    "cardTitle": "DeepSeek-R1：奖励正确答案，为什么能改变解题过程",
    "question": "推理与RL",
    "excerpt": "如果教师只给最终答案打分，而不逐行示范推导，学生能否逐渐学会检查、换方法和延长思考？R1-Zero 探索的是这个问题在强预训练语言模型上的版本。它从 DeepSeek-V3-Base 出发，用数学答案和代码测试等可验证反馈进行强化学习，不先执行一轮解题示范微调。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "095-s1",
    "file": "095-s1.md",
    "kind": "paper",
    "day": 95,
    "year": 2025,
    "title": "095｜s1：少量示范与一个停止按钮，怎样改变推理预算",
    "cardTitle": "s1：少量示范与一个停止按钮，怎样改变推理预算",
    "question": "推理预算",
    "excerpt": "一个模型已经会解题，却可能过早停止，也可能陷入长篇重复。s1 把问题拆成两部分：先用少量精心选择的长推理示范，让现有指令模型学会更完整的解题方式；再在生成时直接控制何时结束推理。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "096-llada",
    "file": "096-llada.md",
    "kind": "paper",
    "day": 96,
    "year": 2025,
    "title": "096｜LLaDA：语言模型一定要从左到右生成吗",
    "cardTitle": "LLaDA：语言模型一定要从左到右生成吗",
    "question": "扩散语言模型",
    "excerpt": "自回归模型像写作者：已有前文，再写下一个词。LLaDA 更像做填空题：先把整段答案空出来，每一轮根据题目和已填内容，决定更多位置该放什么，逐步得到完整回答。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "097-dapo",
    "file": "097-dapo.md",
    "kind": "paper",
    "day": 97,
    "year": 2025,
    "title": "097｜DAPO：让长推理强化学习真正训练起来的四处修改",
    "cardTitle": "DAPO：让长推理强化学习真正训练起来的四处修改",
    "question": "推理与RL",
    "excerpt": "同样写着 GRPO，两个训练程序可能得到很不一样的模型。原因不一定在大公式：如果一批题全部答对或全部答错，就没有组内比较信号；如果长答案每个 token 的梯度被过度稀释，重复文本可能难以抑制；如果答案只是被长度上限截断，却被当成数学错误惩罚，奖励也会混入噪声。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "098-rubric-verification",
    "file": "098-rubric-verification.md",
    "kind": "paper",
    "day": 98,
    "year": 2026,
    "title": "098｜DeepVerifier：让研究型 Agent 检查证据，而不是再自信一次",
    "cardTitle": "DeepVerifier：让研究型 Agent 检查证据，而不是再自信一次",
    "question": "验证与Agent",
    "excerpt": "一个研究 Agent 给出了貌似完整的答案，另一个模型看完说“合理”，并不等于核查成功。两者可能依赖同一条错误线索，或者都没有检查决定答案的关键来源。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "099-autotts",
    "file": "099-autotts.md",
    "kind": "paper",
    "day": 99,
    "year": 2026,
    "title": "099｜AutoTTS：让 Agent 搜索怎样分配推理计算",
    "cardTitle": "AutoTTS：让 Agent 搜索怎样分配推理计算",
    "question": "推理控制",
    "excerpt": "当模型有十份计算预算，应该生成十条短思路，还是把一条思路想十倍长？答案往往取决于当前候选是否一致、某条路径是否还在取得进展。以往这些规则大多由研究者手工写出。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "100-tts-protocol",
    "file": "100-tts-protocol.md",
    "kind": "paper",
    "day": 100,
    "year": 2026,
    "title": "100｜推理时扩展的评估协议：会找到答案，还要会选答案",
    "cardTitle": "推理时扩展的评估协议：会找到答案，还要会选答案",
    "question": "评估协议",
    "excerpt": "假设一个模型对同一道题生成了十份解答，其中一份正确。研究者看过标准答案后可以说“十次内能做出来”；用户拿到的是系统最终挑出的那一份。如果选择器偏爱错误但流畅的解答，多生成几份甚至可能降低最终正确率。",
    "eraId": "system",
    "eraYears": "2024–2026",
    "eraLabel": "推理系统与 Agent"
  },
  {
    "slug": "101-epilogue",
    "file": "101-系列总结.md",
    "kind": "epilogue",
    "day": 101,
    "year": null,
    "title": "从语言建模到推理系统：把论文思想变成可检验的问题",
    "cardTitle": "系列总结",
    "question": "跨论文比较与实验阅读方法",
    "excerpt": "读完一条技术路线，最有用的收获不是记住哪一年谁超过了谁，而是能判断：一个结果来自模型容量、训练数据、优化方法、推理策略，还是评价口径。语言模型的能力由这些环节共同形成，单一排行榜分数很少能替我们完成归因。",
    "eraId": "epilogue",
    "eraYears": "",
    "eraLabel": "收尾"
  }
];
window.SERIES_SLUG_MAP = {
  "00-发展时间线总览.md": "00-timeline",
  "00-发展时间线总览": "00-timeline",
  "001-lstm.md": "001-lstm",
  "001-lstm": "001-lstm",
  "002-nnlm.md": "002-nnlm",
  "002-nnlm": "002-nnlm",
  "003-rnnlm.md": "003-rnnlm",
  "003-rnnlm": "003-rnnlm",
  "004-word2vec.md": "004-word2vec",
  "004-word2vec": "004-word2vec",
  "005-negative-sampling.md": "005-negative-sampling",
  "005-negative-sampling": "005-negative-sampling",
  "006-seq2seq.md": "006-seq2seq",
  "006-seq2seq": "006-seq2seq",
  "007-attention.md": "007-attention",
  "007-attention": "007-attention",
  "008-glove.md": "008-glove",
  "008-glove": "008-glove",
  "009-adam.md": "009-adam",
  "009-adam": "009-adam",
  "010-distillation.md": "010-distillation",
  "010-distillation": "010-distillation",
  "011-bpe.md": "011-bpe",
  "011-bpe": "011-bpe",
  "012-layernorm.md": "012-layernorm",
  "012-layernorm": "012-layernorm",
  "013-fasttext.md": "013-fasttext",
  "013-fasttext": "013-fasttext",
  "014-sparse-moe.md": "014-sparse-moe",
  "014-sparse-moe": "014-sparse-moe",
  "015-transformer.md": "015-transformer",
  "015-transformer": "015-transformer",
  "016-elmo.md": "016-elmo",
  "016-elmo": "016-elmo",
  "017-gpt.md": "017-gpt",
  "017-gpt": "017-gpt",
  "018-bert.md": "018-bert",
  "018-bert": "018-bert",
  "019-transformer-xl.md": "019-transformer-xl",
  "019-transformer-xl": "019-transformer-xl",
  "020-adapters.md": "020-adapters",
  "020-adapters": "020-adapters",
  "021-gpt2.md": "021-gpt2",
  "021-gpt2": "021-gpt2",
  "022-xlnet.md": "022-xlnet",
  "022-xlnet": "022-xlnet",
  "023-roberta.md": "023-roberta",
  "023-roberta": "023-roberta",
  "024-megatron.md": "024-megatron",
  "024-megatron": "024-megatron",
  "025-albert.md": "025-albert",
  "025-albert": "025-albert",
  "026-zero.md": "026-zero",
  "026-zero": "026-zero",
  "027-t5.md": "027-t5",
  "027-t5": "027-t5",
  "028-bart.md": "028-bart",
  "028-bart": "028-bart",
  "029-scaling-laws.md": "029-scaling-laws",
  "029-scaling-laws": "029-scaling-laws",
  "030-realm.md": "030-realm",
  "030-realm": "030-realm",
  "031-electra.md": "031-electra",
  "031-electra": "031-electra",
  "032-dpr.md": "032-dpr",
  "032-dpr": "032-dpr",
  "033-longformer.md": "033-longformer",
  "033-longformer": "033-longformer",
  "034-rag.md": "034-rag",
  "034-rag": "034-rag",
  "035-gpt3.md": "035-gpt3",
  "035-gpt3": "035-gpt3",
  "036-fid.md": "036-fid",
  "036-fid": "036-fid",
  "037-gshard.md": "037-gshard",
  "037-gshard": "037-gshard",
  "038-bigbird.md": "038-bigbird",
  "038-bigbird": "038-bigbird",
  "039-mmlu.md": "039-mmlu",
  "039-mmlu": "039-mmlu",
  "040-performer.md": "040-performer",
  "040-performer": "040-performer",
  "041-pile.md": "041-pile",
  "041-pile": "041-pile",
  "042-switch.md": "042-switch",
  "042-switch": "042-switch",
  "043-clip.md": "043-clip",
  "043-clip": "043-clip",
  "044-prefix-tuning.md": "044-prefix-tuning",
  "044-prefix-tuning": "044-prefix-tuning",
  "045-prompt-tuning.md": "045-prompt-tuning",
  "045-prompt-tuning": "045-prompt-tuning",
  "046-rope.md": "046-rope",
  "046-rope": "046-rope",
  "047-lora.md": "047-lora",
  "047-lora": "047-lora",
  "048-codex.md": "048-codex",
  "048-codex": "048-codex",
  "049-truthfulqa.md": "049-truthfulqa",
  "049-truthfulqa": "049-truthfulqa",
  "050-flan.md": "050-flan",
  "050-flan": "050-flan",
  "051-t0.md": "051-t0",
  "051-t0": "051-t0",
  "052-gsm8k.md": "052-gsm8k",
  "052-gsm8k": "052-gsm8k",
  "053-cot.md": "053-cot",
  "053-cot": "053-cot",
  "054-instructgpt.md": "054-instructgpt",
  "054-instructgpt": "054-instructgpt",
  "055-star.md": "055-star",
  "055-star": "055-star",
  "056-self-consistency.md": "056-self-consistency",
  "056-self-consistency": "056-self-consistency",
  "057-chinchilla.md": "057-chinchilla",
  "057-chinchilla": "057-chinchilla",
  "058-flamingo.md": "058-flamingo",
  "058-flamingo": "058-flamingo",
  "059-flashattention.md": "059-flashattention",
  "059-flashattention": "059-flashattention",
  "060-react.md": "060-react",
  "060-react": "060-react",
  "061-gptq.md": "061-gptq",
  "061-gptq": "061-gptq",
  "062-helm.md": "062-helm",
  "062-helm": "062-helm",
  "063-pal.md": "063-pal",
  "063-pal": "063-pal",
  "064-speculative.md": "064-speculative",
  "064-speculative": "064-speculative",
  "065-constitutional.md": "065-constitutional",
  "065-constitutional": "065-constitutional",
  "066-blip2.md": "066-blip2",
  "066-blip2": "066-blip2",
  "067-toolformer.md": "067-toolformer",
  "067-toolformer": "067-toolformer",
  "068-llama.md": "068-llama",
  "068-llama": "068-llama",
  "069-gpt4.md": "069-gpt4",
  "069-gpt4": "069-gpt4",
  "070-reflexion.md": "070-reflexion",
  "070-reflexion": "070-reflexion",
  "071-llava.md": "071-llava",
  "071-llava": "071-llava",
  "072-tree-of-thoughts.md": "072-tree-of-thoughts",
  "072-tree-of-thoughts": "072-tree-of-thoughts",
  "073-gqa.md": "073-gqa",
  "073-gqa": "073-gqa",
  "074-qlora.md": "074-qlora",
  "074-qlora": "074-qlora",
  "075-dpo.md": "075-dpo",
  "075-dpo": "075-dpo",
  "076-awq.md": "076-awq",
  "076-awq": "076-awq",
  "077-lost-middle.md": "077-lost-middle",
  "077-lost-middle": "077-lost-middle",
  "078-llama2.md": "078-llama2",
  "078-llama2": "078-llama2",
  "079-vllm.md": "079-vllm",
  "079-vllm": "079-vllm",
  "080-rlaif.md": "080-rlaif",
  "080-rlaif": "080-rlaif",
  "081-swebench.md": "081-swebench",
  "081-swebench": "081-swebench",
  "082-self-rag.md": "082-self-rag",
  "082-self-rag": "082-self-rag",
  "083-mamba.md": "083-mamba",
  "083-mamba": "083-mamba",
  "084-mixtral.md": "084-mixtral",
  "084-mixtral": "084-mixtral",
  "085-medusa.md": "085-medusa",
  "085-medusa": "085-medusa",
  "086-deepseekmath.md": "086-deepseekmath",
  "086-deepseekmath": "086-deepseekmath",
  "087-sweagent.md": "087-sweagent",
  "087-sweagent": "087-sweagent",
  "088-mamba2.md": "088-mamba2",
  "088-mamba2": "088-mamba2",
  "089-sae.md": "089-sae",
  "089-sae": "089-sae",
  "090-graphrag.md": "090-graphrag",
  "090-graphrag": "090-graphrag",
  "091-test-time-scaling.md": "091-test-time-scaling",
  "091-test-time-scaling": "091-test-time-scaling",
  "092-deepseekv3.md": "092-deepseekv3",
  "092-deepseekv3": "092-deepseekv3",
  "093-olmo2.md": "093-olmo2",
  "093-olmo2": "093-olmo2",
  "094-r1.md": "094-r1",
  "094-r1": "094-r1",
  "095-s1.md": "095-s1",
  "095-s1": "095-s1",
  "096-llada.md": "096-llada",
  "096-llada": "096-llada",
  "097-dapo.md": "097-dapo",
  "097-dapo": "097-dapo",
  "098-rubric-verification.md": "098-rubric-verification",
  "098-rubric-verification": "098-rubric-verification",
  "099-autotts.md": "099-autotts",
  "099-autotts": "099-autotts",
  "100-tts-protocol.md": "100-tts-protocol",
  "100-tts-protocol": "100-tts-protocol",
  "101-系列总结.md": "101-epilogue",
  "101-系列总结": "101-epilogue"
};
