window.SERIES_POSTS = [
  {
    "slug": "00-timeline",
    "file": "00-发展时间线总览.md",
    "kind": "overview",
    "day": 0,
    "year": null,
    "title": "机器人经典基础发展时间线：从几何表示到完整自主系统",
    "cardTitle": "发展时间线总览",
    "question": "各阶段的问题、方法与继承关系",
    "excerpt": "机器人研究没有一条替代所有旧方法的单线历史。位置表示、状态估计、规划和控制长期并行发展，并在完整系统中结合。更准确的地图是：数学工具使某类问题变得可解，算法使它变得可算，传感器和计算平台使它能够实时运行，公开基准再暴露系统边界。",
    "eraId": "overview",
    "eraYears": "",
    "eraLabel": "总览"
  },
  {
    "slug": "001-dh",
    "file": "001-dh.md",
    "kind": "paper",
    "day": 1,
    "year": 1955,
    "title": "001｜Denavit–Hartenberg：把一台机械臂写成一串坐标变换",
    "cardTitle": "Denavit–Hartenberg：把一台机械臂写成一串坐标变换",
    "question": "几何",
    "excerpt": "证据范围：原出版记录和摘要可核对；原版PDF的完整文字与图式未取得稳定解析。以下明确分开原文可确认的主张与采用现代标准D-H记号的教学推导，不对原论文两个空间机构示例的具体数值作未核实转述。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "002-kalman",
    "file": "002-kalman.md",
    "kind": "paper",
    "day": 2,
    "year": 1960,
    "title": "002｜Kalman滤波：把过去的观测压缩成可递推的信念",
    "cardTitle": "Kalman滤波：把过去的观测压缩成可递推的信念",
    "question": "估计",
    "excerpt": "机器人轮速计容易累积误差，外部定位又带噪声。应该相信哪一个？Kalman滤波不固定规定“各信一半”，而根据预测和测量的不确定性，逐步计算融合权重。它同时递推状态估计与误差协方差，使越来越长的历史不必全部保存为原始测量。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "003-astar",
    "file": "003-astar.md",
    "kind": "paper",
    "day": 3,
    "year": 1968,
    "title": "003｜A*：用可信的剩余代价引导最短路搜索",
    "cardTitle": "A*：用可信的剩余代价引导最短路搜索",
    "question": "规划",
    "excerpt": "阅读范围：已逐页视觉核对 Stanford 保存的八页原始扫描稿（期刊 100–107 页），包括算法、定理条件和讨论。下文的反证是教学重述；1972 年后续勘误未作为本篇已经完整核读的证明材料。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "004-resolved-rate",
    "file": "004-resolved-rate.md",
    "kind": "paper",
    "day": 4,
    "year": 1969,
    "title": "004｜Resolved Motion Rate：让操作者直接指定手的运动方向",
    "cardTitle": "Resolved Motion Rate：让操作者直接指定手的运动方向",
    "question": "几何",
    "excerpt": "证据范围：已核对原始题名、年份与摘要；出版页面的正文访问受到限制，尚未取得可可靠核对的原版完整实验。下面以明确标注的现代微分运动学推导解释思想，不将阻尼逆解、零空间优化等后续扩展归为1969年论文贡献。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "005-newton-euler",
    "file": "005-newton-euler.md",
    "kind": "paper",
    "day": 5,
    "year": 1980,
    "title": "005｜递归Newton–Euler：沿机械臂来回走一遍，计算关节力矩",
    "cardTitle": "递归Newton–Euler：沿机械臂来回走一遍，计算关节力矩",
    "question": "动力学",
    "excerpt": "证据范围：原题名、摘要和出版元数据已核对；全文图表与运算计数的详细条件尚未取得稳定解析。本文用现代空间向量解释递归原理，相关记号不等于1980年原文的逐式复刻。原摘要的硬件时间主张仅作为历史报告，不用于现代平台速度比较。",
    "eraId": "动力学",
    "eraYears": "",
    "eraLabel": "动力学"
  },
  {
    "slug": "006-ransac",
    "file": "006-ransac.md",
    "kind": "paper",
    "day": 6,
    "year": 1981,
    "title": "006｜RANSAC：先找到可信的小群体，再估计几何模型",
    "cardTitle": "RANSAC：先找到可信的小群体，再估计几何模型",
    "question": "视觉",
    "excerpt": "视觉匹配中，一部分对应点根本不是同一个物体位置。把它们与正确点一起做最小二乘，得到的不是稍有噪声的答案，而可能是被错误匹配拖偏的模型。RANSAC先用很少的数据假设模型，再问其余数据是否同意这个假设。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "007-hybrid-force",
    "file": "007-hybrid-force.md",
    "kind": "paper",
    "day": 7,
    "year": 1981,
    "title": "007｜混合位置／力控制：沿桌面移动，同时保持接触压力",
    "cardTitle": "混合位置／力控制：沿桌面移动，同时保持接触压力",
    "question": "控制",
    "excerpt": "机器人擦桌子时，沿桌面的方向希望按轨迹移动，垂直桌面则希望保持适当压力。若两个方向都严格追踪位置，桌面高度的几毫米误差就可能产生很大接触力；若都控制力，又难保证擦拭路线。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "008-lucas-kanade",
    "file": "008-lucas-kanade.md",
    "kind": "paper",
    "day": 8,
    "year": 1981,
    "title": "008｜Lucas–Kanade：用图像梯度寻找匹配，而不是盲目枚举位移",
    "cardTitle": "Lucas–Kanade：用图像梯度寻找匹配，而不是盲目枚举位移",
    "question": "视觉",
    "excerpt": "阅读范围：已逐页视觉核对六页原文，涵盖一维推导、多维推广、光度与仿射扩展及立体匹配演示。下文统一符号的正规方程是教学改写；原实验包含人工引导，不是自动稠密光流基准。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "009-configuration-space",
    "file": "009-configuration-space.md",
    "kind": "paper",
    "day": 9,
    "year": 1983,
    "title": "009｜构型空间：把有体积的机器人变成空间中的一个点",
    "cardTitle": "构型空间：把有体积的机器人变成空间中的一个点",
    "question": "规划",
    "excerpt": "机器人中心点没有碰墙，不代表机器人本体没有碰墙。规划时若一直让复杂形状在障碍物之间运动，碰撞关系很难直接搜索。构型空间把机器人每一个完整姿态表示成一个点，再把会导致碰撞的姿态收集成“构型空间障碍物”。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "010-featherstone",
    "file": "010-featherstone.md",
    "kind": "paper",
    "day": 10,
    "year": 1983,
    "title": "010｜Articulated-Body Algorithm：不形成整块逆矩阵，也能算出机器人加速度",
    "cardTitle": "Articulated-Body Algorithm：不形成整块逆矩阵，也能算出机器人加速度",
    "question": "动力学",
    "excerpt": "证据范围：原摘要与作者书目已核对，原版全文未取得稳定的开放解析。算法教学同时参考作者Spatialv2文档中FDab、FDcrb和ID的区分；这份后续软件属于外部补充，不用于声称1983年实现已包含全部现代扩展。原文详细运算表的数值在此不作未核实转述。",
    "eraId": "动力学",
    "eraYears": "",
    "eraLabel": "动力学"
  },
  {
    "slug": "011-brockett",
    "file": "011-brockett.md",
    "kind": "paper",
    "day": 11,
    "year": 1984,
    "title": "011｜指数积：用关节轴直接写出机器人的运动",
    "cardTitle": "指数积：用关节轴直接写出机器人的运动",
    "question": "几何",
    "excerpt": "阅读范围：原始章节全文未能取得，不能逐页核查 Brockett 的论证及例题。下面对核心公式的教学推导，另据 Lynch 与 Park 的官方教材配套讲解 §4.1.1核对；现代符号和实现步骤不冒充原文记号。本文侧重理解这一经典思想，原稿实验与章节位置保持未核实状态。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "012-manipulability",
    "file": "012-manipulability.md",
    "kind": "paper",
    "day": 12,
    "year": 1985,
    "title": "012｜可操作度：能到达的位置，不一定容易运动",
    "cardTitle": "可操作度：能到达的位置，不一定容易运动",
    "question": "几何",
    "excerpt": "阅读范围：已逐页视觉核对作者保存的七页原文（3–9 页），包括指标定义、尺度归一化、机械臂及手指例题。文章没有实机控制性能基准；下面的额外数值例子明确作为教学构造。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "013-impedance",
    "file": "013-impedance.md",
    "kind": "paper",
    "day": 13,
    "year": 1985,
    "title": "013｜阻抗控制：接触任务需要控制一种关系",
    "cardTitle": "阻抗控制：接触任务需要控制一种关系",
    "question": "控制",
    "excerpt": "阅读范围：全文 7 页，含因果性、广义等效网络和阻抗叠加论证。这里只讨论 Part I；实施与应用属于 Part II、III，不能把后两篇实验挪作本篇证据。下文质量—弹簧—阻尼公式与伪代码是教学特例，不是原论文通用形式的完整替代。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "014-potential-field",
    "file": "014-potential-field.md",
    "kind": "paper",
    "day": 14,
    "year": 1986,
    "title": "014｜人工势场：让障碍物直接参与动作生成",
    "cardTitle": "人工势场：让障碍物直接参与动作生成",
    "question": "规划",
    "excerpt": "阅读范围：已逐页视觉核对作者保存的九页期刊原稿（90–98 页），包括势函数、动态仿真、COSMOS 实机系统及距离计算附录。以下公式使用统一教学符号；局部避障不等于复杂环境的全局规划保证。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "015-subsumption",
    "file": "015-subsumption.md",
    "kind": "paper",
    "day": 15,
    "year": 1986,
    "title": "015｜包容架构：先让机器人活着，再增加本领",
    "cardTitle": "包容架构：先让机器人活着，再增加本领",
    "question": "系统",
    "excerpt": "版本与阅读范围：已阅读可检索的期刊原稿摘要、行为层结构、性能与结论段落，直接 PDF 获取超时。作者保存的 1985 AIM-864 技报是较早版本，其结尾明确说缺少实物演示；1986 期刊版第 V 节则包括实体机器人。下面据期刊版讨论性能，不把两个版本混为一份实验记录。",
    "eraId": "系统",
    "eraYears": "",
    "eraLabel": "系统"
  },
  {
    "slug": "016-damped-ik",
    "file": "016-damped-ik.md",
    "kind": "paper",
    "day": 16,
    "year": 1986,
    "title": "016｜奇异鲁棒逆解：允许一点偏差，换取可执行的关节运动",
    "cardTitle": "奇异鲁棒逆解：允许一点偏差，换取可执行的关节运动",
    "question": "几何",
    "excerpt": "阅读范围：已核对作者、版本、原始摘要及其关于 SR-inverse 的方法描述；出版全文未能取得。下文给出标准阻尼最小二乘的完整教学推导，用来解释奇异鲁棒逆的核心思想；原文权重、调度函数、具体公式编号与仿真图表未核实，不作为已经读过的细节呈现。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "017-uncertain-map",
    "file": "017-uncertain-map.md",
    "kind": "paper",
    "day": 17,
    "year": 1986,
    "title": "017｜空间不确定性：地图还要告诉机器人“有多不确定”",
    "cardTitle": "空间不确定性：地图还要告诉机器人“有多不确定”",
    "question": "估计",
    "excerpt": "阅读范围：读取完整可解析正文，包含第 3 节变换合成、第 4 节融合、第 5 节网络化简、第 6 节移动机器人例子与第 7 节讨论。采用期刊印刷页码定位；扫描末尾附录页与正文共同计入 PDF 页数。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "018-operational-space",
    "file": "018-operational-space.md",
    "kind": "paper",
    "day": 18,
    "year": 1987,
    "title": "018｜操作空间：直接设计夹爪的动力学行为",
    "cardTitle": "操作空间：直接设计夹爪的动力学行为",
    "question": "控制",
    "excerpt": "阅读范围：已逐页视觉核对作者保存的十一页原文（43–53 页），包括任务选择、非冗余与冗余动力学、动态一致分解、仿真和实机摘要。本文采用统一符号解释公式；作者报告的系统数值不等于具有重复统计的普遍性能界。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "019-adaptive-control",
    "file": "019-adaptive-control.md",
    "kind": "paper",
    "day": 19,
    "year": 1987,
    "title": "019｜Slotine–Li 自适应控制：一边跟踪，一边修正动力学参数",
    "cardTitle": "Slotine–Li 自适应控制：一边跟踪，一边修正动力学参数",
    "question": "控制",
    "excerpt": "阅读范围：已核对期刊原稿的公开文本副本，包括第 2–4 节、仿真说明与附录讨论；网页自身的机器摘要不作证据。原稿公式图片部分解析不完整，下文采用统一现代符号并独立核对推导。大量实体实验见作者另外的研究，不能归为本篇仿真成绩。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "020-tsai-calibration",
    "file": "020-tsai-calibration.md",
    "kind": "paper",
    "day": 20,
    "year": 1987,
    "title": "020｜Tsai 标定：先找不受畸变影响的约束",
    "cardTitle": "Tsai 标定：先找不受畸变影响的约束",
    "question": "视觉",
    "excerpt": "阅读范围：22 页原文，核对相机模型、径向对齐约束、单平面与多平面流程、误差定义、实验及附录位置。本文讲解核心两阶段思想，不逐式复刻全部参数恢复分支。1986 CVPR 前身与这篇 1987 期刊版区分引用。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "021-horn",
    "file": "021-horn.md",
    "kind": "paper",
    "day": 21,
    "year": 1987,
    "title": "021｜Horn 配准：把旋转最小二乘变成四维特征值问题",
    "cardTitle": "Horn 配准：把旋转最小二乘变成四维特征值问题",
    "question": "几何",
    "excerpt": "阅读范围：14 页全文，重点核查第 2 节平移与尺度、第 3 节四元数、第 4 节特征值解及附录 A3。下文先讲尺度固定的刚体配准，再单独解释原文的尺度对称性，避免把不同损失函数的尺度公式混用。",
    "eraId": "几何",
    "eraYears": "",
    "eraLabel": "几何"
  },
  {
    "slug": "022-gilbert-distance",
    "file": "022-gilbert-distance.md",
    "kind": "paper",
    "day": 22,
    "year": 1988,
    "title": "022｜GJK：不枚举所有表面，也能求物体距离",
    "cardTitle": "GJK：不枚举所有表面，也能求物体距离",
    "question": "规划",
    "excerpt": "阅读范围：扫描原稿 11 页，结合同版原稿转录核对第 II–VIII 节、数值实验与表 I。转录中损坏的容差指数不引用。伪代码描述距离版本核心流程，并非后来的简化布尔碰撞实现或 EPA 穿透深度算法。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "023-harris",
    "file": "023-harris.md",
    "kind": "paper",
    "day": 23,
    "year": 1988,
    "title": "023｜Harris：一个小矩阵，解释为什么角点适合跟踪",
    "cardTitle": "Harris：一个小矩阵，解释为什么角点适合跟踪",
    "question": "视觉",
    "excerpt": "阅读范围：六页原稿全文，重点核对自相关推导、响应函数和图 1–7。原文是一篇视觉前端论文，不是完整视觉里程计系统；下面的位移估计例子属于教学延伸。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "024-hand-eye",
    "file": "024-hand-eye.md",
    "kind": "paper",
    "day": 24,
    "year": 1989,
    "title": "024｜Tsai–Lenz 手眼标定：为什么换几个姿态，就能知道相机装在哪里",
    "cardTitle": "Tsai–Lenz 手眼标定：为什么换几个姿态，就能知道相机装在哪里",
    "question": "视觉",
    "excerpt": "阅读范围：14 页期刊原稿，第 II 节解法、第 III 节误差分析、第 IV 节仿真与实机结果。正文式 (12)–(15) 的扫描公式结合上下文核对。以下用统一的 $AX=XB$ 方向重新推导，符号不与原文逐字对应。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "025-occupancy",
    "file": "025-occupancy.md",
    "kind": "paper",
    "day": 25,
    "year": 1989,
    "title": "025｜Occupancy Grid：地图不只记录哪里有墙，还记录有多确定",
    "cardTitle": "Occupancy Grid：地图不只记录哪里有墙，还记录有多确定",
    "question": "估计",
    "excerpt": "阅读范围：期刊正文的占据概率、贝叶斯更新、多传感器实验和运动不确定性处理；扫描公式结合作者上传文本核对。原文是一篇框架性研究介绍，明确将更完整推导与部分实验细节指向其参考文献，不能把这些未展开内容视作已经详述的统一基准。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "026-vfh",
    "file": "026-vfh.md",
    "kind": "paper",
    "day": 26,
    "year": 1991,
    "title": "026｜VFH：别把障碍挤成一股力，先看看哪里有通道",
    "cardTitle": "VFH：别把障碍挤成一股力，先看看哪里有通道",
    "question": "导航",
    "excerpt": "阅读范围：作者上传的原文重排版，第 1–7 节，重点为第 4 节机制与第 6 节实机。重排页码与期刊不同，因此以章节、公式和图号定位。VFH、后来的 VFH+ 与 VFH 是不同版本，本文只讨论 1991 年版本。",
    "eraId": "导航",
    "eraYears": "",
    "eraLabel": "导航"
  },
  {
    "slug": "027-lipm",
    "file": "027-lipm.md",
    "kind": "paper",
    "day": 27,
    "year": 1991,
    "title": "027｜线性倒立摆：通过限制身体怎样动，让行走动力学变简单",
    "cardTitle": "线性倒立摆：通过限制身体怎样动，让行走动力学变简单",
    "question": "腿足",
    "excerpt": "阅读范围：1991 会议论文可访问摘要与书目信息，并以同作者、同年日文原始研究期刊摘要核对模型假设。会议版全文实验图表尚未取得，因此不提供未经核实的图号、步速或硬件结果。下文明确区分原文可确认主张与独立教学推导。这里讨论平面 LIPM 的奠基工作，不把 2001 年三维扩展或 2003 年 ZMP 预瞄控制归入 1991 年论文。",
    "eraId": "腿足",
    "eraYears": "",
    "eraLabel": "腿足"
  },
  {
    "slug": "028-icp",
    "file": "028-icp.md",
    "kind": "paper",
    "day": 28,
    "year": 1992,
    "title": "028｜ICP：不知道谁对应谁，也可以交替求解形状对齐",
    "cardTitle": "ICP：不知道谁对应谁，也可以交替求解形状对齐",
    "question": "视觉",
    "excerpt": "阅读范围：原稿可检索正文及同版扫描转录，核对引言、第 IV 节算法与单调性、第 V 节初始化及反例、第 VI-A 节点集实验。曲线与曲面部分核对到示例设定，未逐图复算所有数字。转录损坏的矩阵元素不引用。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "029-navigation-functions",
    "file": "029-navigation-functions.md",
    "kind": "paper",
    "day": 29,
    "year": 1992,
    "title": "029｜Navigation Functions：势场什么时候才能有到达保证",
    "cardTitle": "Navigation Functions：势场什么时候才能有到达保证",
    "question": "规划",
    "excerpt": "阅读范围：原稿摘要、势函数性质的可检索正文、球世界与坐标变换论述，以及第 511 页星形障碍树的结构条件。扫描版仿真图尚未完整取得，不编列未核实的成功率、耗时或图中参数。以下球世界公式与能量分析以教学推导说明，不替代原文全部几何证明。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "030-grasp-quality",
    "file": "030-grasp-quality.md",
    "kind": "paper",
    "day": 30,
    "year": 1992,
    "title": "030｜Ferrari–Canny：抓得住之后，怎样比较抓得好不好",
    "cardTitle": "Ferrari–Canny：抓得住之后，怎样比较抓得好不好",
    "question": "抓取",
    "excerpt": "阅读范围：六页全文，第 2 节接触假设、第 4 节两种质量定义、第 5 节平面两爪与三爪规划，以及结论。论文没有今天常见的千次实物抓取成功率实验，本文以几何论证和算法条件为主要证据。",
    "eraId": "抓取",
    "eraYears": "",
    "eraLabel": "抓取"
  },
  {
    "slug": "031-bootstrap-filter",
    "file": "031-bootstrap-filter.md",
    "kind": "paper",
    "day": 31,
    "year": 1993,
    "title": "031｜Bootstrap Filter：用一群可能状态，代替一个高斯椭球",
    "cardTitle": "Bootstrap Filter：用一群可能状态，代替一个高斯椭球",
    "question": "估计",
    "excerpt": "阅读范围：第 1–5 节完整文字、公式与图注，页码 107–113；部分公式经过文字识别，以下以统一符号重写。数值结论采用正文明确描述，不从模糊曲线读取额外精度。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "032-dstar",
    "file": "032-dstar.md",
    "kind": "paper",
    "day": 32,
    "year": 1994,
    "title": "032｜D*：地图变了，怎样修复已经算过的最短路",
    "cardTitle": "D*：地图变了，怎样修复已经算过的最短路",
    "question": "规划",
    "excerpt": "阅读范围：会议版八页全文，包括第 2 节算法、第 3 节非形式化证明、第 4 节表 1。下文页数按该 PDF 的 1–8 页计，便于对照无印刷页码的作者稿。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "033-good-features",
    "file": "033-good-features.md",
    "kind": "paper",
    "day": 33,
    "year": 1994,
    "title": "033｜Shi–Tomasi：好角点为什么仍然可能是坏特征",
    "cardTitle": "Shi–Tomasi：好角点为什么仍然可能是坏特征",
    "question": "视觉",
    "excerpt": "阅读范围：会议稿第 1–8 节、表 1 与图 1–15 的正文及图注。作者上传页面的外层日期不是论文发表年份。表中变形矩阵的文字识别较破碎，以下只采用可以明确辨认的平移数值，不复写不确定矩阵元素。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "034-force-closure",
    "file": "034-force-closure.md",
    "kind": "paper",
    "day": 34,
    "year": 1995,
    "title": "034｜Bicchi：接触位置相同，为什么一只手抓得稳，另一只不行",
    "cardTitle": "Bicchi：接触位置相同，为什么一只手抓得稳，另一只不行",
    "question": "抓取",
    "excerpt": "阅读范围：作者原稿共 25 页，已核对引言关于机械结构的反例、形式闭合的基本定义与自由运动锥算法、力闭合的可控内力表达、关键命题及三指手数值例子。没有逐行重验全部证明。下文页码采用作者稿页码，不等同于期刊排版页码；本文不把解析示例写成实机成功率实验。",
    "eraId": "抓取",
    "eraYears": "",
    "eraLabel": "抓取"
  },
  {
    "slug": "035-prm",
    "file": "035-prm.md",
    "kind": "paper",
    "day": 35,
    "year": 1996,
    "title": "035｜PRM：先把自由空间修成路网，再回答运动查询",
    "cardTitle": "PRM：先把自由空间修成路网，再回答运动查询",
    "question": "规划",
    "excerpt": "阅读范围：核对期刊版的问题定义、道路图构建与扩展算法、局部规划器讨论、平面机械臂实验设置，以及通用规划器的结果和结论。以下页码使用期刊版；作者网站另有排版不同的长稿。本文没有重新运行碰撞检测或规划实验。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "036-impulse-contact",
    "file": "036-impulse-contact.md",
    "kind": "paper",
    "day": 36,
    "year": 1996,
    "title": "036｜Stewart–Trinkle：不要追逐无限大的接触力，直接计算冲量",
    "cardTitle": "Stewart–Trinkle：不要追逐无限大的接触力，直接计算冲量",
    "question": "接触",
    "excerpt": "阅读范围：核对作者 21 页原稿的接触建模、离散互补方程、摩擦锥近似、非线性几何修正、旋转杆与四球数值实验。以下页码对应作者稿，不对应期刊页码。一般情形的全部存在性证明没有逐行重验；不混入作者 2000 年题名相近的 ICRA 论文。",
    "eraId": "接触",
    "eraYears": "",
    "eraLabel": "接触"
  },
  {
    "slug": "037-visual-servo",
    "file": "037-visual-servo.md",
    "kind": "paper",
    "day": 37,
    "year": 1996,
    "title": "037｜视觉伺服：机器人究竟应该追三维位置，还是追图像误差",
    "cardTitle": "视觉伺服：机器人究竟应该追三维位置，还是追图像误差",
    "question": "控制",
    "excerpt": "阅读范围：核对控制系统分类、位置式与图像式视觉伺服、图像雅可比推导和伪逆、点定位例子、跟踪方法及讨论。下面页码均为期刊版。这是一篇教程与方法综述，其应用例子不少来自所引文献；本文不把这些例子合并为作者实施的一套新基准实验。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "038-dwa",
    "file": "038-dwa.md",
    "kind": "paper",
    "day": 38,
    "year": 1997,
    "title": "038｜DWA：先问刹不刹得住，再问走哪条路最快",
    "cardTitle": "DWA：先问刹不刹得住，再问走哪条路最快",
    "question": "导航",
    "excerpt": "阅读范围：已核对 23 页作者稿的运动近似、速度空间筛选、目标函数、RHINO 实现与实验讨论。以下图号和页码采用该稿，与期刊 11 页排版不同；1996 年相关会议文不与本文混用。本文没有运行机器人复现实验。",
    "eraId": "导航",
    "eraYears": "",
    "eraLabel": "导航"
  },
  {
    "slug": "039-isard-condensation",
    "file": "039-isard-condensation.md",
    "kind": "paper",
    "day": 39,
    "year": 1998,
    "title": "039｜CONDENSATION：暂时保留错误答案，反而能避免彻底跟丢",
    "cardTitle": "CONDENSATION：暂时保留错误答案，反而能避免彻底跟丢",
    "question": "估计",
    "excerpt": "阅读范围：核对期刊正文的贝叶斯传播、采样流程、轮廓观测模型、四类视频实验与结论；附录证明没有逐行重验。页码采用 5–28 的期刊页码。原始视频未逐帧播放，也未重新运行跟踪器。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "040-rrt",
    "file": "040-rrt.md",
    "kind": "paper",
    "day": 40,
    "year": 1998,
    "title": "040｜RRT：让树朝还没探索过的地方生长",
    "cardTitle": "RRT：让树朝还没探索过的地方生长",
    "question": "规划",
    "excerpt": "阅读范围：核对四页报告的定义、生成算法、Voronoi 解释、性质讨论和算例。原文不少结论属于初步观察或研究方向，没有完整现代基准与全部性质的形式证明。下文用页码定位无编号插图，不为其补造图号。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "041-mcl",
    "file": "041-mcl.md",
    "kind": "paper",
    "day": 41,
    "year": 1999,
    "title": "041｜Monte Carlo Localization：让位置假设跟着证据聚拢",
    "cardTitle": "Monte Carlo Localization：让位置假设跟着证据聚拢",
    "question": "估计",
    "excerpt": "阅读范围：已核对七页原稿的完整正文、采样推导、全局定位、参考点精度实验和博物馆日志实验。页码按原稿 PDF 计数。图中没有文字给出的精确曲线数值不作猜测，实验日志未重放。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "042-zhang-calibration",
    "file": "042-zhang-calibration.md",
    "kind": "paper",
    "day": 42,
    "year": 2000,
    "title": "042｜张正友标定：一块平板怎样提供三维相机的信息",
    "cardTitle": "张正友标定：一块平板怎样提供三维相机的信息",
    "question": "视觉",
    "excerpt": "阅读范围：已核对期刊五页正文、公式、附录和 Table 1；表格通过原页视觉核对。下文采用期刊页码，不把长技术报告中的模拟参数或五图实验结果作为期刊同一张表的数据。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "043-rrt-connect",
    "file": "043-rrt-connect.md",
    "kind": "paper",
    "day": 43,
    "year": 2000,
    "title": "043｜RRT-Connect：让两棵搜索树主动相遇",
    "cardTitle": "RRT-Connect：让两棵搜索树主动相遇",
    "question": "规划",
    "excerpt": "阅读范围：已核对全文算法、理论论述、实验与结论。原文的证明为证明梗概；以下说明其前提与结论，不把有限实验扩大为任意场景的运行时间保证。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "044-slam-convergence",
    "file": "044-slam-convergence.md",
    "kind": "paper",
    "day": 44,
    "year": 2001,
    "title": "044｜SLAM 的收敛结构：地图为什么能越走越确定",
    "cardTitle": "SLAM 的收敛结构：地图为什么能越走越确定",
    "question": "SLAM",
    "excerpt": "阅读范围：已核对十三页原文的理论正文、实验描述、图注及两个附录；部分公式在文本抽取中缺失，以下公式用统一符号重写基本滤波与协方差关系，不逐字转录缺失表达式。图中的连续曲线不估读为精确数值。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "045-fastslam",
    "file": "045-fastslam.md",
    "kind": "paper",
    "day": 45,
    "year": 2002,
    "title": "045｜FastSLAM：不删除相关性，而是把它放进轨迹假设",
    "cardTitle": "FastSLAM：不删除相关性，而是把它放进轨迹假设",
    "question": "SLAM",
    "excerpt": "阅读范围：已核对六页会议正文、因子分解、重要性权重、树结构与实验图注。本文讨论原始 FastSLAM，不把后来使用观测改进提议分布的 FastSLAM 2.0 混作同一算法。连续实验曲线仅作趋势解释，不估读未明确给出的数值。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "046-dstar-lite",
    "file": "046-dstar-lite.md",
    "kind": "paper",
    "day": 46,
    "year": 2002,
    "title": "046｜D* Lite：地图变了，只修复受到影响的搜索结果",
    "cardTitle": "D* Lite：地图变了，只修复受到影响的搜索结果",
    "question": "规划",
    "excerpt": "阅读范围：已核对会议全文算法、定理陈述和实验，以及作者正式列出的优化版伪代码勘误。完整定理证明在另行引用的技术报告中，本文未将会议中的陈述当成已经独立重做全部证明。后来的期刊扩展实验不混入这篇会议文的结果。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "047-preview-zmp",
    "file": "047-preview-zmp.md",
    "kind": "paper",
    "day": 47,
    "year": 2003,
    "title": "047｜ZMP 预瞄控制：下一步还没落地，身体就要开始准备",
    "cardTitle": "ZMP 预瞄控制：下一步还没落地，身体就要开始准备",
    "question": "腿足",
    "excerpt": "阅读范围：已核对七页原文的模型、控制器、图注、数值与结论。本文是 ZMP 预瞄步态生成，不是后来 capture point 的专门论文。原文中 HRP-2P 的楼梯行走是动力学仿真，不能称为已验证的实机楼梯实验。",
    "eraId": "腿足",
    "eraYears": "",
    "eraLabel": "腿足"
  },
  {
    "slug": "048-sift",
    "file": "048-sift.md",
    "kind": "paper",
    "day": 48,
    "year": 2004,
    "title": "048｜SIFT：先统一局部坐标，再比较纹理",
    "cardTitle": "SIFT：先统一局部坐标，再比较纹理",
    "question": "视觉",
    "excerpt": "阅读范围：已核对原文方法主体、参数实验、识别流程与应用图注。原文引用的其他论文实验仅作为相关工作背景，不当成 Lowe 自己完成的本篇结果。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "049-five-point",
    "file": "049-five-point.md",
    "kind": "paper",
    "day": 49,
    "year": 2004,
    "title": "049｜五点法：用相机标定，把两帧匹配变成运动假设",
    "cardTitle": "五点法：用相机标定，把两帧匹配变成运动假设",
    "question": "视觉",
    "excerpt": "阅读范围：已核对期刊正文的问题定义、消元步骤、RANSAC 接口、数值及噪声实验、系统结果，并查阅附录的求根与三角化说明。这里的伪代码解释计算组织，不替代完整多项式系数实现；图中连续曲线只作方向性解读，不从低清曲线猜测精确数值。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "050-task-priority",
    "file": "050-task-priority.md",
    "kind": "paper",
    "day": 50,
    "year": 2005,
    "title": "050｜全身任务层级：够不到目标时，先决定什么不能牺牲",
    "cardTitle": "全身任务层级：够不到目标时，先决定什么不能牺牲",
    "question": "控制",
    "excerpt": "阅读范围：已核对十四页期刊版的动力学定义、层级投影、递归证明、可行性分析和关节限位仿真。正文的主要定量验证是模拟人形机器人的同一任务对照，不是大规模实机安全测试。公式采用维度明确的统一符号重写。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "051-id-iLQR",
    "file": "051-id-iLQR.md",
    "kind": "paper",
    "day": 51,
    "year": 2005,
    "title": "051｜迭代 LQG：优化一条轨迹，也优化偏离轨迹后的修正",
    "cardTitle": "迭代 LQG：优化一条轨迹，也优化偏离轨迹后的修正",
    "question": "轨迹",
    "excerpt": "阅读范围：已核对七页原稿的局部近似、值函数递推、控制约束、主迭代、两类数值问题和讨论。以下定位使用章节及图号。作者在讨论中明确承认随机问题的近似不具有确定性情形同等的最优性保证。",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "052-anytime-dstar",
    "file": "052-anytime-dstar.md",
    "kind": "paper",
    "day": 52,
    "year": 2005,
    "title": "052｜AD*：先给有质量界的路线，再随时间和地图一起改进",
    "cardTitle": "AD*：先给有质量界的路线，再随时间和地图一起改进",
    "question": "规划",
    "excerpt": "阅读范围：已核对十页会议原文的算法、性质、应用、实验和讨论；证明技报核对了假设、伪代码及版本差异，没有逐行重做全部引理。以下采用会议稿的反向搜索和 $g,rhs$ 记号，技报另有前向搜索及变量改名。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "053-graphslam",
    "file": "053-graphslam.md",
    "kind": "paper",
    "day": 53,
    "year": 2006,
    "title": "053｜GraphSLAM：让整段历史一起解释地图",
    "cardTitle": "GraphSLAM：让整段历史一起解释地图",
    "question": "SLAM",
    "excerpt": "阅读范围：已读取作者提供的期刊全文解析文本，核对图表示、信息矩阵、线性化和消元、数据关联、城市地图实验与局限。本文用标准分块线性系统重写核心公式。表 8、表 9 的解析文本存在符号疑点，尚未完成对应页面的视觉核对，因此下面区分可独立推导的数学关系与仍待确认的原文排版。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "054-capture-point",
    "file": "054-capture-point.md",
    "kind": "paper",
    "day": 54,
    "year": 2006,
    "title": "054｜Capture Point：被推之后，脚要落在哪里才能停下来",
    "cardTitle": "Capture Point：被推之后，脚要落在哪里才能停下来",
    "question": "腿足",
    "excerpt": "阅读范围：已核对作者上传的论文全文及八页原稿镜像，包括捕获定义、带飞轮模型、力矩与角度限制、摩擦条件、参数分析和仿真。镜像保存的是原稿内容，不使用托管平台生成的摘要作为证据。真实三维人形机器人验证在本文属于后续工作。",
    "eraId": "腿足",
    "eraYears": "",
    "eraLabel": "腿足"
  },
  {
    "slug": "055-gmap",
    "file": "055-gmap.md",
    "kind": "paper",
    "day": 55,
    "year": 2007,
    "title": "055｜GMapping：让粒子在有证据的地方采样",
    "cardTitle": "GMapping：让粒子在有证据的地方采样",
    "question": "SLAM",
    "excerpt": "论文：Giorgio Grisetti、Cyrill Stachniss、Wolfram Burgard，Improved Techniques for Grid Mapping With Rao-Blackwellized Particle Filters，IEEE Transactions on Robotics，23(1)，34–46，2007。作者实",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "056-ptam",
    "file": "056-ptam.md",
    "kind": "paper",
    "day": 56,
    "year": 2007,
    "title": "056｜PTAM：跟踪要及时，建图可以慢慢想",
    "cardTitle": "PTAM：跟踪要及时，建图可以慢慢想",
    "question": "SLAM",
    "excerpt": "论文：Georg Klein、David Murray，Parallel Tracking and Mapping for Small AR Workspaces，ISMAR 2007，225–234。牛津大学作者全文；官方代码说明。以下依据十页原稿正文、图表与局限部分；代码说明仅用于核对版本差异，没有将后续实现的改进归入 2007 年论文。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "057-isam",
    "file": "057-isam.md",
    "kind": "paper",
    "day": 57,
    "year": 2008,
    "title": "057｜iSAM：保留历史，也能增量求解",
    "cardTitle": "iSAM：保留历史，也能增量求解",
    "question": "SLAM",
    "excerpt": "论文：Michael Kaess、Ananth Ranganathan、Frank Dellaert，iSAM: Incremental Smoothing and Mapping，IEEE Transactions on Robotics 24(6)，1365–1378，2008。作者全文；出版记录。以下依据作者保存的 2008 年 9 月 7 日十四页录",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "058-ros",
    "file": "058-ros.md",
    "kind": "paper",
    "day": 58,
    "year": 2009,
    "title": "058｜ROS：让机器人算法能组成系统",
    "cardTitle": "ROS：让机器人算法能组成系统",
    "question": "系统",
    "excerpt": "论文：Morgan Quigley 等，ROS: an open-source Robot Operating System，ICRA Open-Source Software Workshop，2009。第一作者保存的六页全文；作者发表列表。以下阅读范围为原论文全文。这是早期 ROS 的架构文章，既不是 ROS 2 设计论文，也不是某个当前发行版的安装说明",
    "eraId": "系统",
    "eraYears": "",
    "eraLabel": "系统"
  },
  {
    "slug": "059-chomp",
    "file": "059-chomp.md",
    "kind": "paper",
    "day": 59,
    "year": 2009,
    "title": "059｜CHOMP：让整条轨迹一起绕开障碍",
    "cardTitle": "CHOMP：让整条轨迹一起绕开障碍",
    "question": "轨迹",
    "excerpt": "论文：Nathan Ratliff、Matt Zucker、J. Andrew Bagnell、Siddhartha Srinivasa，CHOMP: Gradient Optimization Techniques for Efficient Motion Planning，ICRA 2009，489–494。作者实验室预印稿；CMU 发表记录。以下依据八",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "060-orb",
    "file": "060-orb.md",
    "kind": "paper",
    "day": 60,
    "year": 2011,
    "title": "060｜ORB：让二进制特征既快又有区分力",
    "cardTitle": "ORB：让二进制特征既快又有区分力",
    "question": "视觉",
    "excerpt": "论文：Ethan Rublee、Vincent Rabaud、Kurt Konolige、Gary Bradski，ORB: An Efficient Alternative to SIFT or SURF，ICCV 2011，2564–2571。出版记录；IPOL 保存的作者原稿全文。以下依据八页原稿全文；不是对 ORB-SLAM 的解读。另用 OpenC",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "061-stomp",
    "file": "061-stomp.md",
    "kind": "paper",
    "day": 61,
    "year": 2011,
    "title": "061｜STOMP：用平滑随机试探优化机器人轨迹",
    "cardTitle": "STOMP：用平滑随机试探优化机器人轨迹",
    "question": "轨迹",
    "excerpt": "阅读范围：六页正文，包含算法表 I、实验表 II 和图 1—5。未运行历史 ROS 实现，未检查随附视频的每次执行。下面的推导补充和数值小例子是教学说明，不是新的复现实验。",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "062-rrtstar",
    "file": "062-rrtstar.md",
    "kind": "paper",
    "day": 62,
    "year": 2011,
    "title": "062｜RRT*：让随机树在找到路径后继续变好",
    "cardTitle": "RRT*：让随机树在找到路径后继续变好",
    "question": "规划",
    "excerpt": "阅读范围：问题定义、PRM／RRG／RRT 算法、主定理陈述、复杂度分析和数值实验；附录长证明未逐行复算。另核对 Solovey 等人的后续论文摘要及正式出版记录，用于注明原 RRT 证明的后续修订，未将后续结论冒充 2011 年原文内容。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "063-g2o",
    "file": "063-g2o.md",
    "kind": "paper",
    "day": 63,
    "year": 2011,
    "title": "063｜g2o：把不同估计问题放进同一个稀疏优化框架",
    "cardTitle": "g2o：把不同估计问题放进同一个稀疏优化框架",
    "question": "SLAM",
    "excerpt": "阅读范围：七页正式论文，第 3607—3613 页，包含方法、三张表及实验图；官方仓库只用于核对项目入口，没有把当前软件新增功能算作 2011 年贡献。未编译实现，未重跑基准。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "064-kinfu",
    "file": "064-kinfu.md",
    "kind": "paper",
    "day": 64,
    "year": 2011,
    "title": "064｜KinectFusion：让三维地图反过来帮助相机定位",
    "cardTitle": "KinectFusion：让三维地图反过来帮助相机定位",
    "question": "SLAM",
    "excerpt": "阅读范围：本篇讨论 ISMAR 的跟踪与建图论文，阅读方法 §3、实验 §4、失败模式和结论；不把同年 UIST 交互论文或后续重定位系统合并为这一篇的贡献。未运行软件，未把演示图当作独立的大规模基准。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "065-min-snap",
    "file": "065-min-snap.md",
    "kind": "paper",
    "day": 65,
    "year": 2011,
    "title": "065｜Minimum Snap：把四旋翼轨迹变成可求解的平滑曲线",
    "cardTitle": "Minimum Snap：把四旋翼轨迹变成可求解的平滑曲线",
    "question": "轨迹",
    "excerpt": "阅读范围：原文 §I—VII 的完整文本与图注；未从存档中恢复所有图像像素，因此不估读曲线数值。关键飞行数字来自实验正文，公式采用可确认的表达及明确标注的教学推导。未复现飞行，不把作者 2012 年博士论文的新增实验计入本文。",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "066-dbow",
    "file": "066-dbow.md",
    "kind": "paper",
    "day": 66,
    "year": 2012,
    "title": "066｜DBoW：怎样从相似图片中找出真正的重访地点",
    "cardTitle": "DBoW：怎样从相似图片中找出真正的重访地点",
    "question": "视觉",
    "excerpt": "阅读范围：九页预印本全文、图注及表 I—VI；没有重新运行程序。以下将作者实验、方法解释和教学推断分别说明。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "067-ompl",
    "file": "067-ompl.md",
    "kind": "paper",
    "day": 67,
    "year": 2012,
    "title": "067｜OMPL：怎样让不同运动规划算法使用同一套问题接口",
    "cardTitle": "OMPL：怎样让不同运动规划算法使用同一套问题接口",
    "question": "系统",
    "excerpt": "想比较RRT与PRM，通常要先写状态表示、距离计算、采样、碰撞检查和实验脚本。若两份代码连最近邻结构与碰撞检测精度都不同，测出的“算法优势”可能只是底层实现差异。将算法移到另一台机器人，又可能重写一遍基础设施。",
    "eraId": "系统",
    "eraYears": "",
    "eraLabel": "系统"
  },
  {
    "slug": "068-isam2",
    "file": "068-isam2.md",
    "kind": "paper",
    "day": 68,
    "year": 2012,
    "title": "068｜iSAM2：把不断增长的SLAM问题变成局部树更新",
    "cardTitle": "iSAM2：把不断增长的SLAM问题变成局部树更新",
    "question": "SLAM",
    "excerpt": "机器人每走一步，就多一个位姿和若干测量。最准确的做法之一是保留历史位姿与地图，把所有约束联合优化；但每一步从头求解全部历史，计算会越来越重。原版iSAM可以增量更新矩阵，却仍需要周期性的重排序和重新线性化。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "069-tum-rgbd",
    "file": "069-tum-rgbd.md",
    "kind": "paper",
    "day": 69,
    "year": 2012,
    "title": "069｜TUM RGB-D基准：把“地图看起来不错”变成可检验的轨迹误差",
    "cardTitle": "TUM RGB-D基准：把“地图看起来不错”变成可检验的轨迹误差",
    "question": "基准",
    "excerpt": "两个SLAM系统各自展示一幅漂亮点云，究竟谁更准确？如果输入不同、相机没有统一标定、真值时间戳没对齐，视觉效果甚至误差数字都可能无法比较。",
    "eraId": "基准",
    "eraYears": "",
    "eraLabel": "基准"
  },
  {
    "slug": "070-kitti",
    "file": "070-kitti.md",
    "kind": "paper",
    "day": 70,
    "year": 2012,
    "title": "070｜KITTI：把视觉算法放到真正行驶的街道上检验",
    "cardTitle": "KITTI：把视觉算法放到真正行驶的街道上检验",
    "question": "基准",
    "excerpt": "实验室中表现很好的立体匹配、光流与定位算法，到了高速移动、弱纹理道路、反光车身和遮挡场景，还可靠吗？KITTI没有提出一个包办自动驾驶的新算法，而是把这个问题变成公开数据上的统一实验。",
    "eraId": "基准",
    "eraYears": "",
    "eraLabel": "基准"
  },
  {
    "slug": "071-mujoco",
    "file": "071-mujoco.md",
    "kind": "paper",
    "day": 71,
    "year": 2012,
    "title": "071｜MuJoCo：让物理仿真成为控制优化的内循环",
    "cardTitle": "MuJoCo：让物理仿真成为控制优化的内循环",
    "question": "系统",
    "excerpt": "论文：Emanuel Todorov、Tom Erez、Yuval Tassa，MuJoCo: A Physics Engine for Model-Based Control，IROS 2012。原始书目链接；作者迁移后的全文。阅读范围为原文八页的算法、建模与计时实验；以下讨论 2012 年版本，不把后来的功能倒写成初版贡献。未独立重跑计时实验。",
    "eraId": "系统",
    "eraYears": "",
    "eraLabel": "系统"
  },
  {
    "slug": "072-contact-implicit",
    "file": "072-contact-implicit.md",
    "kind": "paper",
    "day": 72,
    "year": 2012,
    "title": "072｜手部 CIO：把何时接触、在哪里施力一起优化",
    "cardTitle": "手部 CIO：把何时接触、在哪里施力一起优化",
    "question": "接触",
    "excerpt": "论文：Igor Mordatch、Zoran Popović、Emanuel Todorov，Contact-Invariant Optimization for Hand Manipulation，SCA 2012。原始书目链接；作者存档全文。本文依据八页正文的方法、实验和讨论，不与同年 SIGGRAPH 的全身 CIO 论文混同；未独立复现动画优化。",
    "eraId": "接触",
    "eraYears": "",
    "eraLabel": "接触"
  },
  {
    "slug": "073-trajopt",
    "file": "073-trajopt.md",
    "kind": "paper",
    "day": 73,
    "year": 2013,
    "title": "073｜TrajOpt：用局部凸问题修复整条碰撞轨迹",
    "cardTitle": "TrajOpt：用局部凸问题修复整条碰撞轨迹",
    "question": "轨迹",
    "excerpt": "论文：John Schulman、Jonathan Ho、Alex Lee、Ibrahim Awwal、Henry Bradlow、Pieter Abbeel，Finding Locally Optimal, Collision-Free Trajectories with Sequential Convex Optimization，RSS 2013。正式",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "074-octomap",
    "file": "074-octomap.md",
    "kind": "paper",
    "day": 74,
    "year": 2013,
    "title": "074｜OctoMap：同时记住障碍、自由空间与尚未看见的地方",
    "cardTitle": "OctoMap：同时记住障碍、自由空间与尚未看见的地方",
    "question": "SLAM",
    "excerpt": "论文：Armin Hornung、Kai M. Wurm、Maren Bennewitz、Cyrill Stachniss、Wolfram Burgard，OctoMap: An Efficient Probabilistic 3D Mapping Framework Based on Octrees，Autonomous Robots 2013。正式论文；",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "075-contact-trajopt",
    "file": "075-contact-trajopt.md",
    "kind": "paper",
    "day": 75,
    "year": 2014,
    "title": "075｜接触隐式轨迹优化：不先规定哪只脚何时落地",
    "cardTitle": "接触隐式轨迹优化：不先规定哪只脚何时落地",
    "question": "接触",
    "excerpt": "阅读范围：22 页作者预印本的方法、四组应用、讨论及图注，并核对勘误关于先行工作的说明。页码按作者版，章节便于与期刊版对应。没有复现优化、仿真或硬件运行，以下高速运动数字均不作为真机纪录。",
    "eraId": "接触",
    "eraYears": "",
    "eraLabel": "接触"
  },
  {
    "slug": "076-lsdslam",
    "file": "076-lsdslam.md",
    "kind": "paper",
    "day": 76,
    "year": 2014,
    "title": "076｜LSD-SLAM：让单目直接法拥有能闭环的全局地图",
    "cardTitle": "LSD-SLAM：让单目直接法拥有能闭环的全局地图",
    "question": "SLAM",
    "excerpt": "原始论文 · 作者项目页 · 官方代码",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "077-loam",
    "file": "077-loam.md",
    "kind": "paper",
    "day": 77,
    "year": 2014,
    "title": "077｜LOAM：用两种速度处理同一片点云",
    "cardTitle": "LOAM：用两种速度处理同一片点云",
    "question": "SLAM",
    "excerpt": "阅读范围：核对九页原稿的传感器、特征提取、运动补偿、两级配准、实验及结论。下文页码按 PDF 页序；论文中的 KITTI 排名是发表时的历史记录。本文不把后来的 A-LOAM、LeGO-LOAM 或加入回环的实现混作原算法。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "078-svo",
    "file": "078-svo.md",
    "kind": "paper",
    "day": 78,
    "year": 2014,
    "title": "078｜SVO：先用亮度找运动，再让特征做精修",
    "cardTitle": "SVO：先用亮度找运动，再让特征做精修",
    "question": "SLAM",
    "excerpt": "阅读范围：核对原稿的系统、运动估计、深度滤波、参数与实验。页码按 PDF 页序。2017 年多相机版本及后来的 SVO Pro 是后续工作；其 IMU 先验、回环与当前速度数据不能归入本篇。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "079-informed-rrtstar",
    "file": "079-informed-rrtstar.md",
    "kind": "paper",
    "day": 79,
    "year": 2014,
    "title": "079｜Informed RRT*：已有一条路之后，还值得搜索哪里",
    "cardTitle": "Informed RRT*：已有一条路之后，还值得搜索哪里",
    "question": "规划",
    "excerpt": "阅读范围：八页会议论文正文、算法 1—2、理论陈述及实验图注。本文不将后来扩展论文或 BIT 的机器人实验计入本篇，未复现采样规划实验。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "080-wholebody-qp",
    "file": "080-wholebody-qp.md",
    "kind": "paper",
    "day": 80,
    "year": 2014,
    "title": "080｜质心动力学与全身运动学：怎样少算方程而不丢掉身体",
    "cardTitle": "质心动力学与全身运动学：怎样少算方程而不丢掉身体",
    "question": "控制",
    "excerpt": "阅读范围：八页作者版本正文、公式、图注及结论。未运行 Drake 仿真或真机实验。本文是非线性轨迹优化论文，不能仅因求解器内部使用二次子问题，就把整套算法称为一个凸 QP。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "081-bitstar",
    "file": "081-bitstar.md",
    "kind": "paper",
    "day": 81,
    "year": 2014,
    "title": "081｜BIT*：让随机采样按照值得尝试的顺序进行搜索",
    "cardTitle": "BIT*：让随机采样按照值得尝试的顺序进行搜索",
    "question": "规划",
    "excerpt": "阅读范围：阅读正文、算法 1–3、定理 1及实验说明；未独立复证所引用的全部随机几何图理论，未运行规划器。官方接口作为实现入口，不将其后续改动视为原论文实验配置。",
    "eraId": "规划",
    "eraYears": "",
    "eraLabel": "规划"
  },
  {
    "slug": "082-orbslam",
    "file": "082-orbslam.md",
    "kind": "paper",
    "day": 82,
    "year": 2015,
    "title": "082｜ORB-SLAM：从持续跟踪走向能够重访和恢复的单目地图",
    "cardTitle": "ORB-SLAM：从持续跟踪走向能够重访和恢复的单目地图",
    "question": "SLAM",
    "excerpt": "阅读范围：核对正文系统设计、初始化、跟踪/建图/回环及实验，阅读附录的优化目标；未运行程序，未复算全部表格。后文简化推导与例子用于教学，不将 ORB-SLAM2/3 的能力移入第一代。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "083-imu-preintegration",
    "file": "083-imu-preintegration.md",
    "kind": "paper",
    "day": 83,
    "year": 2015,
    "title": "083｜IMU 预积分：把高频惯性测量压缩成可以反复优化的约束",
    "cardTitle": "IMU 预积分：把高频惯性测量压缩成可以反复优化的约束",
    "question": "估计",
    "excerpt": "阅读范围：RSS 2015 正文的方法、实现和实验部分；未逐项复算补充材料的雅可比。本文不将后来期刊扩展版的实验归入会议论文。数值依据第 VIII 节；其中室外轨迹的图注与正文存在不一致，见下文。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "084-elasticfusion",
    "file": "084-elasticfusion.md",
    "kind": "paper",
    "day": 84,
    "year": 2015,
    "title": "084｜ElasticFusion：直接修正稠密地图，而不只修正相机轨迹",
    "cardTitle": "ElasticFusion：直接修正稠密地图，而不只修正相机轨迹",
    "question": "SLAM",
    "excerpt": "阅读范围：会议正文第 II–VII 节、算法 1、表 I–IV 和图 2–6；代码入口用于确认实现来源，未运行程序。本文讨论原始 RGB-D 系统，不把后续动态场景重建方法的能力归入本论文。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "085-dso",
    "file": "085-dso.md",
    "kind": "paper",
    "day": 85,
    "year": 2016,
    "title": "085｜DSO：用少量像素联合优化，而不是用尽所有像素",
    "cardTitle": "DSO：用少量像素联合优化，而不是用尽所有像素",
    "question": "SLAM",
    "excerpt": "阅读范围：2016 年 10 月 v2 的模型、前端、实验与参数研究，重点对应第 2–4 节。代码未运行，图中的连续曲线未进行数值反演；下面不编造曲线上的精确成功率。后来的双目、惯性或回环扩展不属于原始 DSO。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "086-euRoC",
    "file": "086-euRoC.md",
    "kind": "paper",
    "day": 86,
    "year": 2016,
    "title": "086｜EuRoC：一张定位成绩表背后，真值是怎样产生的",
    "cardTitle": "EuRoC：一张定位成绩表背后，真值是怎样产生的",
    "question": "基准",
    "excerpt": "阅读范围：2016 年 1 月 29 日作者公开稿全文，含传感器、数据格式、标定、同步和已知问题；辅以 ETH 官方数据页。下文页码与章节对应九页作者稿，期刊排版页码不同。没有下载全部原始数据或运行定位算法；当前仓储的入库日期不作为论文首次发表日期。",
    "eraId": "基准",
    "eraYears": "",
    "eraLabel": "基准"
  },
  {
    "slug": "087-gpmp2",
    "file": "087-gpmp2.md",
    "kind": "paper",
    "day": 87,
    "year": 2016,
    "title": "087｜GPMP2：把轨迹规划写成因子图推断",
    "cardTitle": "GPMP2：把轨迹规划写成因子图推断",
    "question": "轨迹",
    "excerpt": "阅读范围：会议正文第 II–VI 节、算法 1、表 I–II、实现和局限；未执行代码或机器人实验。下文将 GPMP2 与增量版 iGPMP2 分开，也不把概率建模解释为经过校准的实际碰撞概率。",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "088-colmap",
    "file": "088-colmap.md",
    "kind": "paper",
    "day": 88,
    "year": 2016,
    "title": "088｜COLMAP 的 SfM 基础：重建质量取决于整条链，而不只取决于 BA",
    "cardTitle": "COLMAP 的 SfM 基础：重建质量取决于整条链，而不只取决于 BA",
    "question": "视觉",
    "excerpt": "阅读范围：原文增量 SfM 方法、第 4 节各模块与第 5 节实验、表 1–2。未执行当前版本软件。COLMAP 今天同时提供 SfM 与 MVS，但本文研究的是这篇论文的稀疏重建；不能把后来稠密立体或其他插件能力全部归给本篇。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "089-orbslam2",
    "file": "089-orbslam2.md",
    "kind": "paper",
    "day": 89,
    "year": 2016,
    "title": "089｜ORB-SLAM2：把单目、双目和深度观测接入同一套 SLAM 后端",
    "cardTitle": "ORB-SLAM2：把单目、双目和深度观测接入同一套 SLAM 后端",
    "question": "SLAM",
    "excerpt": "阅读范围：2017 年 6 月 v2 全部方法与实验、表 I–IV；未运行软件。本文不把 ORB-SLAM3 的视觉惯性、鱼眼和多地图能力归入第二代系统。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "090-se-sync",
    "file": "090-se-sync.md",
    "kind": "paper",
    "day": 90,
    "year": 2016,
    "title": "090｜SE-Sync：不仅求一张地图，还证明目标值已经不能更低",
    "cardTitle": "SE-Sync：不仅求一张地图，还证明目标值已经不能更低",
    "question": "估计",
    "excerpt": "阅读范围：2017 年 2 月扩展稿的建模、松弛、算法、实验与定理陈述；附录 B、C 的长证明未逐行复算。下面区分原问题、半正定松弛和低秩数值求解，未运行实现，也不把数值容差下的证书当作任意精度的符号证明。",
    "eraId": "估计",
    "eraYears": "",
    "eraLabel": "估计"
  },
  {
    "slug": "091-cbfqp",
    "file": "091-cbfqp.md",
    "kind": "paper",
    "day": 91,
    "year": 2016,
    "title": "091｜CBF-QP：把安全边界写进控制器",
    "cardTitle": "CBF-QP：把安全边界写进控制器",
    "question": "控制",
    "excerpt": "阅读范围：核对正文的两类屏障函数、CLF-CBF 二次规划、正则性条件、车辆应用与仿真。证明按论证结构阅读，未独立复证全部引理。本文自己的推导与例子均作说明，不是运行结果。",
    "eraId": "控制",
    "eraYears": "",
    "eraLabel": "控制"
  },
  {
    "slug": "092-vinsmono",
    "file": "092-vinsmono.md",
    "kind": "paper",
    "day": 92,
    "year": 2017,
    "title": "092｜VINS-Mono：让单目视觉与 IMU 组成可以长期运行的定位系统",
    "cardTitle": "VINS-Mono：让单目视觉与 IMU 组成可以长期运行的定位系统",
    "question": "SLAM",
    "excerpt": "阅读范围：核对正文的方法、系统流程、实验与官方项目说明，并对 PDF 第 7 页式 23 做视觉复核；未执行官方程序，未逐项复算 IMU 雅可比。后文小例子与简化公式用于教学。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "093-toppra",
    "file": "093-toppra.md",
    "kind": "paper",
    "day": 93,
    "year": 2017,
    "title": "093｜TOPP-RA：先算哪里还能刹住，再决定哪里可以加速",
    "cardTitle": "TOPP-RA：先算哪里还能刹住，再决定哪里可以加速",
    "question": "轨迹",
    "excerpt": "阅读范围：核对正文的路径投影、集合递推、算法 1、定理条件、实验和附录中的离散误差说明；未独立复证全部渐近最优性证明，未运行代码。下面的手算例子是自行构造的教学说明。",
    "eraId": "轨迹",
    "eraYears": "",
    "eraLabel": "轨迹"
  },
  {
    "slug": "094-cheetah-mpc",
    "file": "094-cheetah-mpc.md",
    "kind": "paper",
    "day": 94,
    "year": 2018,
    "title": "094｜Cheetah 凸 MPC：用简化模型提前安排四足机器人的支撑力",
    "cardTitle": "Cheetah 凸 MPC：用简化模型提前安排四足机器人的支撑力",
    "question": "腿足",
    "excerpt": "阅读范围：方法和结果依据可访问的论文全文镜像中原稿正文及图注核对，不采用平台自动摘要。MIT 存档直接读取受限，图中未能可靠量化的曲线不读数。官方代码仅核对项目说明，未逐行审计或运行；不把后来的 Mini Cheetah 结果并入本篇。",
    "eraId": "腿足",
    "eraYears": "",
    "eraLabel": "腿足"
  },
  {
    "slug": "095-legoloam",
    "file": "095-legoloam.md",
    "kind": "paper",
    "day": 95,
    "year": 2018,
    "title": "095｜LeGO-LOAM：利用地面结构，让激光里程计更轻",
    "cardTitle": "LeGO-LOAM：利用地面结构，让激光里程计更轻",
    "question": "SLAM",
    "excerpt": "阅读范围：逐页阅读 8 页作者稿，放大核对第 7、8 页实验表，并阅读官方 README；未运行代码，未复现数据回放。本文的公式简写、例子和适用性分析不是作者新增实验。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "096-teaser",
    "file": "096-teaser.md",
    "kind": "paper",
    "day": 96,
    "year": 2020,
    "title": "096｜TEASER：错误匹配占多数时，怎样配准点云并检查答案",
    "cardTitle": "TEASER：错误匹配占多数时，怎样配准点云并检查答案",
    "question": "视觉",
    "excerpt": "阅读范围：核对正文中的问题分解、TEASER++ 实现、实验与失败分析，以及官方接口说明；附录证明未逐行复推。下文数学解释和小例子是教学推导，不是新复现实验。",
    "eraId": "视觉",
    "eraYears": "",
    "eraLabel": "视觉"
  },
  {
    "slug": "097-liosam",
    "file": "097-liosam.md",
    "kind": "paper",
    "day": 97,
    "year": 2020,
    "title": "097｜LIO-SAM：让激光、惯性、GPS 与回环共同解释运动",
    "cardTitle": "LIO-SAM：让激光、惯性、GPS 与回环共同解释运动",
    "question": "SLAM",
    "excerpt": "阅读范围：已核对方法与实验正文，并对 PDF 第 4–5 页的公式和实验表作视觉复核；官方仓库作为实现补充，不能把后续分支能力全部归入原论文。没有运行传感器数据或独立复现指标。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "098-orbslam3",
    "file": "098-orbslam3.md",
    "kind": "paper",
    "day": 98,
    "year": 2020,
    "title": "098｜ORB-SLAM3：跟踪丢了以后，地图还能继续生长吗",
    "cardTitle": "ORB-SLAM3：跟踪丢了以后，地图还能继续生长吗",
    "question": "SLAM",
    "excerpt": "阅读范围：核对系统架构、视觉惯性初始化、地图合并及实验正文；公式以下以简化符号解释，不复刻全部优化实现。代码仓库用于确认运行与系统边界，未独立执行基准。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "099-fastlio2",
    "file": "099-fastlio2.md",
    "kind": "paper",
    "day": 99,
    "year": 2021,
    "title": "099｜FAST-LIO2：直接用点云定位，为什么先要解决地图更新",
    "cardTitle": "FAST-LIO2：直接用点云定位，为什么先要解决地图更新",
    "question": "SLAM",
    "excerpt": "阅读范围：核对系统、估计、地图维护和实验章节；复杂度推导未逐行复证，未独立运行。以下矩阵推导和诊断实验属于教学解释。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "100-kissicp",
    "file": "100-kissicp.md",
    "kind": "paper",
    "day": 100,
    "year": 2022,
    "title": "100｜KISS-ICP：把简单基线做好，究竟能走多远",
    "cardTitle": "KISS-ICP：把简单基线做好，究竟能走多远",
    "question": "SLAM",
    "excerpt": "阅读范围：核对方法、参数表、实验与消融正文；文章依据 v2，不能把后续代码版本默认为原实验实现。未重跑数据集。下文例子和矩阵解释是教学推导。",
    "eraId": "SLAM",
    "eraYears": "",
    "eraLabel": "SLAM"
  },
  {
    "slug": "101-epilogue",
    "file": "101-系列总结.md",
    "kind": "epilogue",
    "day": 101,
    "year": null,
    "title": "机器人经典基础总结：把几何、估计、规划与控制接成闭环",
    "cardTitle": "系列总结",
    "question": "跨论文比较与实验阅读方法",
    "excerpt": "机器人经典文献最有价值的部分，不是某个算法缩写，而是它们如何把一个过大的问题拆成可计算的模型，并明确代价。坐标表示让运动可描述，概率估计让噪声可处理，搜索和优化让动作可寻找，反馈让模型与现实之间的偏差可纠正。系统和基准则决定这些组件能否协作，以及比较是否可信。",
    "eraId": "epilogue",
    "eraYears": "",
    "eraLabel": "收尾"
  }
];
window.SERIES_SLUG_MAP = {
  "00-发展时间线总览.md": "00-timeline",
  "00-发展时间线总览": "00-timeline",
  "001-dh.md": "001-dh",
  "001-dh": "001-dh",
  "002-kalman.md": "002-kalman",
  "002-kalman": "002-kalman",
  "003-astar.md": "003-astar",
  "003-astar": "003-astar",
  "004-resolved-rate.md": "004-resolved-rate",
  "004-resolved-rate": "004-resolved-rate",
  "005-newton-euler.md": "005-newton-euler",
  "005-newton-euler": "005-newton-euler",
  "006-ransac.md": "006-ransac",
  "006-ransac": "006-ransac",
  "007-hybrid-force.md": "007-hybrid-force",
  "007-hybrid-force": "007-hybrid-force",
  "008-lucas-kanade.md": "008-lucas-kanade",
  "008-lucas-kanade": "008-lucas-kanade",
  "009-configuration-space.md": "009-configuration-space",
  "009-configuration-space": "009-configuration-space",
  "010-featherstone.md": "010-featherstone",
  "010-featherstone": "010-featherstone",
  "011-brockett.md": "011-brockett",
  "011-brockett": "011-brockett",
  "012-manipulability.md": "012-manipulability",
  "012-manipulability": "012-manipulability",
  "013-impedance.md": "013-impedance",
  "013-impedance": "013-impedance",
  "014-potential-field.md": "014-potential-field",
  "014-potential-field": "014-potential-field",
  "015-subsumption.md": "015-subsumption",
  "015-subsumption": "015-subsumption",
  "016-damped-ik.md": "016-damped-ik",
  "016-damped-ik": "016-damped-ik",
  "017-uncertain-map.md": "017-uncertain-map",
  "017-uncertain-map": "017-uncertain-map",
  "018-operational-space.md": "018-operational-space",
  "018-operational-space": "018-operational-space",
  "019-adaptive-control.md": "019-adaptive-control",
  "019-adaptive-control": "019-adaptive-control",
  "020-tsai-calibration.md": "020-tsai-calibration",
  "020-tsai-calibration": "020-tsai-calibration",
  "021-horn.md": "021-horn",
  "021-horn": "021-horn",
  "022-gilbert-distance.md": "022-gilbert-distance",
  "022-gilbert-distance": "022-gilbert-distance",
  "023-harris.md": "023-harris",
  "023-harris": "023-harris",
  "024-hand-eye.md": "024-hand-eye",
  "024-hand-eye": "024-hand-eye",
  "025-occupancy.md": "025-occupancy",
  "025-occupancy": "025-occupancy",
  "026-vfh.md": "026-vfh",
  "026-vfh": "026-vfh",
  "027-lipm.md": "027-lipm",
  "027-lipm": "027-lipm",
  "028-icp.md": "028-icp",
  "028-icp": "028-icp",
  "029-navigation-functions.md": "029-navigation-functions",
  "029-navigation-functions": "029-navigation-functions",
  "030-grasp-quality.md": "030-grasp-quality",
  "030-grasp-quality": "030-grasp-quality",
  "031-bootstrap-filter.md": "031-bootstrap-filter",
  "031-bootstrap-filter": "031-bootstrap-filter",
  "032-dstar.md": "032-dstar",
  "032-dstar": "032-dstar",
  "033-good-features.md": "033-good-features",
  "033-good-features": "033-good-features",
  "034-force-closure.md": "034-force-closure",
  "034-force-closure": "034-force-closure",
  "035-prm.md": "035-prm",
  "035-prm": "035-prm",
  "036-impulse-contact.md": "036-impulse-contact",
  "036-impulse-contact": "036-impulse-contact",
  "037-visual-servo.md": "037-visual-servo",
  "037-visual-servo": "037-visual-servo",
  "038-dwa.md": "038-dwa",
  "038-dwa": "038-dwa",
  "039-isard-condensation.md": "039-isard-condensation",
  "039-isard-condensation": "039-isard-condensation",
  "040-rrt.md": "040-rrt",
  "040-rrt": "040-rrt",
  "041-mcl.md": "041-mcl",
  "041-mcl": "041-mcl",
  "042-zhang-calibration.md": "042-zhang-calibration",
  "042-zhang-calibration": "042-zhang-calibration",
  "043-rrt-connect.md": "043-rrt-connect",
  "043-rrt-connect": "043-rrt-connect",
  "044-slam-convergence.md": "044-slam-convergence",
  "044-slam-convergence": "044-slam-convergence",
  "045-fastslam.md": "045-fastslam",
  "045-fastslam": "045-fastslam",
  "046-dstar-lite.md": "046-dstar-lite",
  "046-dstar-lite": "046-dstar-lite",
  "047-preview-zmp.md": "047-preview-zmp",
  "047-preview-zmp": "047-preview-zmp",
  "048-sift.md": "048-sift",
  "048-sift": "048-sift",
  "049-five-point.md": "049-five-point",
  "049-five-point": "049-five-point",
  "050-task-priority.md": "050-task-priority",
  "050-task-priority": "050-task-priority",
  "051-id-iLQR.md": "051-id-iLQR",
  "051-id-iLQR": "051-id-iLQR",
  "052-anytime-dstar.md": "052-anytime-dstar",
  "052-anytime-dstar": "052-anytime-dstar",
  "053-graphslam.md": "053-graphslam",
  "053-graphslam": "053-graphslam",
  "054-capture-point.md": "054-capture-point",
  "054-capture-point": "054-capture-point",
  "055-gmap.md": "055-gmap",
  "055-gmap": "055-gmap",
  "056-ptam.md": "056-ptam",
  "056-ptam": "056-ptam",
  "057-isam.md": "057-isam",
  "057-isam": "057-isam",
  "058-ros.md": "058-ros",
  "058-ros": "058-ros",
  "059-chomp.md": "059-chomp",
  "059-chomp": "059-chomp",
  "060-orb.md": "060-orb",
  "060-orb": "060-orb",
  "061-stomp.md": "061-stomp",
  "061-stomp": "061-stomp",
  "062-rrtstar.md": "062-rrtstar",
  "062-rrtstar": "062-rrtstar",
  "063-g2o.md": "063-g2o",
  "063-g2o": "063-g2o",
  "064-kinfu.md": "064-kinfu",
  "064-kinfu": "064-kinfu",
  "065-min-snap.md": "065-min-snap",
  "065-min-snap": "065-min-snap",
  "066-dbow.md": "066-dbow",
  "066-dbow": "066-dbow",
  "067-ompl.md": "067-ompl",
  "067-ompl": "067-ompl",
  "068-isam2.md": "068-isam2",
  "068-isam2": "068-isam2",
  "069-tum-rgbd.md": "069-tum-rgbd",
  "069-tum-rgbd": "069-tum-rgbd",
  "070-kitti.md": "070-kitti",
  "070-kitti": "070-kitti",
  "071-mujoco.md": "071-mujoco",
  "071-mujoco": "071-mujoco",
  "072-contact-implicit.md": "072-contact-implicit",
  "072-contact-implicit": "072-contact-implicit",
  "073-trajopt.md": "073-trajopt",
  "073-trajopt": "073-trajopt",
  "074-octomap.md": "074-octomap",
  "074-octomap": "074-octomap",
  "075-contact-trajopt.md": "075-contact-trajopt",
  "075-contact-trajopt": "075-contact-trajopt",
  "076-lsdslam.md": "076-lsdslam",
  "076-lsdslam": "076-lsdslam",
  "077-loam.md": "077-loam",
  "077-loam": "077-loam",
  "078-svo.md": "078-svo",
  "078-svo": "078-svo",
  "079-informed-rrtstar.md": "079-informed-rrtstar",
  "079-informed-rrtstar": "079-informed-rrtstar",
  "080-wholebody-qp.md": "080-wholebody-qp",
  "080-wholebody-qp": "080-wholebody-qp",
  "081-bitstar.md": "081-bitstar",
  "081-bitstar": "081-bitstar",
  "082-orbslam.md": "082-orbslam",
  "082-orbslam": "082-orbslam",
  "083-imu-preintegration.md": "083-imu-preintegration",
  "083-imu-preintegration": "083-imu-preintegration",
  "084-elasticfusion.md": "084-elasticfusion",
  "084-elasticfusion": "084-elasticfusion",
  "085-dso.md": "085-dso",
  "085-dso": "085-dso",
  "086-euRoC.md": "086-euRoC",
  "086-euRoC": "086-euRoC",
  "087-gpmp2.md": "087-gpmp2",
  "087-gpmp2": "087-gpmp2",
  "088-colmap.md": "088-colmap",
  "088-colmap": "088-colmap",
  "089-orbslam2.md": "089-orbslam2",
  "089-orbslam2": "089-orbslam2",
  "090-se-sync.md": "090-se-sync",
  "090-se-sync": "090-se-sync",
  "091-cbfqp.md": "091-cbfqp",
  "091-cbfqp": "091-cbfqp",
  "092-vinsmono.md": "092-vinsmono",
  "092-vinsmono": "092-vinsmono",
  "093-toppra.md": "093-toppra",
  "093-toppra": "093-toppra",
  "094-cheetah-mpc.md": "094-cheetah-mpc",
  "094-cheetah-mpc": "094-cheetah-mpc",
  "095-legoloam.md": "095-legoloam",
  "095-legoloam": "095-legoloam",
  "096-teaser.md": "096-teaser",
  "096-teaser": "096-teaser",
  "097-liosam.md": "097-liosam",
  "097-liosam": "097-liosam",
  "098-orbslam3.md": "098-orbslam3",
  "098-orbslam3": "098-orbslam3",
  "099-fastlio2.md": "099-fastlio2",
  "099-fastlio2": "099-fastlio2",
  "100-kissicp.md": "100-kissicp",
  "100-kissicp": "100-kissicp",
  "101-系列总结.md": "101-epilogue",
  "101-系列总结": "101-epilogue"
};
