window.RL_CATALOG = {
  "title": "强化学习 60 篇论文：从预测、控制到推理与 Agent",
  "subtitle": "以 60 篇代表论文为线索，串联早期控制、深度价值学习、策略梯度、探索与模仿、多智能体、离线学习、世界模型和语言模型强化学习。",
  "posts": [
    {
      "slug": "00-强化学习发展时间线总览",
      "file": "00-强化学习发展时间线总览.md",
      "kind": "overview",
      "day": 0,
      "year": null,
      "title": "强化学习发展时间线总览：从早期基础到 2026 年",
      "shortTitle": "时间线总览",
      "question": "各阶段的问题、方法与继承关系",
      "eraId": "overview",
      "eraRange": "总览",
      "eraLabel": "阅读入口",
      "excerpt": "从 Bellman 方程到 Q-learning，从 DQN、PPO 到世界模型与推理强化学习，这条时间线关注每个阶段的瓶颈、代表方法，以及新方法继承了什么、改变了什么。"
    },
    {
      "slug": "01-actor-critic",
      "file": "01-actor-critic.md",
      "kind": "paper",
      "day": 1,
      "year": 1983,
      "title": "第 01 天｜早期 Actor–Critic：让行动者拥有一个评价者",
      "shortTitle": "早期 Actor–Critic：让行动者拥有一个评价者",
      "question": "只有失败信号时怎样学会控制",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在在线、单智能体、无模型的倒立摆控制中，作者通过“把行动搜索 ASE 与学习评价 ACE 分开，让预测变化提供更及时的强化”应对“只有失败信号时怎样学会控制”这一问题；证据边界或代价是：原文全文访问受限，不能确认曲线、重复次数和成功门槛。"
    },
    {
      "slug": "02-td-lambda",
      "file": "02-td-lambda.md",
      "kind": "paper",
      "day": 2,
      "year": 1988,
      "title": "第 02 天｜TD(λ)：结果还没出现，预测为什么就能学习",
      "shortTitle": "TD(λ)：结果还没出现，预测为什么就能学习",
      "question": "长序列中的预测与信用分配",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在固定过程的在线预测，通常先不学习策略中，作者通过“用相邻预测差和资格迹更新历史状态”应对“长序列中的预测与信用分配”这一问题；证据边界或代价是：函数表示、步长和 λ 改变偏差与方差，非任意设置都更好。"
    },
    {
      "slug": "03-dyna",
      "file": "03-dyna.md",
      "kind": "paper",
      "day": 3,
      "year": 1990,
      "title": "第 03 天｜Dyna：一次真实交互，如何产生多次学习",
      "shortTitle": "Dyna：一次真实交互，如何产生多次学习",
      "question": "昂贵交互下的学习与规划",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在在线、单智能体、模型驱动的学习与规划中，作者通过“学习环境模型，并把模型生成的一步经验送入同一更新器”应对“昂贵交互下的学习与规划”这一问题；证据边界或代价是：错误模型会反复灌输错误，规划更新也有计算成本。"
    },
    {
      "slug": "04-q-learning",
      "file": "04-q-learning.md",
      "kind": "paper",
      "day": 4,
      "year": 1992,
      "title": "第 04 天｜Q-learning：从一条经验开始，学会比较未来",
      "shortTitle": "Q-learning：从一条经验开始，学会比较未来",
      "question": "不知道转移概率，为什么仍能逼近最优 Q？",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在单智能体、在线采样、无模型、off-policy 的有限 MDP中，作者通过“用采样 Bellman 最优目标逐项更新 Q”应对“未知环境中的最优行动选择”这一问题；证据边界或代价是：渐近结论没有承诺有限预算速度，也不能直接覆盖神经网络。"
    },
    {
      "slug": "05-reinforce",
      "file": "05-reinforce.md",
      "kind": "paper",
      "day": 5,
      "year": 1992,
      "title": "第 05 天｜REINFORCE：环境不可微，也能沿奖励的梯度学习",
      "shortTitle": "REINFORCE：环境不可微，也能沿奖励的梯度学习",
      "question": "为什么 log 概率乘回报会产生正确方向？",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在随机策略的强化学习；原文含即时与延迟强化中，作者通过“以奖励减基线乘对数概率梯度更新策略”应对“只有标量反馈时如何直接训练随机行为”这一问题；证据边界或代价是：高方差、长时信用分配与有限样本噪声仍在。"
    },
    {
      "slug": "06-sarsa",
      "file": "06-sarsa.md",
      "kind": "paper",
      "day": 6,
      "year": 1994,
      "title": "第 06 天｜SARSA：学习实际会执行的行为，而不只学习贪心目标",
      "shortTitle": "SARSA：学习实际会执行的行为，而不只学习贪心目标",
      "question": "探索中的行为价值应该如何更新",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在单智能体、无模型、on-policy 的动作价值学习中，作者通过“以实际采样的下一动作构造 TD 目标，并研究连接主义在线更新”应对“探索中的行为价值应该如何更新”这一问题；证据边界或代价是：不能将后来的教材悬崖例子写成 1994 原文实验。"
    },
    {
      "slug": "07-options",
      "file": "07-options.md",
      "kind": "paper",
      "day": 7,
      "year": 1999,
      "title": "第 07 天｜Options：把“到达门口”也当作一个动作",
      "shortTitle": "Options：把“到达门口”也当作一个动作",
      "question": "长期任务如何在多个时间尺度决策",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在单智能体、时间抽象与层级强化学习框架中，作者通过“用启动集合、内部策略、终止规则定义时间延展动作”应对“长期任务如何在多个时间尺度决策”这一问题；证据边界或代价是：技能选择范围限制可达策略；本文未完整读取原文图表。"
    },
    {
      "slug": "08-policy-gradient-theorem",
      "file": "08-policy-gradient-theorem.md",
      "kind": "paper",
      "day": 8,
      "year": 1999,
      "title": "第 08 天｜策略梯度定理：Critic 近似到什么程度才不带偏 Actor",
      "shortTitle": "策略梯度定理：Critic 近似到什么程度才不带偏 Actor",
      "question": "带函数逼近的策略如何得到可靠梯度",
      "eraId": "classic",
      "eraRange": "1983–1999",
      "eraLabel": "经典基础",
      "excerpt": "在可微策略、平均回报或起始状态折扣回报的 MDP中，作者通过“把目标梯度写成状态访问分布下的策略导数与 Q 的乘积，并给出兼容逼近条件”应对“带函数逼近的策略如何得到可靠梯度”这一问题；证据边界或代价是：任意深度 Critic 都不自动满足兼容条件。"
    },
    {
      "slug": "09-natural-policy-gradient",
      "file": "09-natural-policy-gradient.md",
      "kind": "paper",
      "day": 9,
      "year": 2001,
      "title": "第 09 天｜自然策略梯度：同样改一个参数，行为变化为什么不同",
      "shortTitle": "自然策略梯度：同样改一个参数，行为变化为什么不同",
      "question": "普通梯度对参数尺度敏感",
      "eraId": "approx",
      "eraRange": "2000–2012",
      "eraLabel": "函数逼近",
      "excerpt": "在可微随机策略的单智能体策略搜索中，作者通过“按策略 Fisher 几何预条件化梯度”应对“普通梯度对参数尺度敏感”这一问题；证据边界或代价是：估计 Fisher 与求解线性系统有成本，近似会改变保证。"
    },
    {
      "slug": "10-lspi",
      "file": "10-lspi.md",
      "kind": "paper",
      "day": 10,
      "year": 2003,
      "title": "第 10 天｜LSPI：反复利用同一批数据进行策略迭代",
      "shortTitle": "LSPI：反复利用同一批数据进行策略迭代",
      "question": "有限经验下怎样高效评价并改善策略",
      "eraId": "approx",
      "eraRange": "2000–2012",
      "eraLabel": "函数逼近",
      "excerpt": "在基于批量转移、无模型、近似策略迭代中，作者通过“把最小二乘 TD 扩展到动作价值，交替求解线性系统和贪心改进”应对“有限经验下怎样高效评价并改善策略”这一问题；证据边界或代价是：线性特征、数据覆盖与矩阵条件决定可用性。"
    },
    {
      "slug": "11-double-q",
      "file": "11-double-q.md",
      "kind": "paper",
      "day": 11,
      "year": 2010,
      "title": "第 11 天｜Double Q-learning：为什么取最大值会制造乐观偏差",
      "shortTitle": "Double Q-learning：为什么取最大值会制造乐观偏差",
      "question": "噪声价值估计中的最大化偏差",
      "eraId": "approx",
      "eraRange": "2000–2012",
      "eraLabel": "函数逼近",
      "excerpt": "在表格、无模型、off-policy 控制中，作者通过“用两套价值估计分离动作选择与动作评价”应对“噪声价值估计中的最大化偏差”这一问题；证据边界或代价是：双估计也可能低估，两个估计高度相关时收益有限。"
    },
    {
      "slug": "12-gps",
      "file": "12-gps.md",
      "kind": "paper",
      "day": 12,
      "year": 2013,
      "title": "第 12 天｜Guided Policy Search：先找到好轨迹，再让策略学会产生它",
      "shortTitle": "Guided Policy Search：先找到好轨迹，再让策略学会产生它",
      "question": "复杂连续策略如何绕开低质量局部最优",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在轨迹优化辅助的连续控制策略搜索中，作者通过“用轨迹优化生成引导样本，再做带正则的重要性采样策略优化”应对“复杂连续策略如何绕开低质量局部最优”这一问题；证据边界或代价是：依赖轨迹优化器与相关模型假设，不能当成纯无模型学习。"
    },
    {
      "slug": "13-dpg",
      "file": "13-dpg.md",
      "kind": "paper",
      "day": 13,
      "year": 2014,
      "title": "第 13 天｜DPG：沿价值对动作的梯度，训练连续策略",
      "shortTitle": "DPG：沿价值对动作的梯度，训练连续策略",
      "question": "高维连续动作的策略更新",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在确定性策略、连续动作、单智能体 Actor–Critic中，作者通过“以 Critic 对动作的导数连接确定性 Actor 的参数导数”应对“高维连续动作的策略更新”这一问题；证据边界或代价是：Critic 梯度错误可直接误导 Actor，off-policy 实现与理想定理有差别。"
    },
    {
      "slug": "14-trpo",
      "file": "14-trpo.md",
      "kind": "paper",
      "day": 14,
      "year": 2015,
      "title": "第 14 天｜TRPO：策略更新太猛，为什么会毁掉好不容易学会的行为",
      "shortTitle": "TRPO：策略更新太猛，为什么会毁掉好不容易学会的行为",
      "question": "策略更新的稳定性",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在单智能体、on-policy 随机策略优化中，作者通过“以 KL 信赖域限制策略变化，近似求解受约束替代目标”应对“策略更新的稳定性”这一问题；证据边界或代价是：实际平均 KL 与理论最坏状态约束不同，不构成无条件单调保证。"
    },
    {
      "slug": "15-gae",
      "file": "15-gae.md",
      "kind": "paper",
      "day": 15,
      "year": 2015,
      "title": "第 15 天｜GAE：把一串 TD 误差变成更好用的策略优势",
      "shortTitle": "GAE：把一串 TD 误差变成更好用的策略优势",
      "question": "策略梯度的优势估计噪声",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在on-policy Actor–Critic 的优势估计中，作者通过“以几何权重混合未来 TD 残差”应对“策略梯度的优势估计噪声”这一问题；证据边界或代价是：估计器不能替代策略优化器；偏差取决于折扣和价值误差。"
    },
    {
      "slug": "16-dqn",
      "file": "16-dqn.md",
      "kind": "paper",
      "day": 16,
      "year": 2015,
      "title": "第 16 天｜DQN：让 Q-learning 从像素中学习，先要稳住自举目标",
      "shortTitle": "DQN：让 Q-learning 从像素中学习，先要稳住自举目标",
      "question": "高维图像输入下的动作价值学习",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在在线采样、off-policy、无模型、离散动作中，作者通过“结合卷积 Q 网络、经验回放与周期冻结的目标网络”应对“高维图像输入下的动作价值学习”这一问题；证据边界或代价是：每个游戏单独训练，结果不等于通用模型或所有任务超人。"
    },
    {
      "slug": "17-ddpg",
      "file": "17-ddpg.md",
      "kind": "paper",
      "day": 17,
      "year": 2015,
      "title": "第 17 天｜DDPG：把确定性策略梯度放进深度网络",
      "shortTitle": "DDPG：把确定性策略梯度放进深度网络",
      "question": "从复杂观测学习连续控制",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在在线收集、off-policy、连续动作、无模型 Actor–Critic中，作者通过“把 DPG 与回放、双目标网络、软更新和探索噪声结合”应对“从复杂观测学习连续控制”这一问题；证据边界或代价是：仍易受价值高估、尺度和超参数影响。"
    },
    {
      "slug": "18-double-dqn",
      "file": "18-double-dqn.md",
      "kind": "paper",
      "day": 18,
      "year": 2015,
      "title": "第 18 天｜Double DQN：不用加一整套网络，也能分开选动作与打分",
      "shortTitle": "Double DQN：不用加一整套网络，也能分开选动作与打分",
      "question": "DQN 的价值高估",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在无模型、off-policy、视觉离散控制中，作者通过“在线网络选下一动作，目标网络评价这个动作”应对“DQN 的价值高估”这一问题；证据边界或代价是：共享训练历史仍造成估计相关，减轻高估不等于消除。"
    },
    {
      "slug": "19-per",
      "file": "19-per.md",
      "kind": "paper",
      "day": 19,
      "year": 2015,
      "title": "第 19 天｜优先经验回放：经验并非都值得同样多次重读",
      "shortTitle": "优先经验回放：经验并非都值得同样多次重读",
      "question": "replay中有限梯度预算怎样分配",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在off-policy经验回放机制，可与DQN等组合中，作者通过“按 TD 误差优先采样并用重要性权重修正分布”应对“replay中有限梯度预算怎样分配”这一问题；证据边界或代价是：大 TD 误差也可能只是噪声，采样偏差与存储维护有代价。"
    },
    {
      "slug": "20-dueling-dqn",
      "file": "20-dueling-dqn.md",
      "kind": "paper",
      "day": 20,
      "year": 2015,
      "title": "第 20 天｜Dueling DQN：先判断处境，再判断动作差别",
      "shortTitle": "Dueling DQN：先判断处境，再判断动作差别",
      "question": "许多状态下各动作价值相近",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在无模型、基于价值的离散动作网络中，作者通过“把Q网络分成状态价值与动作相对优势两个流”应对“许多状态下各动作价值相近”这一问题；证据边界或代价是：它是表示结构，不能解决所有自举误差。"
    },
    {
      "slug": "21-alphago",
      "file": "21-alphago.md",
      "kind": "paper",
      "day": 21,
      "year": 2016,
      "title": "第 21 天｜AlphaGo：策略、价值与树搜索如何分工",
      "shortTitle": "AlphaGo：策略、价值与树搜索如何分工",
      "question": "围棋巨大搜索空间中的决策",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在双人零和棋类、自我对弈与已知规则模型规划中，作者通过“结合人类棋谱策略学习、自我对弈强化学习、价值网络与树搜索”应对“围棋巨大搜索空间中的决策”这一问题；证据边界或代价是：不是AlphaGo Zero，训练使用人类棋谱与大量搜索资源。"
    },
    {
      "slug": "22-a3c",
      "file": "22-a3c.md",
      "kind": "paper",
      "day": 22,
      "year": 2016,
      "title": "第 22 天｜A3C：用多个环境的异步经验稳定深度学习",
      "shortTitle": "A3C：用多个环境的异步经验稳定深度学习",
      "question": "深度RL的相关样本与训练吞吐",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在异步多worker、通常近似on-policy的单智能体学习中，作者通过“多个worker独立交互并异步更新共享Actor–Critic”应对“深度RL的相关样本与训练吞吐”这一问题；证据边界或代价是：异步梯度有滞后，部分调参比较不完全对等。"
    },
    {
      "slug": "23-gail",
      "file": "23-gail.md",
      "kind": "paper",
      "day": 23,
      "year": 2016,
      "title": "第 23 天｜GAIL：模仿专家的行为分布，而不只复制单步动作",
      "shortTitle": "GAIL：模仿专家的行为分布，而不只复制单步动作",
      "question": "没有奖励函数时怎样学专家行为",
      "eraId": "deep",
      "eraRange": "2013–2016",
      "eraLabel": "深度突破",
      "excerpt": "在基于专家示范的模仿学习，训练通常在线交互中，作者通过“用判别器区分专家与学习者状态动作，再用RL逼近专家占用分布”应对“没有奖励函数时怎样学专家行为”这一问题；证据边界或代价是：仍需环境交互，判别器奖励可能被利用。"
    },
    {
      "slug": "24-icm",
      "file": "24-icm.md",
      "kind": "paper",
      "day": 24,
      "year": 2017,
      "title": "第 24 天｜ICM：好奇心奖励应该预测什么",
      "shortTitle": "ICM：好奇心奖励应该预测什么",
      "question": "稀疏奖励下的探索",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在在线、无模型策略学习加内在奖励中，作者通过“用逆动力学学习动作相关特征，再以特征前向预测误差作为内在奖励”应对“稀疏奖励下的探索”这一问题；证据边界或代价是：预测误差不等于任务价值，也未完全消除不可控噪声。"
    },
    {
      "slug": "25-maddpg",
      "file": "25-maddpg.md",
      "kind": "paper",
      "day": 25,
      "year": 2017,
      "title": "第 25 天｜MADDPG：训练时看全局，执行时各自行动",
      "shortTitle": "MADDPG：训练时看全局，执行时各自行动",
      "question": "多个学习者使彼此的环境不断变化",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在多智能体、集中训练分散执行、连续策略梯度中，作者通过“为每个智能体用集中Critic，Actor执行时只用局部观测”应对“多个学习者使彼此的环境不断变化”这一问题；证据边界或代价是：集中信息和联合动作输入限制可扩展性。"
    },
    {
      "slug": "26-her",
      "file": "26-her.md",
      "kind": "paper",
      "day": 26,
      "year": 2017,
      "title": "第 26 天｜HER：失败轨迹也能成为另一个目标的成功经验",
      "shortTitle": "HER：失败轨迹也能成为另一个目标的成功经验",
      "question": "目标条件任务中的稀疏成功信号",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在目标条件、off-policy、机器人控制中，作者通过“将已达到的结果重标为目标，重算奖励并复用轨迹”应对“目标条件任务中的稀疏成功信号”这一问题；证据边界或代价是：必须能合法重算目标奖励，随机环境重标可能引入偏差。"
    },
    {
      "slug": "27-ppo",
      "file": "27-ppo.md",
      "kind": "paper",
      "day": 27,
      "year": 2017,
      "title": "第 27 天｜PPO：裁剪替代目标到底限制了什么",
      "shortTitle": "PPO：裁剪替代目标到底限制了什么",
      "question": "在稳定性与实现成本间折中",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在on-policy 采样、随机策略优化，通常搭配 Actor–Critic中，作者通过“采用概率比裁剪或 KL 惩罚，让策略更新更易实现”应对“在稳定性与实现成本间折中”这一问题；证据边界或代价是：裁剪不构成所有动作概率或 KL 的硬约束。"
    },
    {
      "slug": "28-c51",
      "file": "28-c51.md",
      "kind": "paper",
      "day": 28,
      "year": 2017,
      "title": "第 28 天｜C51：不只预测平均回报，还预测回报分布",
      "shortTitle": "C51：不只预测平均回报，还预测回报分布",
      "question": "价值平均数丢失回报分布结构",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在基于价值、off-policy、离散动作的分布式RL中，作者通过“学习固定支撑上的分类回报分布，投影分布Bellman目标”应对“价值平均数丢失回报分布结构”这一问题；证据边界或代价是：固定支撑会截断尾部，控制算子不能直接继承评价的压缩性。"
    },
    {
      "slug": "29-rainbow",
      "file": "29-rainbow.md",
      "kind": "paper",
      "day": 29,
      "year": 2017,
      "title": "第 29 天｜Rainbow：六种DQN改进叠加后，哪些真的重要",
      "shortTitle": "Rainbow：六种DQN改进叠加后，哪些真的重要",
      "question": "独立DQN改进能否互补",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在off-policy、离散视觉价值学习的组合算法中，作者通过“组合Double、优先回放、Dueling、多步、分布式、Noisy Nets”应对“独立DQN改进能否互补”这一问题；证据边界或代价是：贡献有交互，不能把单独提升相加。"
    },
    {
      "slug": "30-sac",
      "file": "30-sac.md",
      "kind": "paper",
      "day": 30,
      "year": 2018,
      "title": "第 30 天｜SAC：随机性进入目标，而不仅是探索噪声",
      "shortTitle": "SAC：随机性进入目标，而不仅是探索噪声",
      "question": "连续控制的探索与样本效率",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在off-policy、无模型、最大熵随机 Actor–Critic中，作者通过“联合最大化回报与策略熵，使用 off-policy Actor–Critic”应对“连续控制的探索与样本效率”这一问题；证据边界或代价是：熵系数改变任务折中，原始版本不自动调温度。"
    },
    {
      "slug": "31-td3",
      "file": "31-td3.md",
      "kind": "paper",
      "day": 31,
      "year": 2018,
      "title": "第 31 天｜TD3：给 DDPG 的价值误差加三道约束",
      "shortTitle": "TD3：给 DDPG 的价值误差加三道约束",
      "question": "Critic 错误被 Actor 放大的不稳定性",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在off-policy、无模型、确定性连续 Actor–Critic中，作者通过“双 Critic 取较小目标、延迟 Actor 更新、平滑目标动作”应对“Critic 错误被 Actor 放大的不稳定性”这一问题；证据边界或代价是：可能引入低估，不能把双 Critic 最小值当真值下界。"
    },
    {
      "slug": "32-impala",
      "file": "32-impala.md",
      "kind": "paper",
      "day": 32,
      "year": 2018,
      "title": "第 32 天｜IMPALA：采样与学习分离后，用V-trace处理策略滞后",
      "shortTitle": "IMPALA：采样与学习分离后，用V-trace处理策略滞后",
      "question": "大规模分布式RL的吞吐与数据滞后",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在分布式Actor–Learner、off-policy校正的Actor–Critic中，作者通过“用Actor–Learner队列解耦并通过截断重要性比构造V-trace”应对“大规模分布式RL的吞吐与数据滞后”这一问题；证据边界或代价是：截断引入特定偏差，系统吞吐不等于环境样本效率。"
    },
    {
      "slug": "33-diayn",
      "file": "33-diayn.md",
      "kind": "paper",
      "day": 33,
      "year": 2018,
      "title": "第 33 天｜DIAYN：没有任务奖励，能否先学会一组不同技能",
      "shortTitle": "DIAYN：没有任务奖励，能否先学会一组不同技能",
      "question": "无外部任务时的技能发现",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在无监督技能发现、目标为技能变量z的最大熵RL中，作者通过“最大化技能与访问状态的可辨识性，同时保留技能内动作熵”应对“无外部任务时的技能发现”这一问题；证据边界或代价是：可辨识不等于有用，技能选择与实际任务还需额外学习。"
    },
    {
      "slug": "34-qmix",
      "file": "34-qmix.md",
      "kind": "paper",
      "day": 34,
      "year": 2018,
      "title": "第 34 天｜QMIX：用单调混合，让局部贪心与团队价值一致",
      "shortTitle": "QMIX：用单调混合，让局部贪心与团队价值一致",
      "question": "合作团队的分散动作选择",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在合作多智能体、集中训练分散执行、值分解中，作者通过“以单调混合网络把各智能体局部Q组合为团队Q”应对“合作团队的分散动作选择”这一问题；证据边界或代价是：单调性限制能表示的协作价值，不能覆盖所有博弈。"
    },
    {
      "slug": "35-pets",
      "file": "35-pets.md",
      "kind": "paper",
      "day": 35,
      "year": 2018,
      "title": "第 35 天｜PETS：用模型集成表示不确定性，再进行短期规划",
      "shortTitle": "PETS：用模型集成表示不确定性，再进行短期规划",
      "question": "模型驱动控制的误差与过度自信",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在在线模型驱动连续控制，MPC执行中，作者通过“训练概率动力学集成，用粒子传播和MPC评估动作序列”应对“模型驱动控制的误差与过度自信”这一问题；证据边界或代价是：规划计算昂贵，不确定性仍可能失准。"
    },
    {
      "slug": "36-rnd",
      "file": "36-rnd.md",
      "kind": "paper",
      "day": 36,
      "year": 2018,
      "title": "第 36 天｜RND：预测一个冻结随机网络，也能产生探索奖励",
      "shortTitle": "RND：预测一个冻结随机网络，也能产生探索奖励",
      "question": "难探索环境中的新颖性估计",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在在线内在奖励探索，通常配PPO中，作者通过“固定随机目标网络，训练预测器拟合它，以拟合误差奖励新观测”应对“难探索环境中的新颖性估计”这一问题；证据边界或代价是：观测噪声、泛化和遗忘仍会影响新颖性。"
    },
    {
      "slug": "37-bcq",
      "file": "37-bcq.md",
      "kind": "paper",
      "day": 37,
      "year": 2018,
      "title": "第 37 天｜BCQ：离线学习时，先别选择数据从没支持过的动作",
      "shortTitle": "BCQ：离线学习时，先别选择数据从没支持过的动作",
      "question": "固定数据上的价值外推错误",
      "eraId": "scale",
      "eraRange": "2017–2018",
      "eraLabel": "稳定与规模",
      "excerpt": "在离线、连续动作、batch-constrained Q-learning中，作者通过“生成接近数据的候选动作，只允许小扰动，再用Critic选择”应对“固定数据上的价值外推错误”这一问题；证据边界或代价是：受限动作集可能排除更优行为，生成模型有覆盖误差。"
    },
    {
      "slug": "38-bear",
      "file": "38-bear.md",
      "kind": "paper",
      "day": 38,
      "year": 2019,
      "title": "第 38 天｜BEAR：限制支持范围，而不必复制行为频率",
      "shortTitle": "BEAR：限制支持范围，而不必复制行为频率",
      "question": "离线Q的自举误差传播",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线、连续动作、约束Actor–Critic中，作者通过“用分布约束让策略靠近数据动作支持，并优化Q”应对“离线Q的自举误差传播”这一问题；证据边界或代价是：MMD是有限样本替代约束，不是精确支持集检测器。"
    },
    {
      "slug": "39-mbpo",
      "file": "39-mbpo.md",
      "kind": "paper",
      "day": 39,
      "year": 2019,
      "title": "第 39 天｜MBPO：不要在错误模型里想象太久",
      "shortTitle": "MBPO：不要在错误模型里想象太久",
      "question": "模型偏差与样本效率的权衡",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在在线模型驱动数据增强，通常搭配SAC中，作者通过“从真实replay状态出发做短分支rollout，用合成经验训练策略”应对“模型偏差与样本效率的权衡”这一问题；证据边界或代价是：模型误差、合成比例和模型训练成本仍需计量。"
    },
    {
      "slug": "40-dreamer",
      "file": "40-dreamer.md",
      "kind": "paper",
      "day": 40,
      "year": 2019,
      "title": "第 40 天｜Dreamer：把策略训练搬到潜在世界里",
      "shortTitle": "Dreamer：把策略训练搬到潜在世界里",
      "question": "从像素高效学习长期控制",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在在线视觉、模型驱动、潜在Actor–Critic中，作者通过“学习潜在动态模型，在想象轨迹中训练Actor和价值网络”应对“从像素高效学习长期控制”这一问题；证据边界或代价是：模型幻觉与潜在表示丢失仍会影响控制。"
    },
    {
      "slug": "41-muzero",
      "file": "41-muzero.md",
      "kind": "paper",
      "day": 41,
      "year": 2019,
      "title": "第 41 天｜MuZero：不用重构世界，也能学出供搜索使用的模型",
      "shortTitle": "MuZero：不用重构世界，也能学出供搜索使用的模型",
      "question": "未知动力学下如何保留树搜索优势",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在模型驱动、潜在搜索、自我对弈或环境交互中，作者通过“只学习与搜索有关的潜在转移、奖励、策略与价值”应对“未知动力学下如何保留树搜索优势”这一问题；证据边界或代价是：潜在模型不是物理真相，训练与搜索资源巨大。"
    },
    {
      "slug": "42-cql",
      "file": "42-cql.md",
      "kind": "paper",
      "day": 42,
      "year": 2020,
      "title": "第 42 天｜CQL：不敢相信未知动作，就直接惩罚乐观估值",
      "shortTitle": "CQL：不敢相信未知动作，就直接惩罚乐观估值",
      "question": "离线策略利用分布外高Q",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线、无模型、保守价值学习中，作者通过“在TD损失外加入压低候选动作、相对抬高数据动作的保守正则”应对“离线策略利用分布外高Q”这一问题；证据边界或代价是：正则过强会过度保守；理论下界有具体条件。"
    },
    {
      "slug": "43-awac",
      "file": "43-awac.md",
      "kind": "paper",
      "day": 43,
      "year": 2020,
      "title": "第 43 天｜AWAC：先用旧数据起步，再顺利接入在线学习",
      "shortTitle": "AWAC：先用旧数据起步，再顺利接入在线学习",
      "question": "离线预训练到在线微调的衔接",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线初始化加在线微调，Actor–Critic中，作者通过“用优势加权的行为回归更新Actor，以off-policy Critic持续改进”应对“离线预训练到在线微调的衔接”这一问题；证据边界或代价是：Critic仍可能评价未知动作出错，奖励与示范条件影响公平性。"
    },
    {
      "slug": "44-decision-transformer",
      "file": "44-decision-transformer.md",
      "kind": "paper",
      "day": 44,
      "year": 2021,
      "title": "第 44 天｜Decision Transformer：把控制写成条件序列预测",
      "shortTitle": "Decision Transformer：把控制写成条件序列预测",
      "question": "离线决策是否必须使用Bellman自举",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线、回报条件的序列建模控制中，作者通过“用期望回报、状态、动作序列训练因果Transformer预测动作”应对“离线决策是否必须使用Bellman自举”这一问题；证据边界或代价是：请求很高回报不保证可实现，数据覆盖仍限制行为。"
    },
    {
      "slug": "45-td3-bc",
      "file": "45-td3-bc.md",
      "kind": "paper",
      "day": 45,
      "year": 2021,
      "title": "第 45 天｜TD3+BC：离线学习中，一项模仿损失能走多远",
      "shortTitle": "TD3+BC：离线学习中，一项模仿损失能走多远",
      "question": "离线方法复杂度与复现敏感性",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线、连续动作、TD3加行为约束中，作者通过“在TD3 Actor目标中加入行为克隆，并规范化状态输入”应对“离线方法复杂度与复现敏感性”这一问题；证据边界或代价是：简单不等于无超参数，BC约束也可能限制改进。"
    },
    {
      "slug": "46-iql",
      "file": "46-iql.md",
      "kind": "paper",
      "day": 46,
      "year": 2021,
      "title": "第 46 天｜IQL：不查询数据外动作，也能向更好价值学习",
      "shortTitle": "IQL：不查询数据外动作，也能向更好价值学习",
      "question": "离线价值学习中的OOD动作查询",
      "eraId": "world",
      "eraRange": "2019–2021",
      "eraLabel": "世界模型与离线",
      "excerpt": "在离线、隐式价值改进，可接在线微调中，作者通过“用数据动作Q的高expectile拟合V，再以V构造TD目标并提取优势加权策略”应对“离线价值学习中的OOD动作查询”这一问题；证据边界或代价是：不能保证部署动作都在支持内，也不能恢复完全缺失行为。"
    },
    {
      "slug": "47-instructgpt",
      "file": "47-instructgpt.md",
      "kind": "paper",
      "day": 47,
      "year": 2022,
      "title": "第 47 天｜InstructGPT：从预测下一个词，到学习人类更偏好的回答",
      "shortTitle": "InstructGPT：从预测下一个词，到学习人类更偏好的回答",
      "question": "语言模型的输出与用户意图不一致",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在语言模型RLHF；提示条件的序列策略学习中，作者通过“用示范SFT、成对偏好奖励模型、PPO及预训练混合更新进行对齐”应对“语言模型的输出与用户意图不一致”这一问题；证据边界或代价是：不是全面能力超越，标注群体、奖励投机与能力回退仍重要。"
    },
    {
      "slug": "48-dreamerv3",
      "file": "48-dreamerv3.md",
      "kind": "paper",
      "day": 48,
      "year": 2023,
      "title": "第 48 天｜DreamerV3：为什么跨任务稳定，比单个任务高分更难",
      "shortTitle": "DreamerV3：为什么跨任务稳定，比单个任务高分更难",
      "question": "世界模型算法跨任务的超参数敏感性",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在模型驱动、潜在世界模型与Actor–Critic，多领域中，作者通过“用离散潜变量、尺度稳健的预测与归一化等配方统一世界模型学习”应对“世界模型算法跨任务的超参数敏感性”这一问题；证据边界或代价是：同一配方分别训练不等于单模型零样本通用。"
    },
    {
      "slug": "49-dpo",
      "file": "49-dpo.md",
      "kind": "paper",
      "day": 49,
      "year": 2023,
      "title": "第 49 天｜DPO：为什么偏好分类可以直接更新语言模型",
      "shortTitle": "DPO：为什么偏好分类可以直接更新语言模型",
      "question": "RLHF的多模型与在线训练复杂性",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在固定偏好数据、参考策略约束的语言模型对齐中，作者通过“把KL正则奖励最优策略代回偏好模型，直接优化偏好对”应对“RLHF的多模型与在线训练复杂性”这一问题；证据边界或代价是：离线偏好覆盖和建模假设仍在，不能当通用在线RL替代。"
    },
    {
      "slug": "50-ipo",
      "file": "50-ipo.md",
      "kind": "paper",
      "day": 50,
      "year": 2023,
      "title": "第 50 天｜IPO：偏好胜负差距，是否应该被无限拉大",
      "shortTitle": "IPO：偏好胜负差距，是否应该被无限拉大",
      "question": "直接偏好优化的过拟合与假设问题",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在离线成对偏好、参考约束的直接策略优化中，作者通过“以更一般偏好目标分析RLHF，并用有限目标margin的平方损失构造IPO”应对“直接偏好优化的过拟合与假设问题”这一问题；证据边界或代价是：目标margin和正则尺度仍需选择，不保证所有偏好任务更好。"
    },
    {
      "slug": "51-kto",
      "file": "51-kto.md",
      "kind": "paper",
      "day": 51,
      "year": 2024,
      "title": "第 51 天｜KTO：只有“好／不好”标签，如何进行模型对齐",
      "shortTitle": "KTO：只有“好／不好”标签，如何进行模型对齐",
      "question": "成对偏好数据的采集要求",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在离线二元反馈的语言模型策略对齐中，作者通过“用前景理论式效用构造可使用单条好坏标签的目标”应对“成对偏好数据的采集要求”这一问题；证据边界或代价是：参考点估计、好坏比例和标签来源会改变效果。"
    },
    {
      "slug": "52-grpo",
      "file": "52-grpo.md",
      "kind": "paper",
      "day": 52,
      "year": 2024,
      "title": "第 52 天｜DeepSeekMath／GRPO：用同题多回答，替代独立价值基线",
      "shortTitle": "DeepSeekMath／GRPO：用同题多回答，替代独立价值基线",
      "question": "语言模型RL的Critic成本与评价基线",
      "eraId": "llm",
      "eraRange": "2022–2024",
      "eraLabel": "语言模型对齐",
      "excerpt": "在语言模型数学后训练，组相对策略梯度中，作者通过“对同提示采样一组回答，以组内奖励统计构造优势，再做裁剪策略优化”应对“语言模型RL的Critic成本与评价基线”这一问题；证据边界或代价是：整篇同时包含预训练和SFT，不能把全部能力归于GRPO。"
    },
    {
      "slug": "53-r1",
      "file": "53-r1.md",
      "kind": "paper",
      "day": 53,
      "year": 2025,
      "title": "第 53 天｜DeepSeek-R1：区分纯RL探索、完整训练管线与蒸馏",
      "shortTitle": "DeepSeek-R1：区分纯RL探索、完整训练管线与蒸馏",
      "question": "大模型推理行为能否通过强化学习增强",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在大模型可验证推理后训练；多个不同训练路径中，作者通过“研究R1-Zero的直接RL，再用冷启动、推理RL、拒绝采样SFT和其他RL构建R1”应对“大模型推理行为能否通过强化学习增强”这一问题；证据边界或代价是：不是从随机权重开始，也不能把小模型蒸馏成绩当独立RL涌现。"
    },
    {
      "slug": "54-dapo",
      "file": "54-dapo.md",
      "kind": "paper",
      "day": 54,
      "year": 2025,
      "title": "第 54 天｜DAPO：GRPO训练中的采样、长度与裁剪，如何一起修正",
      "shortTitle": "DAPO：GRPO训练中的采样、长度与裁剪，如何一起修正",
      "question": "大规模推理RL的熵塌缩、无效样本与长度问题",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在在线推理RL，规则奖励，GRPO衍生配方中，作者通过“组合Clip-Higher、动态采样、token级损失与超长奖励处理”应对“大规模推理RL的熵塌缩、无效样本与长度问题”这一问题；证据边界或代价是：多项同时改变，训练步数不能代表全部生成和筛选成本。"
    },
    {
      "slug": "55-dr-grpo",
      "file": "55-dr-grpo.md",
      "kind": "paper",
      "day": 55,
      "year": 2025,
      "title": "第 55 天｜Dr. GRPO：两个归一化分母，怎样改变学习方向的权重",
      "shortTitle": "Dr. GRPO：两个归一化分母，怎样改变学习方向的权重",
      "question": "GRPO长度与题目难度相关的梯度偏置",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在数学推理RL，GRPO的目标权重分析中，作者通过“移除这两类归一化，用固定分母保留奖励差优势”应对“GRPO长度与题目难度相关的梯度偏置”这一问题；证据边界或代价是：作者所说去偏针对具体来源，不是任何策略梯度意义都无偏。"
    },
    {
      "slug": "56-mbdpo",
      "file": "56-mbdpo.md",
      "kind": "paper",
      "day": 56,
      "year": 2026,
      "title": "第 56 天｜MBDPO：让世界模型、价值学习与扩散策略更一致",
      "shortTitle": "MBDPO：让世界模型、价值学习与扩散策略更一致",
      "question": "模型搜索与价值训练的策略分布不一致",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在模型驱动在线、离线预训练及在线微调中，作者通过“加入行为相关能量约束，用模型回报加权估计score，再训练扩散策略生成器”应对“模型搜索与价值训练的策略分布不一致”这一问题；证据边界或代价是：能量密度解释有采样假设；最大模型并非所有设置都继续改善。"
    },
    {
      "slug": "57-worldsample",
      "file": "57-worldsample.md",
      "kind": "paper",
      "day": 57,
      "year": 2026,
      "title": "第 57 天｜WorldSample：合成经验什么时候值得交给真实机器人学习",
      "shortTitle": "WorldSample：合成经验什么时候值得交给真实机器人学习",
      "question": "真实机器人交互昂贵，合成数据可能污染Critic",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在真实机器人在线RL加视频世界模型中，作者通过“世界模型与策略共同更新，并以Q感知筛选及策略熵调度合成影响”应对“真实机器人交互昂贵，合成数据可能污染Critic”这一问题；证据边界或代价是：摘要与表格数值口径存在不一致，策略熵不是可靠模型误差保证。"
    },
    {
      "slug": "58-factor",
      "file": "58-factor.md",
      "kind": "paper",
      "day": 58,
      "year": 2026,
      "title": "第 58 天｜FACTOR：先分配动作信用，再决定哪些token承担它",
      "shortTitle": "FACTOR：先分配动作信用，再决定哪些token承担它",
      "question": "多轮Agent中轨迹、动作和token三层信用混杂",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在多轮Agent RL与可恢复环境状态中，作者通过“用边界校准TD分动作信用，再用均值为1的非负token权重分配”应对“多轮Agent中轨迹、动作和token三层信用混杂”这一问题；证据边界或代价是：代数守恒不是因果正确，也不是梯度向量守恒。"
    },
    {
      "slug": "59-ttpo",
      "file": "59-ttpo.md",
      "kind": "paper",
      "day": 59,
      "year": 2026,
      "title": "第 59 天｜TTPO：没有标准答案，测试时还能怎样更新模型",
      "shortTitle": "TTPO：没有标准答案，测试时还能怎样更新模型",
      "question": "无标签测试时推理适应",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在无标签训练／测试时参数优化中，作者通过“以多数票伪答案为条件构造教师蒸馏，并对负回答进行token选择的RL抑制”应对“无标签测试时推理适应”这一问题；证据边界或代价是：多数票可能错，峰值检查点选择与全部适应成本必须说明。"
    },
    {
      "slug": "60-draco",
      "file": "60-draco.md",
      "kind": "paper",
      "day": 60,
      "year": 2026,
      "title": "第 60 天｜DRACO：没有成功验证器时，如何把评分准则分配到步骤",
      "shortTitle": "DRACO：没有成功验证器时，如何把评分准则分配到步骤",
      "question": "多轮工具任务缺少可靠终局成功标签",
      "eraId": "agent",
      "eraRange": "2025–2026",
      "eraLabel": "推理与 Agent",
      "excerpt": "在outcome-blind多轮Agent GRPO中，作者通过“动态生成并合并评分准则，用judge引用的步骤重分配组优势”应对“多轮工具任务缺少可靠终局成功标签”这一问题；证据边界或代价是：judge仍是额外监督，保符号分配不等于步骤因果价值。"
    },
    {
      "slug": "61-系列收尾",
      "file": "61-系列收尾.md",
      "kind": "epilogue",
      "day": 61,
      "year": 2026,
      "title": "系列收尾｜把 60 篇论文连成可检验的理解",
      "shortTitle": "系列收尾",
      "question": "横向比较、实验设计与阅读记录",
      "eraId": "epilogue",
      "eraRange": "收尾",
      "eraLabel": "综合",
      "excerpt": "理解一个算法，不仅要能写出更新公式，还要知道它依赖哪些信息、改善了什么指标，以及在什么条件下可能失败。把相近方法放在一起比较，再构造能够推翻直觉的实验，才能把零散论文连成可检验的认识。"
    }
  ]
};
