window.RL_POSTS = [
  {
    "slug": "00-timeline",
    "file": "00-强化学习发展时间线总览.md",
    "title": "强化学习发展时间线总览：从早期基础到 2026 年",
    "cardTitle": "发展时间线总览",
    "day": 0,
    "year": null,
    "question": "",
    "excerpt": "强化学习的发展始终围绕一个问题：如何从有限的反馈中，学会获得更高的长期回报。价值估计、策略优化与环境建模提供了三类互相连接的工具；深度网络、离线数据和语言模型又不断改变它们的使用场景。",
    "eraId": "overview",
    "eraYears": "",
    "eraLabel": "总览"
  },
  {
    "slug": "01-actor-critic",
    "file": "01-actor-critic.md",
    "title": "第 01 天｜早期 Actor–Critic：让行动者拥有一个评价者",
    "cardTitle": "早期 Actor–Critic：让行动者拥有一个评价者",
    "day": 1,
    "year": 1983,
    "question": "只有失败信号时怎样学会控制",
    "excerpt": "**阅读范围**：原始资料限于摘要与书目信息，全文尚未可靠获取。现代 Actor–Critic 公式与伪代码用于解释两类组件的作用，并非 1983 年 ASE/ACE 更新规则的精确复刻；实验曲线与数值尚未核实。",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "02-td-lambda",
    "file": "02-td-lambda.md",
    "title": "第 02 天｜TD(λ)：结果还没出现，预测为什么就能学习",
    "cardTitle": "TD(λ)：结果还没出现，预测为什么就能学习",
    "day": 2,
    "year": 1988,
    "question": "长序列中的预测与信用分配",
    "excerpt": "**研究问题**：长序列中的预测与信用分配",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "03-dyna",
    "file": "03-dyna.md",
    "title": "第 03 天｜Dyna：一次真实交互，如何产生多次学习",
    "cardTitle": "Dyna：一次真实交互，如何产生多次学习",
    "day": 3,
    "year": 1990,
    "question": "昂贵交互下的学习与规划",
    "excerpt": "**研究问题**：昂贵交互下的学习与规划",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "04-q-learning",
    "file": "04-q-learning.md",
    "title": "第 04 天｜Q-learning：从一条经验开始，学会比较未来",
    "cardTitle": "Q-learning：从一条经验开始，学会比较未来",
    "day": 4,
    "year": 1992,
    "question": "不知道转移概率，为什么仍能逼近最优 Q？",
    "excerpt": "**研究问题**：未知环境中的最优行动选择",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "05-reinforce",
    "file": "05-reinforce.md",
    "title": "第 05 天｜REINFORCE：环境不可微，也能沿奖励的梯度学习",
    "cardTitle": "REINFORCE：环境不可微，也能沿奖励的梯度学习",
    "day": 5,
    "year": 1992,
    "question": "为什么 log 概率乘回报会产生正确方向？",
    "excerpt": "**研究问题**：只有标量反馈时如何直接训练随机行为",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "06-sarsa",
    "file": "06-sarsa.md",
    "title": "第 06 天｜SARSA：学习实际会执行的行为，而不只学习贪心目标",
    "cardTitle": "SARSA：学习实际会执行的行为，而不只学习贪心目标",
    "day": 6,
    "year": 1994,
    "question": "探索中的行为价值应该如何更新",
    "excerpt": "**阅读范围**：原始技术报告的 PDF 文本提取受限，可靠信息限于书目与可识别段落。SARSA 更新采用标准教学形式；原报告的实验数值、表号和变体细节尚未核实。",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "07-options",
    "file": "07-options.md",
    "title": "第 07 天｜Options：把“到达门口”也当作一个动作",
    "cardTitle": "Options：把“到达门口”也当作一个动作",
    "day": 7,
    "year": 1999,
    "question": "长期任务如何在多个时间尺度决策",
    "excerpt": "**阅读范围**：原始资料限于摘要与书目信息，全文尚未可靠获取。下文采用 Options 的标准数学教学形式；原论文的实验曲线、消融与页码尚未核实。",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "08-policy-gradient-theorem",
    "file": "08-policy-gradient-theorem.md",
    "title": "第 08 天｜策略梯度定理：Critic 近似到什么程度才不带偏 Actor",
    "cardTitle": "策略梯度定理：Critic 近似到什么程度才不带偏 Actor",
    "day": 8,
    "year": 1999,
    "question": "带函数逼近的策略如何得到可靠梯度",
    "excerpt": "**研究问题**：带函数逼近的策略如何得到可靠梯度",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "09-natural-policy-gradient",
    "file": "09-natural-policy-gradient.md",
    "title": "第 09 天｜自然策略梯度：同样改一个参数，行为变化为什么不同",
    "cardTitle": "自然策略梯度：同样改一个参数，行为变化为什么不同",
    "day": 9,
    "year": 2001,
    "question": "普通梯度对参数尺度敏感",
    "excerpt": "**研究问题**：普通梯度对参数尺度敏感",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "10-lspi",
    "file": "10-lspi.md",
    "title": "第 10 天｜LSPI：反复利用同一批数据进行策略迭代",
    "cardTitle": "LSPI：反复利用同一批数据进行策略迭代",
    "day": 10,
    "year": 2003,
    "question": "有限经验下怎样高效评价并改善策略",
    "excerpt": "**研究问题**：有限经验下怎样高效评价并改善策略",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "11-double-q",
    "file": "11-double-q.md",
    "title": "第 11 天｜Double Q-learning：为什么取最大值会制造乐观偏差",
    "cardTitle": "Double Q-learning：为什么取最大值会制造乐观偏差",
    "day": 11,
    "year": 2010,
    "question": "噪声价值估计中的最大化偏差",
    "excerpt": "**研究问题**：噪声价值估计中的最大化偏差",
    "eraId": "classic",
    "eraYears": "1983—2010",
    "eraLabel": "经典基础"
  },
  {
    "slug": "12-gps",
    "file": "12-gps.md",
    "title": "第 12 天｜Guided Policy Search：先找到好轨迹，再让策略学会产生它",
    "cardTitle": "Guided Policy Search：先找到好轨迹，再让策略学会产生它",
    "day": 12,
    "year": 2013,
    "question": "复杂连续策略如何绕开低质量局部最优",
    "excerpt": "**研究问题**：复杂连续策略如何绕开低质量局部最优",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "13-dpg",
    "file": "13-dpg.md",
    "title": "第 13 天｜DPG：沿价值对动作的梯度，训练连续策略",
    "cardTitle": "DPG：沿价值对动作的梯度，训练连续策略",
    "day": 13,
    "year": 2014,
    "question": "高维连续动作的策略更新",
    "excerpt": "**研究问题**：高维连续动作的策略更新",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "14-trpo",
    "file": "14-trpo.md",
    "title": "第 14 天｜TRPO：策略更新太猛，为什么会毁掉好不容易学会的行为",
    "cardTitle": "TRPO：策略更新太猛，为什么会毁掉好不容易学会的行为",
    "day": 14,
    "year": 2015,
    "question": "策略更新的稳定性",
    "excerpt": "**研究问题**：策略更新的稳定性",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "15-gae",
    "file": "15-gae.md",
    "title": "第 15 天｜GAE：把一串 TD 误差变成更好用的策略优势",
    "cardTitle": "GAE：把一串 TD 误差变成更好用的策略优势",
    "day": 15,
    "year": 2015,
    "question": "策略梯度的优势估计噪声",
    "excerpt": "**研究问题**：策略梯度的优势估计噪声",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "16-dqn",
    "file": "16-dqn.md",
    "title": "第 16 天｜DQN：让 Q-learning 从像素中学习，先要稳住自举目标",
    "cardTitle": "DQN：让 Q-learning 从像素中学习，先要稳住自举目标",
    "day": 16,
    "year": 2015,
    "question": "高维图像输入下的动作价值学习",
    "excerpt": "以前篇 2013 版为背景，本节以 2015 版为准。",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "17-ddpg",
    "file": "17-ddpg.md",
    "title": "第 17 天｜DDPG：把确定性策略梯度放进深度网络",
    "cardTitle": "DDPG：把确定性策略梯度放进深度网络",
    "day": 17,
    "year": 2015,
    "question": "从复杂观测学习连续控制",
    "excerpt": "**研究问题**：从复杂观测学习连续控制",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "18-double-dqn",
    "file": "18-double-dqn.md",
    "title": "第 18 天｜Double DQN：不用加一整套网络，也能分开选动作与打分",
    "cardTitle": "Double DQN：不用加一整套网络，也能分开选动作与打分",
    "day": 18,
    "year": 2015,
    "question": "DQN 的价值高估",
    "excerpt": "**研究问题**：DQN 的价值高估",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "19-per",
    "file": "19-per.md",
    "title": "第 19 天｜优先经验回放：经验并非都值得同样多次重读",
    "cardTitle": "优先经验回放：经验并非都值得同样多次重读",
    "day": 19,
    "year": 2015,
    "question": "replay中有限梯度预算怎样分配",
    "excerpt": "**研究问题**：replay中有限梯度预算怎样分配",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "20-dueling-dqn",
    "file": "20-dueling-dqn.md",
    "title": "第 20 天｜Dueling DQN：先判断处境，再判断动作差别",
    "cardTitle": "Dueling DQN：先判断处境，再判断动作差别",
    "day": 20,
    "year": 2015,
    "question": "许多状态下各动作价值相近",
    "excerpt": "**研究问题**：许多状态下各动作价值相近",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "21-alphago",
    "file": "21-alphago.md",
    "title": "第 21 天｜AlphaGo：策略、价值与树搜索如何分工",
    "cardTitle": "AlphaGo：策略、价值与树搜索如何分工",
    "day": 21,
    "year": 2016,
    "question": "围棋巨大搜索空间中的决策",
    "excerpt": "**研究问题**：围棋巨大搜索空间中的决策",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "22-a3c",
    "file": "22-a3c.md",
    "title": "第 22 天｜A3C：用多个环境的异步经验稳定深度学习",
    "cardTitle": "A3C：用多个环境的异步经验稳定深度学习",
    "day": 22,
    "year": 2016,
    "question": "深度RL的相关样本与训练吞吐",
    "excerpt": "**研究问题**：深度RL的相关样本与训练吞吐",
    "eraId": "deep",
    "eraYears": "2013—2016",
    "eraLabel": "深度强化学习突破"
  },
  {
    "slug": "23-gail",
    "file": "23-gail.md",
    "title": "第 23 天｜GAIL：模仿专家的行为分布，而不只复制单步动作",
    "cardTitle": "GAIL：模仿专家的行为分布，而不只复制单步动作",
    "day": 23,
    "year": 2016,
    "question": "没有奖励函数时怎样学专家行为",
    "excerpt": "**研究问题**：没有奖励函数时怎样学专家行为",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "24-icm",
    "file": "24-icm.md",
    "title": "第 24 天｜ICM：好奇心奖励应该预测什么",
    "cardTitle": "ICM：好奇心奖励应该预测什么",
    "day": 24,
    "year": 2017,
    "question": "稀疏奖励下的探索",
    "excerpt": "**研究问题**：稀疏奖励下的探索",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "25-maddpg",
    "file": "25-maddpg.md",
    "title": "第 25 天｜MADDPG：训练时看全局，执行时各自行动",
    "cardTitle": "MADDPG：训练时看全局，执行时各自行动",
    "day": 25,
    "year": 2017,
    "question": "多个学习者使彼此的环境不断变化",
    "excerpt": "**研究问题**：多个学习者使彼此的环境不断变化",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "26-her",
    "file": "26-her.md",
    "title": "第 26 天｜HER：失败轨迹也能成为另一个目标的成功经验",
    "cardTitle": "HER：失败轨迹也能成为另一个目标的成功经验",
    "day": 26,
    "year": 2017,
    "question": "目标条件任务中的稀疏成功信号",
    "excerpt": "**研究问题**：目标条件任务中的稀疏成功信号",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "27-ppo",
    "file": "27-ppo.md",
    "title": "第 27 天｜PPO：裁剪替代目标到底限制了什么",
    "cardTitle": "PPO：裁剪替代目标到底限制了什么",
    "day": 27,
    "year": 2017,
    "question": "在稳定性与实现成本间折中",
    "excerpt": "**研究问题**：在稳定性与实现成本间折中",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "28-c51",
    "file": "28-c51.md",
    "title": "第 28 天｜C51：不只预测平均回报，还预测回报分布",
    "cardTitle": "C51：不只预测平均回报，还预测回报分布",
    "day": 28,
    "year": 2017,
    "question": "价值平均数丢失回报分布结构",
    "excerpt": "**研究问题**：价值平均数丢失回报分布结构",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "29-rainbow",
    "file": "29-rainbow.md",
    "title": "第 29 天｜Rainbow：六种DQN改进叠加后，哪些真的重要",
    "cardTitle": "Rainbow：六种DQN改进叠加后，哪些真的重要",
    "day": 29,
    "year": 2017,
    "question": "独立DQN改进能否互补",
    "excerpt": "**研究问题**：独立DQN改进能否互补",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "30-sac",
    "file": "30-sac.md",
    "title": "第 30 天｜SAC：随机性进入目标，而不仅是探索噪声",
    "cardTitle": "SAC：随机性进入目标，而不仅是探索噪声",
    "day": 30,
    "year": 2018,
    "question": "连续控制的探索与样本效率",
    "excerpt": "**研究问题**：连续控制的探索与样本效率",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "31-td3",
    "file": "31-td3.md",
    "title": "第 31 天｜TD3：给 DDPG 的价值误差加三道约束",
    "cardTitle": "TD3：给 DDPG 的价值误差加三道约束",
    "day": 31,
    "year": 2018,
    "question": "Critic 错误被 Actor 放大的不稳定性",
    "excerpt": "**研究问题**：Critic 错误被 Actor 放大的不稳定性",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "32-impala",
    "file": "32-impala.md",
    "title": "第 32 天｜IMPALA：采样与学习分离后，用V-trace处理策略滞后",
    "cardTitle": "IMPALA：采样与学习分离后，用V-trace处理策略滞后",
    "day": 32,
    "year": 2018,
    "question": "大规模分布式RL的吞吐与数据滞后",
    "excerpt": "**研究问题**：大规模分布式RL的吞吐与数据滞后",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "33-diayn",
    "file": "33-diayn.md",
    "title": "第 33 天｜DIAYN：没有任务奖励，能否先学会一组不同技能",
    "cardTitle": "DIAYN：没有任务奖励，能否先学会一组不同技能",
    "day": 33,
    "year": 2018,
    "question": "无外部任务时的技能发现",
    "excerpt": "**研究问题**：无外部任务时的技能发现",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "34-qmix",
    "file": "34-qmix.md",
    "title": "第 34 天｜QMIX：用单调混合，让局部贪心与团队价值一致",
    "cardTitle": "QMIX：用单调混合，让局部贪心与团队价值一致",
    "day": 34,
    "year": 2018,
    "question": "合作团队的分散动作选择",
    "excerpt": "**研究问题**：合作团队的分散动作选择",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "35-pets",
    "file": "35-pets.md",
    "title": "第 35 天｜PETS：用模型集成表示不确定性，再进行短期规划",
    "cardTitle": "PETS：用模型集成表示不确定性，再进行短期规划",
    "day": 35,
    "year": 2018,
    "question": "模型驱动控制的误差与过度自信",
    "excerpt": "**研究问题**：模型驱动控制的误差与过度自信",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "36-rnd",
    "file": "36-rnd.md",
    "title": "第 36 天｜RND：预测一个冻结随机网络，也能产生探索奖励",
    "cardTitle": "RND：预测一个冻结随机网络，也能产生探索奖励",
    "day": 36,
    "year": 2018,
    "question": "难探索环境中的新颖性估计",
    "excerpt": "**研究问题**：难探索环境中的新颖性估计",
    "eraId": "scale",
    "eraYears": "2016—2018",
    "eraLabel": "稳定性、探索与规模化"
  },
  {
    "slug": "37-bcq",
    "file": "37-bcq.md",
    "title": "第 37 天｜BCQ：离线学习时，先别选择数据从没支持过的动作",
    "cardTitle": "BCQ：离线学习时，先别选择数据从没支持过的动作",
    "day": 37,
    "year": 2018,
    "question": "固定数据上的价值外推错误",
    "excerpt": "**研究问题**：固定数据上的价值外推错误",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "38-bear",
    "file": "38-bear.md",
    "title": "第 38 天｜BEAR：限制支持范围，而不必复制行为频率",
    "cardTitle": "BEAR：限制支持范围，而不必复制行为频率",
    "day": 38,
    "year": 2019,
    "question": "离线Q的自举误差传播",
    "excerpt": "**研究问题**：离线Q的自举误差传播",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "39-mbpo",
    "file": "39-mbpo.md",
    "title": "第 39 天｜MBPO：不要在错误模型里想象太久",
    "cardTitle": "MBPO：不要在错误模型里想象太久",
    "day": 39,
    "year": 2019,
    "question": "模型偏差与样本效率的权衡",
    "excerpt": "**研究问题**：模型偏差与样本效率的权衡",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "40-dreamer",
    "file": "40-dreamer.md",
    "title": "第 40 天｜Dreamer：把策略训练搬到潜在世界里",
    "cardTitle": "Dreamer：把策略训练搬到潜在世界里",
    "day": 40,
    "year": 2019,
    "question": "从像素高效学习长期控制",
    "excerpt": "**研究问题**：从像素高效学习长期控制",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "41-muzero",
    "file": "41-muzero.md",
    "title": "第 41 天｜MuZero：不用重构世界，也能学出供搜索使用的模型",
    "cardTitle": "MuZero：不用重构世界，也能学出供搜索使用的模型",
    "day": 41,
    "year": 2019,
    "question": "未知动力学下如何保留树搜索优势",
    "excerpt": "**研究问题**：未知动力学下如何保留树搜索优势",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "42-cql",
    "file": "42-cql.md",
    "title": "第 42 天｜CQL：不敢相信未知动作，就直接惩罚乐观估值",
    "cardTitle": "CQL：不敢相信未知动作，就直接惩罚乐观估值",
    "day": 42,
    "year": 2020,
    "question": "离线策略利用分布外高Q",
    "excerpt": "**研究问题**：离线策略利用分布外高Q",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "43-awac",
    "file": "43-awac.md",
    "title": "第 43 天｜AWAC：先用旧数据起步，再顺利接入在线学习",
    "cardTitle": "AWAC：先用旧数据起步，再顺利接入在线学习",
    "day": 43,
    "year": 2020,
    "question": "离线预训练到在线微调的衔接",
    "excerpt": "**研究问题**：离线预训练到在线微调的衔接",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "44-decision-transformer",
    "file": "44-decision-transformer.md",
    "title": "第 44 天｜Decision Transformer：把控制写成条件序列预测",
    "cardTitle": "Decision Transformer：把控制写成条件序列预测",
    "day": 44,
    "year": 2021,
    "question": "离线决策是否必须使用Bellman自举",
    "excerpt": "**研究问题**：离线决策是否必须使用Bellman自举",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "45-td3-bc",
    "file": "45-td3-bc.md",
    "title": "第 45 天｜TD3+BC：离线学习中，一项模仿损失能走多远",
    "cardTitle": "TD3+BC：离线学习中，一项模仿损失能走多远",
    "day": 45,
    "year": 2021,
    "question": "离线方法复杂度与复现敏感性",
    "excerpt": "**研究问题**：离线方法复杂度与复现敏感性",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "46-iql",
    "file": "46-iql.md",
    "title": "第 46 天｜IQL：不查询数据外动作，也能向更好价值学习",
    "cardTitle": "IQL：不查询数据外动作，也能向更好价值学习",
    "day": 46,
    "year": 2021,
    "question": "离线价值学习中的OOD动作查询",
    "excerpt": "**研究问题**：离线价值学习中的OOD动作查询",
    "eraId": "offline",
    "eraYears": "2018—2021",
    "eraLabel": "离线学习与世界模型"
  },
  {
    "slug": "47-instructgpt",
    "file": "47-instructgpt.md",
    "title": "第 47 天｜InstructGPT：从预测下一个词，到学习人类更偏好的回答",
    "cardTitle": "InstructGPT：从预测下一个词，到学习人类更偏好的回答",
    "day": 47,
    "year": 2022,
    "question": "语言模型的输出与用户意图不一致",
    "excerpt": "**研究问题**：语言模型的输出与用户意图不一致",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "48-dreamerv3",
    "file": "48-dreamerv3.md",
    "title": "第 48 天｜DreamerV3：为什么跨任务稳定，比单个任务高分更难",
    "cardTitle": "DreamerV3：为什么跨任务稳定，比单个任务高分更难",
    "day": 48,
    "year": 2023,
    "question": "世界模型算法跨任务的超参数敏感性",
    "excerpt": "**阅读范围**：引用 arXiv 修订正文中的方法与基准结果。2023 指首次预印本年份，后续修订结果不能全部归入首版。各版本的完整差异与代码尚未逐项核实。",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "49-dpo",
    "file": "49-dpo.md",
    "title": "第 49 天｜DPO：为什么偏好分类可以直接更新语言模型",
    "cardTitle": "DPO：为什么偏好分类可以直接更新语言模型",
    "day": 49,
    "year": 2023,
    "question": "RLHF的多模型与在线训练复杂性",
    "excerpt": "**研究问题**：RLHF的多模型与在线训练复杂性",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "50-ipo",
    "file": "50-ipo.md",
    "title": "第 50 天｜IPO：偏好胜负差距，是否应该被无限拉大",
    "cardTitle": "IPO：偏好胜负差距，是否应该被无限拉大",
    "day": 50,
    "year": 2023,
    "question": "直接偏好优化的过拟合与假设问题",
    "excerpt": "**研究问题**：直接偏好优化的过拟合与假设问题",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "51-kto",
    "file": "51-kto.md",
    "title": "第 51 天｜KTO：只有“好／不好”标签，如何进行模型对齐",
    "cardTitle": "KTO：只有“好／不好”标签，如何进行模型对齐",
    "day": 51,
    "year": 2024,
    "question": "成对偏好数据的采集要求",
    "excerpt": "**研究问题**：成对偏好数据的采集要求",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "52-grpo",
    "file": "52-grpo.md",
    "title": "第 52 天｜DeepSeekMath／GRPO：用同题多回答，替代独立价值基线",
    "cardTitle": "DeepSeekMath／GRPO：用同题多回答，替代独立价值基线",
    "day": 52,
    "year": 2024,
    "question": "语言模型RL的Critic成本与评价基线",
    "excerpt": "**研究问题**：语言模型RL的Critic成本与评价基线",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "53-r1",
    "file": "53-r1.md",
    "title": "第 53 天｜DeepSeek-R1：区分纯RL探索、完整训练管线与蒸馏",
    "cardTitle": "DeepSeek-R1：区分纯RL探索、完整训练管线与蒸馏",
    "day": 53,
    "year": 2025,
    "question": "大模型推理行为能否通过强化学习增强",
    "excerpt": "**研究问题**：大模型推理行为能否通过强化学习增强",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "54-dapo",
    "file": "54-dapo.md",
    "title": "第 54 天｜DAPO：GRPO训练中的采样、长度与裁剪，如何一起修正",
    "cardTitle": "DAPO：GRPO训练中的采样、长度与裁剪，如何一起修正",
    "day": 54,
    "year": 2025,
    "question": "大规模推理RL的熵塌缩、无效样本与长度问题",
    "excerpt": "**研究问题**：大规模推理RL的熵塌缩、无效样本与长度问题",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "55-dr-grpo",
    "file": "55-dr-grpo.md",
    "title": "第 55 天｜Dr. GRPO：两个归一化分母，怎样改变学习方向的权重",
    "cardTitle": "Dr. GRPO：两个归一化分母，怎样改变学习方向的权重",
    "day": 55,
    "year": 2025,
    "question": "GRPO长度与题目难度相关的梯度偏置",
    "excerpt": "**研究问题**：GRPO长度与题目难度相关的梯度偏置",
    "eraId": "llm",
    "eraYears": "2022—2025",
    "eraLabel": "语言模型强化学习"
  },
  {
    "slug": "56-mbdpo",
    "file": "56-mbdpo.md",
    "title": "第 56 天｜MBDPO：让世界模型、价值学习与扩散策略更一致",
    "cardTitle": "MBDPO：让世界模型、价值学习与扩散策略更一致",
    "day": 56,
    "year": 2026,
    "question": "模型搜索与价值训练的策略分布不一致",
    "excerpt": "**研究问题**：模型搜索与价值训练的策略分布不一致",
    "eraId": "agent",
    "eraYears": "2026",
    "eraLabel": "近期研究与 Agent"
  },
  {
    "slug": "57-worldsample",
    "file": "57-worldsample.md",
    "title": "第 57 天｜WorldSample：合成经验什么时候值得交给真实机器人学习",
    "cardTitle": "WorldSample：合成经验什么时候值得交给真实机器人学习",
    "day": 57,
    "year": 2026,
    "question": "真实机器人交互昂贵，合成数据可能污染Critic",
    "excerpt": "**研究问题**：真实机器人交互昂贵，合成数据可能污染Critic",
    "eraId": "agent",
    "eraYears": "2026",
    "eraLabel": "近期研究与 Agent"
  },
  {
    "slug": "58-factor",
    "file": "58-factor.md",
    "title": "第 58 天｜FACTOR：先分配动作信用，再决定哪些token承担它",
    "cardTitle": "FACTOR：先分配动作信用，再决定哪些token承担它",
    "day": 58,
    "year": 2026,
    "question": "多轮Agent中轨迹、动作和token三层信用混杂",
    "excerpt": "**研究问题**：多轮Agent中轨迹、动作和token三层信用混杂",
    "eraId": "agent",
    "eraYears": "2026",
    "eraLabel": "近期研究与 Agent"
  },
  {
    "slug": "59-ttpo",
    "file": "59-ttpo.md",
    "title": "第 59 天｜TTPO：没有标准答案，测试时还能怎样更新模型",
    "cardTitle": "TTPO：没有标准答案，测试时还能怎样更新模型",
    "day": 59,
    "year": 2026,
    "question": "无标签测试时推理适应",
    "excerpt": "**研究问题**：无标签测试时推理适应",
    "eraId": "agent",
    "eraYears": "2026",
    "eraLabel": "近期研究与 Agent"
  },
  {
    "slug": "60-draco",
    "file": "60-draco.md",
    "title": "第 60 天｜DRACO：没有成功验证器时，如何把评分准则分配到步骤",
    "cardTitle": "DRACO：没有成功验证器时，如何把评分准则分配到步骤",
    "day": 60,
    "year": 2026,
    "question": "多轮工具任务缺少可靠终局成功标签",
    "excerpt": "**研究问题**：多轮工具任务缺少可靠终局成功标签",
    "eraId": "agent",
    "eraYears": "2026",
    "eraLabel": "近期研究与 Agent"
  },
  {
    "slug": "61-epilogue",
    "file": "61-系列收尾.md",
    "title": "系列收尾｜把 60 篇论文连成可检验的理解",
    "cardTitle": "系列收尾",
    "day": 61,
    "year": null,
    "question": "",
    "excerpt": "理解一个算法，不仅要能写出更新公式，还要知道它依赖哪些信息、改善了什么指标，以及在什么条件下可能失败。把相近方法放在一起比较，再构造能够推翻直觉的实验，才能把零散论文连成可检验的认识。",
    "eraId": "epilogue",
    "eraYears": "",
    "eraLabel": "收尾"
  }
];
window.RL_SLUG_MAP = {
  "00-强化学习发展时间线总览.md": "00-timeline",
  "01-actor-critic.md": "01-actor-critic",
  "02-td-lambda.md": "02-td-lambda",
  "03-dyna.md": "03-dyna",
  "04-q-learning.md": "04-q-learning",
  "05-reinforce.md": "05-reinforce",
  "06-sarsa.md": "06-sarsa",
  "07-options.md": "07-options",
  "08-policy-gradient-theorem.md": "08-policy-gradient-theorem",
  "09-natural-policy-gradient.md": "09-natural-policy-gradient",
  "10-lspi.md": "10-lspi",
  "11-double-q.md": "11-double-q",
  "12-gps.md": "12-gps",
  "13-dpg.md": "13-dpg",
  "14-trpo.md": "14-trpo",
  "15-gae.md": "15-gae",
  "16-dqn.md": "16-dqn",
  "17-ddpg.md": "17-ddpg",
  "18-double-dqn.md": "18-double-dqn",
  "19-per.md": "19-per",
  "20-dueling-dqn.md": "20-dueling-dqn",
  "21-alphago.md": "21-alphago",
  "22-a3c.md": "22-a3c",
  "23-gail.md": "23-gail",
  "24-icm.md": "24-icm",
  "25-maddpg.md": "25-maddpg",
  "26-her.md": "26-her",
  "27-ppo.md": "27-ppo",
  "28-c51.md": "28-c51",
  "29-rainbow.md": "29-rainbow",
  "30-sac.md": "30-sac",
  "31-td3.md": "31-td3",
  "32-impala.md": "32-impala",
  "33-diayn.md": "33-diayn",
  "34-qmix.md": "34-qmix",
  "35-pets.md": "35-pets",
  "36-rnd.md": "36-rnd",
  "37-bcq.md": "37-bcq",
  "38-bear.md": "38-bear",
  "39-mbpo.md": "39-mbpo",
  "40-dreamer.md": "40-dreamer",
  "41-muzero.md": "41-muzero",
  "42-cql.md": "42-cql",
  "43-awac.md": "43-awac",
  "44-decision-transformer.md": "44-decision-transformer",
  "45-td3-bc.md": "45-td3-bc",
  "46-iql.md": "46-iql",
  "47-instructgpt.md": "47-instructgpt",
  "48-dreamerv3.md": "48-dreamerv3",
  "49-dpo.md": "49-dpo",
  "50-ipo.md": "50-ipo",
  "51-kto.md": "51-kto",
  "52-grpo.md": "52-grpo",
  "53-r1.md": "53-r1",
  "54-dapo.md": "54-dapo",
  "55-dr-grpo.md": "55-dr-grpo",
  "56-mbdpo.md": "56-mbdpo",
  "57-worldsample.md": "57-worldsample",
  "58-factor.md": "58-factor",
  "59-ttpo.md": "59-ttpo",
  "60-draco.md": "60-draco",
  "61-系列收尾.md": "61-epilogue"
};
