window.SERIES_POSTS = [
  {
    "slug": "00-timeline",
    "file": "00-发展时间线总览.md",
    "kind": "overview",
    "day": 0,
    "year": null,
    "title": "机器人学习发展时间线：从示范运动到通用动作模型",
    "cardTitle": "发展时间线总览",
    "question": "各阶段的问题、方法与继承关系",
    "excerpt": "机器人学习并非一条不断用大模型替换小模型的直线。运动基元解决行为怎样表示，逆强化学习研究目标怎样获得，深度强化学习探索怎样改进动作，世界模型学习怎样预测后果，VLA 则把语言、视觉与控制连接起来。它们面对的瓶颈不同，也经常组合在同一系统中。",
    "eraId": "overview",
    "eraYears": "",
    "eraLabel": "总览"
  },
  {
    "slug": "001-dmp",
    "file": "001-dmp.md",
    "kind": "paper",
    "day": 1,
    "year": 2002,
    "title": "001｜DMP：把示范写进稳定动力系统",
    "cardTitle": "DMP：把示范写进稳定动力系统",
    "question": "运动表示",
    "excerpt": "教机械臂挥拍，最直接的办法是记录每一时刻的关节角，再照表播放。问题在于，这张表没有回答“如果球的位置变了，或者手臂被短暂挡住，下一步怎么办”。离线插值可以让曲线更平滑，却不能自动提供受扰后的行为规律。",
    "eraId": "运动表示",
    "eraYears": "",
    "eraLabel": "运动表示"
  },
  {
    "slug": "002-apprenticeship",
    "file": "002-apprenticeship.md",
    "kind": "paper",
    "day": 2,
    "year": 2004,
    "title": "002｜学徒学习：从行为恢复任务偏好",
    "cardTitle": "学徒学习：从行为恢复任务偏好",
    "question": "模仿与奖励",
    "excerpt": "一个人可以演示怎样开车，却很难精确写出“碰撞、偏离车道、速度”之间的奖励权重。行为克隆直接学习状态到动作的映射，但没有明确利用“这些选择服务于长期目标”这一结构。学徒学习尝试从示范中恢复足以生成合适行为的奖励描述。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "003-maxent-irl",
    "file": "003-maxent-irl.md",
    "kind": "paper",
    "day": 3,
    "year": 2008,
    "title": "003｜最大熵逆强化学习：多条合理轨迹如何共存",
    "cardTitle": "最大熵逆强化学习：多条合理轨迹如何共存",
    "question": "模仿与奖励",
    "excerpt": "同一个驾驶员去同一个地点，今天可能走主路，明天可能绕一条支路。把其中一条当作唯一最优解，会把另一条解释成错误；只匹配平均特征，又可能得到许多同样合理的行为分布。最大熵逆强化学习为这种不确定性增加了一个选择原则：在满足观察到的统计约束之后，不额外偏爱某一条轨迹。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "004-power",
    "file": "004-power.md",
    "kind": "paper",
    "day": 4,
    "year": 2008,
    "title": "004｜PoWER：用回报重加权动作探索",
    "cardTitle": "PoWER：用回报重加权动作探索",
    "question": "机器人强化学习",
    "excerpt": "接球入杯这样的动作，成功取决于整段摆动的节奏。若每个控制周期独立加入白噪声，产生的往往是抖动，而不是有意义的动作变化。PoWER 把探索与运动基元的参数化联系起来，让试错更像“稍微改变这一段挥动”，再按后续回报决定哪些变化值得保留。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "005-pi2",
    "file": "005-pi2.md",
    "kind": "paper",
    "day": 5,
    "year": 2010,
    "title": "005｜PI²：从轨迹代价到策略参数更新",
    "cardTitle": "PI²：从轨迹代价到策略参数更新",
    "question": "机器人强化学习",
    "excerpt": "机器人动作优化经常面临这样的条件：能运行一段轨迹并得到代价，却无法对碰撞、摩擦和整段物理过程直接求导。PI² 将低代价轨迹转化为较大概率权重，用这些权重平均探索扰动，从而调整参数化策略。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "006-dagger",
    "file": "006-dagger.md",
    "kind": "paper",
    "day": 6,
    "year": 2011,
    "title": "006｜DAgger：修复模仿中的分布偏移",
    "cardTitle": "DAgger：修复模仿中的分布偏移",
    "question": "模仿与奖励",
    "excerpt": "专家开车总在车道中央，因此示范里很少出现“已经偏到路边，应该怎样回正”。一个监督模型即使在专家数据上预测准确，执行时只要稍有偏差，就可能进入陌生状态，再做出更大错误。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "007-pilco",
    "file": "007-pilco.md",
    "kind": "paper",
    "day": 7,
    "year": 2011,
    "title": "007｜PILCO：把模型不确定性传播到长期回报",
    "cardTitle": "PILCO：把模型不确定性传播到长期回报",
    "question": "模型学习",
    "excerpt": "只观察过几次摆动，机器人可以拟合出很多不同的动力学函数。若随便选一个确定模型，再在它上面优化长轨迹，策略就可能利用模型在未知区域的错误。PILCO 的出发点是：不仅学习预测均值，也要把“模型还不知道什么”带入未来状态与成本的计算。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "008-promp",
    "file": "008-promp.md",
    "kind": "paper",
    "day": 8,
    "year": 2013,
    "title": "008｜ProMP：把动作技能表示为轨迹分布",
    "cardTitle": "ProMP：把动作技能表示为轨迹分布",
    "question": "运动表示",
    "excerpt": "两次伸手动作看起来略有不同，却都准确抓住杯子：肩膀往左一点，手肘就可以往右补偿。若只保留每个关节的平均曲线，就会丢掉这种协调；若分别对每个关节加独立噪声，原本互相抵消的变化又可能让手偏离杯口。",
    "eraId": "运动表示",
    "eraYears": "",
    "eraLabel": "运动表示"
  },
  {
    "slug": "009-gps",
    "file": "009-gps.md",
    "kind": "paper",
    "day": 9,
    "year": 2013,
    "title": "009｜GPS：让轨迹优化指导策略学习",
    "cardTitle": "GPS：让轨迹优化指导策略学习",
    "question": "机器人强化学习",
    "excerpt": "轨迹优化器可以找到一段漂亮的跑步动作，但它常依赖特定起点、时刻与地形。神经网络策略可以直接根据当前状态反馈控制，却很难从随机探索发现同样好的动作。GPS 把两者连接：用轨迹优化得到的高回报分布提供引导样本，再用这些样本与当前策略样本共同训练参数化策略。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "010-visuomotor",
    "file": "010-visuomotor.md",
    "kind": "paper",
    "day": 10,
    "year": 2015,
    "title": "010｜视觉运动策略：从相机到机械臂动作",
    "cardTitle": "视觉运动策略：从相机到机械臂动作",
    "question": "视觉控制",
    "excerpt": "传统流水线先估计物体位置，再把位置交给控制器。这个分工清楚，但感知目标通常是几何误差最小，未必最适合实际操作。例如拧瓶盖需要同时关注瓶口、瓶盖和夹爪相对姿态，单纯估计瓶子中心可能丢掉关键接触信息。",
    "eraId": "视觉控制",
    "eraYears": "",
    "eraLabel": "视觉控制"
  },
  {
    "slug": "011-ddpg",
    "file": "011-ddpg.md",
    "kind": "paper",
    "day": 11,
    "year": 2015,
    "title": "011｜DDPG：在连续动作上直接优化价值",
    "cardTitle": "DDPG：在连续动作上直接优化价值",
    "question": "机器人强化学习",
    "excerpt": "机械臂的电机力矩不是“左、右、停”三个按钮，而是一组实数。若把每个关节切成十档，七个关节就有一千万种组合。DQN 的逐个动作比较因此难以直接搬到机器人上。DDPG 的办法是让一个网络直接提出动作，再让另一个网络评价这个动作；评价网络还告诉提议网络，动作朝哪个方向改变可能更好。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "012-guided-cost",
    "file": "012-guided-cost.md",
    "kind": "paper",
    "day": 12,
    "year": 2016,
    "title": "012｜Guided Cost Learning：一起学习代价与策略",
    "cardTitle": "Guided Cost Learning：一起学习代价与策略",
    "question": "模仿与奖励",
    "excerpt": "教机械臂放盘子，写“离目标越近越好”似乎够用了。但快速撞进盘架也可能获得很低的位置误差，却打碎盘子。示范展示了人想要的过程，问题是如何把这些过程变成能够指导控制的代价，而不是只能原样回放的轨迹。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "013-naf",
    "file": "013-naf.md",
    "kind": "paper",
    "day": 13,
    "year": 2016,
    "title": "013｜NAF：让连续 Q 的最大化可以解析求解",
    "cardTitle": "NAF：让连续 Q 的最大化可以解析求解",
    "question": "机器人强化学习",
    "excerpt": "DDPG 用 Actor 近似寻找高价值动作。NAF 则问：能不能把价值函数设计成一种特殊形状，让最优动作直接读出来？答案是可以，但需要牺牲一部分表达能力。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "014-hand-eye",
    "file": "014-hand-eye.md",
    "kind": "paper",
    "day": 14,
    "year": 2016,
    "title": "014｜手眼协调：从大规模抓取中学习闭环视觉控制",
    "cardTitle": "手眼协调：从大规模抓取中学习闭环视觉控制",
    "question": "抓取操作",
    "excerpt": "看一眼物体，计算一个抓取点，再闭眼执行，在真实环境里经常不够。物体可能被夹爪碰动，执行器存在误差，相机与机械臂的相对位置也可能略有变化。这篇论文把抓取分成两个部分：神经网络判断“这样移动以后能不能抓住”，控制器不断选择动作，并在收到新图像后重新判断。",
    "eraId": "抓取操作",
    "eraYears": "",
    "eraLabel": "抓取操作"
  },
  {
    "slug": "015-gail",
    "file": "015-gail.md",
    "kind": "paper",
    "day": 15,
    "year": 2016,
    "title": "015｜GAIL：匹配长期行为分布",
    "cardTitle": "GAIL：匹配长期行为分布",
    "question": "模仿与奖励",
    "excerpt": "行为克隆问：“看到这个状态，专家会输出什么动作？”GAIL 换了一个角度：“机器人实际走出来的状态和动作，能否让一个分类器分不清它与专家？”",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "016-visual-foresight",
    "file": "016-visual-foresight.md",
    "kind": "paper",
    "day": 16,
    "year": 2016,
    "title": "016｜视觉预见：通过预测视频规划动作",
    "cardTitle": "视觉预见：通过预测视频规划动作",
    "question": "模型学习",
    "excerpt": "一个抓取成功预测器只能给动作打分；一个视频预测模型还能问：“这样推一下，桌上的东西会如何移动？”这篇论文将动作条件视频预测接到模型预测控制，让机器人在预测的未来中挑选动作，再到现实执行第一步。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "017-progressive",
    "file": "017-progressive.md",
    "kind": "paper",
    "day": 17,
    "year": 2016,
    "title": "017｜渐进网络：像素策略如何迁移到真机",
    "cardTitle": "渐进网络：像素策略如何迁移到真机",
    "question": "仿真迁移",
    "excerpt": "仿真中学会伸手，不代表真实相机里的机械臂也能照做。直接从头训练浪费已有能力，直接微调又可能破坏原来有用的特征。本文采用渐进网络：冻结仿真策略，增加一条新网络，通过横向连接读取旧网络的中间表示，再在真机上学习。",
    "eraId": "仿真迁移",
    "eraYears": "",
    "eraLabel": "仿真迁移"
  },
  {
    "slug": "018-domain-randomization",
    "file": "018-domain-randomization.md",
    "kind": "paper",
    "day": 18,
    "year": 2017,
    "title": "018｜域随机化：让真实视觉成为一种变化",
    "cardTitle": "域随机化：让真实视觉成为一种变化",
    "question": "仿真迁移",
    "excerpt": "如果仿真图像和真实图像不一样，常见思路是把渲染做得更逼真。Domain Randomization 提供另一条路径：让模拟场景的纹理、灯光、相机和干扰物大量变化，使模型无法依赖某一种外观捷径，只能寻找更稳定的线索。",
    "eraId": "仿真迁移",
    "eraYears": "",
    "eraLabel": "仿真迁移"
  },
  {
    "slug": "019-one-shot",
    "file": "019-one-shot.md",
    "kind": "paper",
    "day": 19,
    "year": 2017,
    "title": "019｜一次示范模仿：学习如何使用新示范",
    "cardTitle": "一次示范模仿：学习如何使用新示范",
    "question": "模仿与奖励",
    "excerpt": "这里的 one-shot 不是从零开始只看一条示范就学会机器人控制。模型先在大量相关任务上学习“如何利用示范”，遇到新任务时，再把一条示范当作上下文，直接输出适合当前状态的动作。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "020-dexnet2",
    "file": "020-dexnet2.md",
    "kind": "paper",
    "day": 20,
    "year": 2017,
    "title": "020｜Dex-Net 2.0：解析抓取指标与合成深度数据",
    "cardTitle": "Dex-Net 2.0：解析抓取指标与合成深度数据",
    "question": "抓取操作",
    "excerpt": "真实机器人收集百万次抓取很昂贵。Dex-Net 2.0 将一部分代价搬到离线：从物体网格生成抓取候选，用解析力学和不确定性采样评估质量，再渲染带噪深度图，训练神经网络快速预测候选抓取的可靠性。",
    "eraId": "抓取操作",
    "eraYears": "",
    "eraLabel": "抓取操作"
  },
  {
    "slug": "021-dart",
    "file": "021-dart.md",
    "kind": "paper",
    "day": 21,
    "year": 2017,
    "title": "021｜DART：在专家示范中注入恢复机会",
    "cardTitle": "DART：在专家示范中注入恢复机会",
    "question": "模仿与奖励",
    "excerpt": "一条完美示范可能没有教机器人如何恢复。夹爪偏左一点时，人会顺手修正；如果所有训练轨迹都毫无偏差，学习者真正执行时反而不知道怎样回到正确路线。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "022-her",
    "file": "022-her.md",
    "kind": "paper",
    "day": 22,
    "year": 2017,
    "title": "022｜HER：失败轨迹中的新目标",
    "cardTitle": "HER：失败轨迹中的新目标",
    "question": "机器人强化学习",
    "excerpt": "机械臂原本想把方块推到桌角，却只推到了桌子中央。对原目标它失败了，但这段经验仍告诉我们：执行这些动作能够到达中央。HER 在回放时更换目标、重新计算奖励，把经验变成对另一个真实可达目标的学习数据。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "023-dapg",
    "file": "023-dapg.md",
    "kind": "paper",
    "day": 23,
    "year": 2017,
    "title": "023｜DAPG：示范如何引导灵巧操作探索",
    "cardTitle": "DAPG：示范如何引导灵巧操作探索",
    "question": "灵巧操作",
    "excerpt": "五指手要拿起锤子再敲钉子，随机探索首先得碰巧学会接近、握住、提起和挥动。只在最后奖励“钉进去”，几乎没有早期学习信号。DAPG 用少量示范先把策略放到有意义的行为附近，再在强化学习期间持续加入模仿梯度。",
    "eraId": "灵巧操作",
    "eraYears": "",
    "eraLabel": "灵巧操作"
  },
  {
    "slug": "024-dynamics-randomization",
    "file": "024-dynamics-randomization.md",
    "kind": "paper",
    "day": 24,
    "year": 2017,
    "title": "024｜动力学随机化：从参数变化中学习鲁棒控制",
    "cardTitle": "动力学随机化：从参数变化中学习鲁棒控制",
    "question": "仿真迁移",
    "excerpt": "在仿真中把圆盘推到目标位置，并不意味着真实机械臂也能做到。同样的关节目标角，真实电机可能晚一点响应；同样的推力，桌面的摩擦可能让圆盘滑得更远。只适应一组精确参数的策略，会把仿真器的习惯误当成世界的规律。",
    "eraId": "仿真迁移",
    "eraYears": "",
    "eraLabel": "仿真迁移"
  },
  {
    "slug": "025-sac",
    "file": "025-sac.md",
    "kind": "paper",
    "day": 25,
    "year": 2018,
    "title": "025｜SAC：把动作随机性写进控制目标",
    "cardTitle": "SAC：把动作随机性写进控制目标",
    "question": "机器人强化学习",
    "excerpt": "机器人学习中，一条关节动作看起来回报最高，可能只是价值网络暂时高估了它。若策略迅速变成确定性输出，之后的数据又围绕这个动作产生，错误就可能自我强化。SAC 让策略同时追求任务回报和动作分布的熵：在相近的好选择之间保留随机性，而不是立即收缩到单一动作。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "026-td3",
    "file": "026-td3.md",
    "kind": "paper",
    "day": 26,
    "year": 2018,
    "title": "026｜TD3：防止策略利用价值估计错误",
    "cardTitle": "TD3：防止策略利用价值估计错误",
    "question": "机器人强化学习",
    "excerpt": "假设机械臂尝试动作 A 得分普通，而价值网络错误地认为动作 B 特别好。Actor 会向 B 靠近；Critic 又用“下一步做 B”的预测给当前动作打分。即使最初误差很小，这个循环也可能把虚假的高分扩散开。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "027-dynamics-embedding",
    "file": "027-dynamics-embedding.md",
    "kind": "paper",
    "day": 27,
    "year": 2018,
    "title": "027｜动态环境元强化学习：从短历史识别新动力学",
    "cardTitle": "动态环境元强化学习：从短历史识别新动力学",
    "question": "仿真迁移",
    "excerpt": "一只机器人在地毯上走得很好，换到斜坡、拖上负载或损坏一条腿后，原来的动作与运动关系会变。可以从头训练新策略，但数据和时间都不允许；也可以微调环境模型，但普通神经网络未必能靠最近几步就学好。",
    "eraId": "仿真迁移",
    "eraYears": "",
    "eraLabel": "仿真迁移"
  },
  {
    "slug": "028-deepmimic",
    "file": "028-deepmimic.md",
    "kind": "paper",
    "day": 28,
    "year": 2018,
    "title": "028｜DeepMimic：让物理角色学习动作技能",
    "cardTitle": "DeepMimic：让物理角色学习动作技能",
    "question": "全身运动",
    "excerpt": "一段后空翻动画只给出各时刻的身体姿态，不告诉机器人应该施加什么力矩。直接播放姿态可能穿地、失衡，或者在受推后完全无法恢复。DeepMimic 让物理仿真角色通过强化学习追踪参考动作，同时学习反馈控制。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "029-pets",
    "file": "029-pets.md",
    "kind": "paper",
    "day": 29,
    "year": 2018,
    "title": "029｜PETS：用概率集成模型做控制规划",
    "cardTitle": "PETS：用概率集成模型做控制规划",
    "question": "模型学习",
    "excerpt": "神经网络预测“推一下，物体会到这里”，规划器就可能专挑模型最乐观的动作。但数据少时，这个预测也许只是猜测；即使模型已充分学习，摩擦和执行噪声仍会让结果不同。PETS 为这两种不确定性分别留出表达方式，再让多条可能的未来参与动作选择。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "030-qt-opt",
    "file": "030-qt-opt.md",
    "kind": "paper",
    "day": 30,
    "year": 2018,
    "title": "030｜QT-Opt：大规模视觉抓取的 Q 学习",
    "cardTitle": "QT-Opt：大规模视觉抓取的 Q 学习",
    "question": "抓取操作",
    "excerpt": "看到瓶子直立时，最好的动作可能先把它推倒；物体滑出夹爪时，最好的动作可能重新张开并调整。单次抓点评分很难表示这些“现在不抓，之后更好抓”的选择。QT-Opt 将移动、开合与结束都纳入连续决策，用最终抓取结果训练视觉 Q 函数。",
    "eraId": "抓取操作",
    "eraYears": "",
    "eraLabel": "抓取操作"
  },
  {
    "slug": "031-dexterous",
    "file": "031-dexterous.md",
    "kind": "paper",
    "day": 31,
    "year": 2018,
    "title": "031｜灵巧手：用随机化模拟学习物体重定向",
    "cardTitle": "灵巧手：用随机化模拟学习物体重定向",
    "question": "灵巧操作",
    "excerpt": "五指手旋转物体，需要一部分手指支撑、一部分手指换位，还要利用接触和重力。手指传动、软指尖和摩擦很难在刚体仿真中精确建模。本文没有等到模型完美，而是把大量可能误差加入仿真，训练带记忆的策略，再直接迁移到真实 Shadow 手。",
    "eraId": "灵巧操作",
    "eraYears": "",
    "eraLabel": "灵巧操作"
  },
  {
    "slug": "032-anymal",
    "file": "032-anymal.md",
    "kind": "paper",
    "day": 32,
    "year": 2019,
    "title": "032｜ANYmal：把学习到的敏捷运动带到真机",
    "cardTitle": "ANYmal：把学习到的敏捷运动带到真机",
    "question": "全身运动",
    "excerpt": "腿式机器人的困难不只是算出下一脚踩在哪里。策略发出关节指令后，电机、弹性机构、底层控制器和通信延迟一起决定真正产生的力矩。仿真若把这些过程当成立即响应，机器人可能在电脑里跑得很好，上机却剧烈振荡。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "033-mbpo",
    "file": "033-mbpo.md",
    "kind": "paper",
    "day": 33,
    "year": 2019,
    "title": "033｜MBPO：什么时候该相信模型生成的经验",
    "cardTitle": "MBPO：什么时候该相信模型生成的经验",
    "question": "模型学习",
    "excerpt": "有了环境模型，就能在电脑中制造大量训练经验。但是，模型越往未来预测，错误越容易累积；策略还可能专门找到模型“以为有高回报”、现实却没有的动作。于是模型强化学习经常早期学习快，后期表现反而落后。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "034-rlbench",
    "file": "034-rlbench.md",
    "kind": "paper",
    "day": 34,
    "year": 2019,
    "title": "034｜RLBench：面向视觉操作的任务集合",
    "cardTitle": "RLBench：面向视觉操作的任务集合",
    "question": "基准与数据",
    "excerpt": "如果两个机器人算法分别在自建的三个任务上测试，即使各自成功率都很高，也难以知道谁更通用。一个方法可能只是选择了更容易的物体、初始位置或成功条件。RLBench 试图解决的首先是研究如何比较，其次才是机器人如何学习。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "035-rubiks",
    "file": "035-rubiks.md",
    "kind": "paper",
    "day": 35,
    "year": 2019,
    "title": "035｜机械手魔方：自动域随机化与长期控制",
    "cardTitle": "机械手魔方：自动域随机化与长期控制",
    "question": "灵巧操作",
    "excerpt": "“机器人学会还原魔方”容易让人想到网络自己发现了魔方解法。但这篇论文的核心是让灵巧手可靠执行解法要求的翻转和转面。离散解法由已有求解器提供；学习系统负责看清状态并处理复杂接触。",
    "eraId": "灵巧操作",
    "eraYears": "",
    "eraLabel": "灵巧操作"
  },
  {
    "slug": "036-metaworld",
    "file": "036-metaworld.md",
    "kind": "paper",
    "day": 36,
    "year": 2019,
    "title": "036｜Meta-World：多任务操作应该怎样比较",
    "cardTitle": "Meta-World：多任务操作应该怎样比较",
    "question": "基准与数据",
    "excerpt": "会向不同位置推同一个物体，不等于会开门、关抽屉和装配。早期元强化学习常把目标速度或目标坐标变化称作“新任务”，但这类测试很难检验能否快速学会新的操作结构。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "037-dreamer",
    "file": "037-dreamer.md",
    "kind": "paper",
    "day": 37,
    "year": 2019,
    "title": "037｜Dreamer：在潜在世界里训练控制策略",
    "cardTitle": "Dreamer：在潜在世界里训练控制策略",
    "question": "模型学习",
    "excerpt": "机器人从图像学习控制，既要理解画面，又要判断动作会造成什么。直接靠环境试错很贵；在像素空间反复生成完整视频又很耗计算。Dreamer 把经验压缩成可预测的潜在状态，然后在这个空间里训练策略。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "038-cql",
    "file": "038-cql.md",
    "kind": "paper",
    "day": 38,
    "year": 2020,
    "title": "038｜CQL：离线机器人数据为什么需要保守估值",
    "cardTitle": "CQL：离线机器人数据为什么需要保守估值",
    "question": "离线学习",
    "excerpt": "机械臂积累了许多旧操作记录，能否不再冒险试错，直接学出更好的策略？普通 SAC 虽然能重复使用旧经验，却不保证在完全离线时稳定：它可能选中数据里没有、价值网络却误判很好的动作，而离线训练没有机会去环境中纠错。",
    "eraId": "离线学习",
    "eraYears": "",
    "eraLabel": "离线学习"
  },
  {
    "slug": "039-awac",
    "file": "039-awac.md",
    "kind": "paper",
    "day": 39,
    "year": 2020,
    "title": "039｜AWAC：示范预热后的在线策略改进",
    "cardTitle": "AWAC：示范预热后的在线策略改进",
    "question": "离线学习",
    "excerpt": "机器人已经有一些示范和旧尝试，最实用的目标往往不是永远离线，而是先用旧数据建立起点，再通过少量新交互改善。普通强化学习可能在刚开始微调时把已有能力弄坏；过强的离线约束又可能使策略一直模仿旧数据。",
    "eraId": "离线学习",
    "eraYears": "",
    "eraLabel": "离线学习"
  },
  {
    "slug": "040-transporter",
    "file": "040-transporter.md",
    "kind": "paper",
    "day": 40,
    "year": 2020,
    "title": "040｜Transporter：用空间对应关系学习操作",
    "cardTitle": "Transporter：用空间对应关系学习操作",
    "question": "抓取操作",
    "excerpt": "拿起一个物体再放进槽里，放哪里取决于刚才抓在哪里。从物体左边缘吸起，与从中心吸起，末端最终位置不能一样。若把抓取和放置分别回归成两个互不相关坐标，网络要用很多数据才能学会这种几何关系。",
    "eraId": "抓取操作",
    "eraYears": "",
    "eraLabel": "抓取操作"
  },
  {
    "slug": "041-amp",
    "file": "041-amp.md",
    "kind": "paper",
    "day": 41,
    "year": 2021,
    "title": "041｜AMP：把动作分布变成运动先验",
    "cardTitle": "AMP：把动作分布变成运动先验",
    "question": "全身运动",
    "excerpt": "如果只奖励“尽快到达目标”，虚拟人可能用奇怪的姿势移动。如果要求它逐帧复现某段跑步动画，又必须决定什么时候切换到走路、跳跃或者翻滚。AMP 把这两个难题拆开：任务奖励告诉角色去哪里，动作数据训练出的判别器评价它动得是否像示范。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "042-rma",
    "file": "042-rma.md",
    "kind": "paper",
    "day": 42,
    "year": 2021,
    "title": "042｜RMA：根据近期运动快速适应新地面",
    "cardTitle": "RMA：根据近期运动快速适应新地面",
    "question": "全身运动",
    "excerpt": "机器人走到湿滑地面，不能停下来重新训练几分钟；动作不及时改变，它可能已经摔倒。RMA 让控制系统保留两个时间尺度：快速策略决定关节位置，较慢的适应模块根据最近的身体运动和动作，更新环境的紧凑表示。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "043-robomimic",
    "file": "043-robomimic.md",
    "kind": "paper",
    "day": 43,
    "year": 2021,
    "title": "043｜robomimic：离线人类示范中真正重要的变量",
    "cardTitle": "robomimic：离线人类示范中真正重要的变量",
    "question": "模仿与奖励",
    "excerpt": "一段人类操作轨迹并不是普通的独立样本集合。人会记住刚才失败过的抓取、根据自己的操作习惯继续运动，也可能用不同路径完成同一任务。把每一帧孤立起来拟合“唯一正确动作”，容易丢掉这些信息。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "044-ibc",
    "file": "044-ibc.md",
    "kind": "paper",
    "day": 44,
    "year": 2021,
    "title": "044｜IBC：用能量函数表示多峰动作",
    "cardTitle": "IBC：用能量函数表示多峰动作",
    "question": "模仿与奖励",
    "excerpt": "普通行为克隆接收图像，直接输出动作。IBC换了一个接口：网络同时接收图像和候选动作，输出一个“能量”；控制时寻找能量最低的动作。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "045-learning-to-walk",
    "file": "045-learning-to-walk.md",
    "kind": "paper",
    "day": 45,
    "year": 2021,
    "title": "045｜并行强化学习：在分钟级训练四足步态",
    "cardTitle": "并行强化学习：在分钟级训练四足步态",
    "question": "全身运动",
    "excerpt": "这篇论文最重要的变化并非一个新的价值函数，而是把仿真、观测、奖励、策略推理和梯度更新尽量放在同一块GPU上，让数千个机器人同时提供经验。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "046-clipport",
    "file": "046-clipport.md",
    "kind": "paper",
    "day": 46,
    "year": 2021,
    "title": "046｜CLIPort：语言语义与空间操作的分工",
    "cardTitle": "CLIPort：语言语义与空间操作的分工",
    "question": "语言与操作",
    "excerpt": "CLIP能把“红色方块”与图像联系起来，却不会天然给出精确抓取和放置位置。Transporter能做空间对齐，却不知道同一桌面上这次要听哪一句指令。CLIPort把两者连接成语言条件操作策略。",
    "eraId": "语言与操作",
    "eraYears": "",
    "eraLabel": "语言与操作"
  },
  {
    "slug": "047-iql",
    "file": "047-iql.md",
    "kind": "paper",
    "day": 47,
    "year": 2021,
    "title": "047｜IQL：在数据内完成价值改进",
    "cardTitle": "IQL：在数据内完成价值改进",
    "question": "离线学习",
    "excerpt": "离线机器人数据可能包含很多“差一点成功”的轨迹。一条轨迹把物体带到中间位置，另一条从附近完成放置；只复制整条行为未必能组合两者。Q-learning可以向前传播好结果，却容易对数据外动作产生虚高估计。",
    "eraId": "离线学习",
    "eraYears": "",
    "eraLabel": "离线学习"
  },
  {
    "slug": "048-calvin",
    "file": "048-calvin.md",
    "kind": "paper",
    "day": 48,
    "year": 2021,
    "title": "048｜CALVIN：语言条件长任务的组合泛化",
    "cardTitle": "CALVIN：语言条件长任务的组合泛化",
    "question": "基准与数据",
    "excerpt": "机器人能分别打开抽屉、拿起积木，为什么连续听从五条指令时却几乎总会失败？CALVIN 把这个落差变成了可重复的研究问题。它的贡献主要是环境、数据和评测协议，而不是一种战胜其他方法的新策略网络。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "049-tdmpc",
    "file": "049-tdmpc.md",
    "kind": "paper",
    "day": 49,
    "year": 2022,
    "title": "049｜TD-MPC：让短规划连接长期价值",
    "cardTitle": "TD-MPC：让短规划连接长期价值",
    "question": "模型学习",
    "excerpt": "学一个能预测未来的模型，未必需要让它画出未来每个像素。对控制来说，更重要的问题是：执行这个动作会不会接近目标，接下来还有多少收益？",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "050-r3m",
    "file": "050-r3m.md",
    "kind": "paper",
    "day": 50,
    "year": 2022,
    "title": "050｜R3M：人类视频中的机器人视觉表征",
    "cardTitle": "R3M：人类视频中的机器人视觉表征",
    "question": "视觉控制",
    "excerpt": "只给机器人二十次示范，却要求它同时学会“看懂杂乱桌面”和“怎样控制手臂”，往往太难。R3M把两个问题拆开：先用大量人类活动视频学习视觉表示，再冻结这套视觉网络，用少量机器人示范训练动作网络。",
    "eraId": "视觉控制",
    "eraYears": "",
    "eraLabel": "视觉控制"
  },
  {
    "slug": "051-saycan",
    "file": "051-saycan.md",
    "kind": "paper",
    "day": 51,
    "year": 2022,
    "title": "051｜SayCan：语言计划还需要可执行性",
    "cardTitle": "SayCan：语言计划还需要可执行性",
    "question": "语言与操作",
    "excerpt": "人说“我把饮料洒了，帮一下忙”，语言模型可能建议拿吸尘器，而机器人既没有吸尘器，也不会使用它。SayCan的办法是同时问两个问题：这个技能对请求有没有用？机器人现在能不能做成？",
    "eraId": "语言与操作",
    "eraYears": "",
    "eraLabel": "语言与操作"
  },
  {
    "slug": "052-gato",
    "file": "052-gato.md",
    "kind": "paper",
    "day": 52,
    "year": 2022,
    "title": "052｜Gato：把多模态决策统一为序列预测",
    "cardTitle": "Gato：把多模态决策统一为序列预测",
    "question": "通用策略",
    "excerpt": "一套权重能否既生成文字，又玩游戏，还控制真实机械臂？Gato把这些任务都改写成序列预测：把观测变成输入token，把文字或动作变成要预测的token，用一个Transformer学习。",
    "eraId": "通用策略",
    "eraYears": "",
    "eraLabel": "通用策略"
  },
  {
    "slug": "053-diffuser",
    "file": "053-diffuser.md",
    "kind": "paper",
    "day": 53,
    "year": 2022,
    "title": "053｜Diffuser：通过去噪生成行为轨迹",
    "cardTitle": "Diffuser：通过去噪生成行为轨迹",
    "question": "生成动作",
    "excerpt": "通常的模型规划是“猜一个动作，再预测下一步”，重复很多次。Diffuser换了一种方式：先产生一整条杂乱轨迹，再反复修正它，让起点、终点、中间状态和动作逐渐相互协调。",
    "eraId": "生成动作",
    "eraYears": "",
    "eraLabel": "生成动作"
  },
  {
    "slug": "054-daydreamer",
    "file": "054-daydreamer.md",
    "kind": "paper",
    "day": 54,
    "year": 2022,
    "title": "054｜DayDreamer：世界模型走出仿真",
    "cardTitle": "DayDreamer：世界模型走出仿真",
    "question": "模型学习",
    "excerpt": "在仿真里学会走路，与让一台真实机器人边试边学，是两种难度。DayDreamer把Dreamer世界模型方法放到四台真实机器人上：机器人只收集有限真实经验，模型在内部预测大量未来，用这些想象轨迹训练策略。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "055-peract",
    "file": "055-peract.md",
    "kind": "paper",
    "day": 55,
    "year": 2022,
    "title": "055｜PerAct：三维体素中的语言条件动作",
    "cardTitle": "PerAct：三维体素中的语言条件动作",
    "question": "抓取操作",
    "excerpt": "给机器人看图，让它回归一个三维抓取位置，网络需要自己学相机投影与空间关系。PerAct先把RGB-D转换成三维体素，再问：“下一次关键动作应该落在哪个体素？”",
    "eraId": "抓取操作",
    "eraYears": "",
    "eraLabel": "抓取操作"
  },
  {
    "slug": "056-vima",
    "file": "056-vima.md",
    "kind": "paper",
    "day": 56,
    "year": 2022,
    "title": "056｜VIMA：多模态提示中的任务组合",
    "cardTitle": "VIMA：多模态提示中的任务组合",
    "question": "语言与操作",
    "excerpt": "机器人任务不只有一句话。有时人指着一个物体，有时给目标照片，有时展示一段动作。VIMA 把这些输入写成同一种多模态提示：文字中可以插入物体图、场景图和示范视频帧，策略结合当前观测与历史直接预测操作动作。",
    "eraId": "语言与操作",
    "eraYears": "",
    "eraLabel": "语言与操作"
  },
  {
    "slug": "057-rt1",
    "file": "057-rt1.md",
    "kind": "paper",
    "day": 57,
    "year": 2022,
    "title": "057｜RT-1：大规模真实机器人动作序列",
    "cardTitle": "RT-1：大规模真实机器人动作序列",
    "question": "VLA",
    "excerpt": "RT-1 的问题是，能不能把大量厨房操作示范放进一个模型，让它执行新的物体—动作组合，而不为每条指令单独训练？作者用13台机器人、17个月采集约13万条真实示范，并设计一个能以3 Hz输出动作的视觉语言策略。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "058-uni-pi",
    "file": "058-uni-pi.md",
    "kind": "paper",
    "day": 58,
    "year": 2023,
    "title": "058｜UniPi：把文本生成视频变成动作策略",
    "cardTitle": "UniPi：把文本生成视频变成动作策略",
    "question": "模型学习",
    "excerpt": "同一个“把杯子放到碗旁”的任务，不同机器人需要不同关节命令，但人看视频通常都能理解目标。UniPi据此把规划和执行拆开：一个文本条件视频模型生成完成任务的未来画面，另一个逆动力学模型把画面转换成特定机器人的控制。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "059-genaug",
    "file": "059-genaug.md",
    "kind": "paper",
    "day": 59,
    "year": 2023,
    "title": "059｜GenAug：用生成式视觉增强扩展示范",
    "cardTitle": "GenAug：用生成式视觉增强扩展示范",
    "question": "视觉控制",
    "excerpt": "示范往往只在一张干净桌子上采集，部署却有新桌布、新容器和杂物。GenAug不重新教机器人一种动作，而是用生成模型修改示范图像：换物体纹理、替换类别、添加干扰物和背景，尽量保持原来的抓取放置标签仍然有效。",
    "eraId": "视觉控制",
    "eraYears": "",
    "eraLabel": "视觉控制"
  },
  {
    "slug": "060-palm-e",
    "file": "060-palm-e.md",
    "kind": "paper",
    "day": 60,
    "year": 2023,
    "title": "060｜PaLM-E：将连续感知送入语言模型",
    "cardTitle": "PaLM-E：将连续感知送入语言模型",
    "question": "语言与操作",
    "excerpt": "SayCan主要把语言模型与技能可行性分数组合；PaLM-E进一步把图像、连续状态或三维场景表示直接嵌入语言模型。模型既能回答“红块在蓝块下面吗”，也能生成“先移开蓝块，再抓红块”这样的步骤。",
    "eraId": "语言与操作",
    "eraYears": "",
    "eraLabel": "语言与操作"
  },
  {
    "slug": "061-diffusion-policy",
    "file": "061-diffusion-policy.md",
    "kind": "paper",
    "day": 61,
    "year": 2023,
    "title": "061｜Diffusion Policy：在动作空间迭代去噪",
    "cardTitle": "Diffusion Policy：在动作空间迭代去噪",
    "question": "生成动作",
    "excerpt": "推一个T形物体时，机械臂可以从左绕，也可以从右绕。若直接回归平均动作，可能直冲物体；若每一步独立选路线，又可能左右摇摆。Diffusion Policy把一段未来动作作为整体分布来学习，从随机噪声逐步生成一条连贯动作序列，只执行其中一部分，再根据新观测重新生成。",
    "eraId": "生成动作",
    "eraYears": "",
    "eraLabel": "生成动作"
  },
  {
    "slug": "062-act",
    "file": "062-act.md",
    "kind": "paper",
    "day": 62,
    "year": 2023,
    "title": "062｜ACT：用动作分块学习精细双臂操作",
    "cardTitle": "ACT：用动作分块学习精细双臂操作",
    "question": "生成动作",
    "excerpt": "ALOHA是双臂遥操作硬件，ACT是学习算法。人移动较小的主臂，较大的从臂同步关节运动，收集精细操作示范；ACT读取多视角RGB和当前关节位置，一次预测未来一段双臂关节目标，再通过时间集成形成平滑命令。",
    "eraId": "生成动作",
    "eraYears": "",
    "eraLabel": "生成动作"
  },
  {
    "slug": "063-furniturebench",
    "file": "063-furniturebench.md",
    "kind": "paper",
    "day": 63,
    "year": 2023,
    "title": "063｜FurnitureBench：真实装配的长期误差",
    "cardTitle": "FurnitureBench：真实装配的长期误差",
    "question": "基准与数据",
    "excerpt": "把桌腿拿到桌面附近，与真正把螺纹对准并拧紧，是两种难度。前者容忍厘米级误差，后者可能被一次接触改变后续全部状态。FurnitureBench 把这种差别变成了可以重复测量的机器人学习问题。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "064-voxposer",
    "file": "064-voxposer.md",
    "kind": "paper",
    "day": 64,
    "year": 2023,
    "title": "064｜VoxPoser：从语言构造三维价值地图",
    "cardTitle": "VoxPoser：从语言构造三维价值地图",
    "question": "语言与操作",
    "excerpt": "“把杯子拿过来，避开花瓶，经过桌沿时慢一点。”这句话包含目标、障碍和速度要求。把它翻译成几个动作名称容易，变成机器人此刻能执行的空间轨迹却困难。",
    "eraId": "语言与操作",
    "eraYears": "",
    "eraLabel": "语言与操作"
  },
  {
    "slug": "065-rt2",
    "file": "065-rt2.md",
    "kind": "paper",
    "day": 65,
    "year": 2023,
    "title": "065｜RT-2：把视觉语言知识接到机器人动作",
    "cardTitle": "RT-2：把视觉语言知识接到机器人动作",
    "question": "VLA",
    "excerpt": "机器人可能会抓苹果，却听不懂“拿一个健康的零食”；视觉语言模型可能知道苹果符合要求，却不会控制夹爪。RT-2 尝试让这两种能力在同一个模型里连接。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "066-bridgev2",
    "file": "066-bridgev2.md",
    "kind": "paper",
    "day": 66,
    "year": 2023,
    "title": "066｜BridgeData V2：跨场景操作数据",
    "cardTitle": "BridgeData V2：跨场景操作数据",
    "question": "基准与数据",
    "excerpt": "如果一个机器人只在某张桌子上学会搬杯子，换实验室就失效，那么它学到的可能既包含技能，也包含大量偶然的视觉规律。BridgeData V2 的问题是：怎样采集一份数据，使别人能在自己的机器人场景里真正使用？",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "067-extreme-parkour",
    "file": "067-extreme-parkour.md",
    "kind": "paper",
    "day": 67,
    "year": 2023,
    "title": "067｜Extreme Parkour：复杂地形中的运动课程",
    "cardTitle": "Extreme Parkour：复杂地形中的运动课程",
    "question": "全身运动",
    "excerpt": "四足机器人能在平地跑，并不意味着它会在窄平台边缘找准起跳姿态。跑酷要求视觉和动作紧密耦合：方向偏几度，前脚就可能落不到平台上。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "068-openx",
    "file": "068-openx.md",
    "kind": "paper",
    "day": 68,
    "year": 2023,
    "title": "068｜Open X：跨机器人数据与共享策略",
    "cardTitle": "Open X：跨机器人数据与共享策略",
    "question": "基准与数据",
    "excerpt": "每个实验室都让自己的机械臂收集数据，却各自训练一个模型，会浪费多少可以共享的经验？Open X-Embodiment 把这个问题推向实际验证：不同机器人的轨迹能否放在一起，帮助每一种机器人学得更好？",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "069-eureka",
    "file": "069-eureka.md",
    "kind": "paper",
    "day": 69,
    "year": 2023,
    "title": "069｜Eureka：用程序生成与反馈改进奖励",
    "cardTitle": "Eureka：用程序生成与反馈改进奖励",
    "question": "机器人强化学习",
    "excerpt": "强化学习中的难点常常不是“怎样更新参数”，而是“到底给什么奖励”。只在任务完成时给分，机器人可能永远碰不到成功；奖励设计得太细，又可能学会钻空子。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "070-tdmpc2",
    "file": "070-tdmpc2.md",
    "kind": "paper",
    "day": 70,
    "year": 2023,
    "title": "070｜TD-MPC2：可扩展的连续控制世界模型",
    "cardTitle": "TD-MPC2：可扩展的连续控制世界模型",
    "question": "模型学习",
    "excerpt": "世界模型不一定需要生成逼真的未来视频。对控制而言，它首先需要回答：尝试这串动作，回报会怎样，最后会到一个多好的状态？",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "071-mimicgen",
    "file": "071-mimicgen.md",
    "kind": "paper",
    "day": 71,
    "year": 2023,
    "title": "071｜MimicGen：用对象中心变换复用示范",
    "cardTitle": "MimicGen：用对象中心变换复用示范",
    "question": "模仿与奖励",
    "excerpt": "把杯子从桌角移到桌心，人通常不需要重新学习抓杯子，只需让“相对杯子的动作”跟着杯子移动。MimicGen 把这种复用做成数据生产系统：把少量示范分成对象中心片段，变换并执行，收集成功轨迹，再训练视觉策略。",
    "eraId": "模仿与奖励",
    "eraYears": "",
    "eraLabel": "模仿与奖励"
  },
  {
    "slug": "072-gr1",
    "file": "072-gr1.md",
    "kind": "paper",
    "day": 72,
    "year": 2023,
    "title": "072｜GR-1：视频预测预训练与机器人动作学习",
    "cardTitle": "GR-1：视频预测预训练与机器人动作学习",
    "question": "模型学习",
    "excerpt": "人类视频没有机器人的电机标签，却包含物体如何被抓取、移动和放置的信息。GR-1 的主张是：先用这类视频训练一个预测未来画面的序列模型，再用机器人示范教它预测动作，可以获得比仅模仿机器人轨迹更好的泛化。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "073-mobile-aloha",
    "file": "073-mobile-aloha.md",
    "kind": "paper",
    "day": 73,
    "year": 2024,
    "title": "073｜Mobile ALOHA：移动双臂的全身示范",
    "cardTitle": "Mobile ALOHA：移动双臂的全身示范",
    "question": "全身操作",
    "excerpt": "双臂抓着柜门时，底盘要后退，手臂又要保持接触；底盘停得稍有偏差，按电梯按钮的位置就可能偏几厘米。Mobile ALOHA 研究的正是这种移动与操作耦合。",
    "eraId": "全身操作",
    "eraYears": "",
    "eraLabel": "全身操作"
  },
  {
    "slug": "074-serl",
    "file": "074-serl.md",
    "kind": "paper",
    "day": 74,
    "year": 2024,
    "title": "074｜SERL：可实际运行的真机强化学习栈",
    "cardTitle": "SERL：可实际运行的真机强化学习栈",
    "question": "机器人强化学习",
    "excerpt": "写出 SAC 损失很容易，让真实机械臂稳定收集数据、自动获得奖励、完成复位且不因训练阻塞控制，却需要另一套工作。SERL 把这些环节组合成可用的软件系统。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "075-dp3",
    "file": "075-dp3.md",
    "kind": "paper",
    "day": 75,
    "year": 2024,
    "title": "075｜DP3：简洁三维表示与动作扩散",
    "cardTitle": "DP3：简洁三维表示与动作扩散",
    "question": "生成动作",
    "excerpt": "同一只杯子在图像里变大，可能因为靠近相机，也可能因为杯子本身更大。三维点云直接提供空间位置，能减少模仿学习在少量示范中自行推断几何的负担。",
    "eraId": "生成动作",
    "eraYears": "",
    "eraLabel": "生成动作"
  },
  {
    "slug": "076-human2humanoid",
    "file": "076-human2humanoid.md",
    "kind": "paper",
    "day": 76,
    "year": 2024,
    "title": "076｜Human2Humanoid：把人的全身运动映射到机器人",
    "cardTitle": "Human2Humanoid：把人的全身运动映射到机器人",
    "question": "全身运动",
    "excerpt": "人类动作捕捉中有大量走路、挥手和踢腿，但人体与人形机器人的质量、关节和力矩上限不同。直接把人体姿势变成机器人关节角，可能得到形似却会跌倒的动作。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "077-dexcap",
    "file": "077-dexcap.md",
    "kind": "paper",
    "day": 77,
    "year": 2024,
    "title": "077｜DexCap：便携式灵巧操作数据采集",
    "cardTitle": "DexCap：便携式灵巧操作数据采集",
    "question": "灵巧操作",
    "excerpt": "遥操作灵巧手很慢，纯视频估计人手又常被物体遮挡。DexCap 把手指动捕、手腕定位和胸前深度相机组合起来，让人在没有机器人的地方也能采集三维操作数据。",
    "eraId": "灵巧操作",
    "eraYears": "",
    "eraLabel": "灵巧操作"
  },
  {
    "slug": "078-droid",
    "file": "078-droid.md",
    "kind": "paper",
    "day": 78,
    "year": 2024,
    "title": "078｜DROID：真实环境中的多样操作示范",
    "cardTitle": "DROID：真实环境中的多样操作示范",
    "question": "基准与数据",
    "excerpt": "如果十万次抓取都发生在同一张桌子上，模型可能学会桌面背景，而不是稳定识别操作关系。DROID 把采集地点、物体、视角和交互位置的多样性作为核心问题。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "079-humanoidgym",
    "file": "079-humanoidgym.md",
    "kind": "paper",
    "day": 79,
    "year": 2024,
    "title": "079｜Humanoid-Gym：人形步态的零样本仿真迁移",
    "cardTitle": "Humanoid-Gym：人形步态的零样本仿真迁移",
    "question": "全身运动",
    "excerpt": "训练出一个在模拟器里不摔倒的人形策略，并不等于把程序复制到机器人后就能走。电机响应、关节摩擦、通信时延和接触求解器都会改变闭环行为。Humanoid-Gym 把关注点放在这个工程断层：用统一环境训练步态，再跨模拟器检查，最后部署到真实人形机器人。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "080-octo",
    "file": "080-octo.md",
    "kind": "paper",
    "day": 80,
    "year": 2024,
    "title": "080｜Octo：可适配的通用机器人策略",
    "cardTitle": "Octo：可适配的通用机器人策略",
    "question": "通用策略",
    "excerpt": "机器人实验室换一只机械臂，常常连输入和输出维度都会改变：原来只有外部相机，现在多了腕部相机；原来预测末端增量，现在要预测两个手臂的关节位置。如果模型只能接受固定格式，“通用”便只剩下在同一接口中识别更多物体。",
    "eraId": "通用策略",
    "eraYears": "",
    "eraLabel": "通用策略"
  },
  {
    "slug": "081-robocasa",
    "file": "081-robocasa.md",
    "kind": "paper",
    "day": 81,
    "year": 2024,
    "title": "081｜RoboCasa：把厨房仿真变成机器人数据工厂",
    "cardTitle": "RoboCasa：把厨房仿真变成机器人数据工厂",
    "question": "基准与数据",
    "excerpt": "真实厨房中的物体、布局和设备很多，逐个遥操作收集示范成本高；如果仿真只有几个桌面任务，也难以支撑通用控制研究。RoboCasa 建立多样化厨房、可交互资产和任务库，再用人类示范驱动 MimicGen 生成更多成功轨迹。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "082-openvla",
    "file": "082-openvla.md",
    "kind": "paper",
    "day": 82,
    "year": 2024,
    "title": "082｜OpenVLA：开源视觉语言动作模型",
    "cardTitle": "OpenVLA：开源视觉语言动作模型",
    "question": "VLA",
    "excerpt": "OpenVLA 将已经具备视觉语言知识的模型继续训练成机器人策略：看一张图、读一条指令，然后输出末端位移、旋转和夹爪动作。它沿用 RT-2 的动作 token 思路，重点解决开放使用、机器人数据训练和低成本适配问题。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "083-diffusion-rl",
    "file": "083-diffusion-rl.md",
    "kind": "paper",
    "day": 83,
    "year": 2024,
    "title": "083｜DPPO：扩散策略如何在线优化回报",
    "cardTitle": "DPPO：扩散策略如何在线优化回报",
    "question": "机器人强化学习",
    "excerpt": "Diffusion Policy 能模仿复杂动作，但示范有限时，它也会继承数据中的盲区。DPPO 研究如何利用在线强化学习继续改善这种策略，而不把多模态动作分布压成一个普通高斯。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "084-robotwin",
    "file": "084-robotwin.md",
    "kind": "paper",
    "day": 84,
    "year": 2024,
    "title": "084｜RoboTwin：数字孪生中的双臂任务",
    "cardTitle": "RoboTwin：数字孪生中的双臂任务",
    "question": "基准与数据",
    "excerpt": "双臂机器人不仅要分别控制两只手，还要处理交接、共同持物和工具作用方向。真实示范昂贵，而通用三维模型又常缺少可以直接控制的功能信息。",
    "eraId": "基准与数据",
    "eraYears": "",
    "eraLabel": "基准与数据"
  },
  {
    "slug": "085-rdt",
    "file": "085-rdt.md",
    "kind": "paper",
    "day": 85,
    "year": 2024,
    "title": "085｜RDT-1B：双臂控制的扩散基础模型",
    "cardTitle": "RDT-1B：双臂控制的扩散基础模型",
    "question": "生成动作",
    "excerpt": "RDT-1B 想解决两类瓶颈。第一，双臂的可行动作常有多种模式，简单平均可能导致两只手都犹豫；第二，目标双臂数据少，但其他机器人的动作格式又不一样。",
    "eraId": "生成动作",
    "eraYears": "",
    "eraLabel": "生成动作"
  },
  {
    "slug": "086-hil-serl",
    "file": "086-hil-serl.md",
    "kind": "paper",
    "day": 86,
    "year": 2024,
    "title": "086｜HIL-SERL：通过人类纠正加速真机学习",
    "cardTitle": "HIL-SERL：通过人类纠正加速真机学习",
    "question": "机器人强化学习",
    "excerpt": "教机器人插内存条，最难的往往不是让它接近插槽，而是在接触后发现偏差、退出一点、重新对齐。只模仿顺利完成的演示，容易缺少这些失败后的恢复经验。HIL-SERL 让机器人在真机上试，同时允许操作者用 SpaceMouse 接管几步，把机器人带回值得探索的区域。",
    "eraId": "机器人强化学习",
    "eraYears": "",
    "eraLabel": "机器人强化学习"
  },
  {
    "slug": "087-pi0",
    "file": "087-pi0.md",
    "kind": "paper",
    "day": 87,
    "year": 2024,
    "title": "087｜π0：以流匹配生成连续动作",
    "cardTitle": "π0：以流匹配生成连续动作",
    "question": "VLA",
    "excerpt": "语言模型可以理解“把衣服折好”，但把一句话变成连续、双臂协调的关节运动，不能只靠把数字当单词逐个输出。π0 为预训练视觉语言模型增加一个动作专家，让它通过流匹配一次生成一段连续动作，再用大规模机器人资料预训练和任务数据后训练。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "088-dexmimicgen",
    "file": "088-dexmimicgen.md",
    "kind": "paper",
    "day": 88,
    "year": 2024,
    "title": "088｜DexMimicGen：从少量示范生成双臂灵巧数据",
    "cardTitle": "DexMimicGen：从少量示范生成双臂灵巧数据",
    "question": "灵巧操作",
    "excerpt": "双手装配不能简单地把两条单手轨迹同时播放。左手可以先拿到零件、等待右手；两手抬托盘必须同时用力；倒完水之前，另一只手不能把碗搬走。DexMimicGen 的核心，就是把这些时间关系加入示范扩增。",
    "eraId": "灵巧操作",
    "eraYears": "",
    "eraLabel": "灵巧操作"
  },
  {
    "slug": "089-fast",
    "file": "089-fast.md",
    "kind": "paper",
    "day": 89,
    "year": 2025,
    "title": "089｜FAST：让高频连续动作拥有紧凑 token",
    "cardTitle": "FAST：让高频连续动作拥有紧凑 token",
    "question": "VLA",
    "excerpt": "让模型逐个预测一秒内的700个动作数字，听起来精细，实际可能让训练陷入“照抄上一个数字”。高频动作往往变化很小，预测重复内容容易获得低损失，却没有学会根据图像和指令组织整段运动。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "090-asap",
    "file": "090-asap.md",
    "kind": "paper",
    "day": 90,
    "year": 2025,
    "title": "090｜ASAP：学习仿真与现实之间的动作差异",
    "cardTitle": "ASAP：学习仿真与现实之间的动作差异",
    "question": "全身运动",
    "excerpt": "仿真里能跳起来的人形机器人，上机后可能因为踝关节传动和电机响应不同而动作变形。ASAP没有直接要求真实机器人“加一段补偿动作”，而是先让模拟器变得更像真实机器人，包括复现它的不足，再在这个经过修正的环境里训练动作策略。",
    "eraId": "全身运动",
    "eraYears": "",
    "eraLabel": "全身运动"
  },
  {
    "slug": "091-openvla-oft",
    "file": "091-openvla-oft.md",
    "kind": "paper",
    "day": 91,
    "year": 2025,
    "title": "091｜OpenVLA-OFT：高效微调与动作分块",
    "cardTitle": "OpenVLA-OFT：高效微调与动作分块",
    "question": "VLA",
    "excerpt": "预训练时怎样输出动作，微调时不一定还要照搬。OpenVLA最初像写句子一样逐个生成动作数字，这使双臂高频控制很慢。OFT保留已经学到的表示，却把输出改成一次并行预测整段连续动作，用简单L1损失微调。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "092-groot",
    "file": "092-groot.md",
    "kind": "paper",
    "day": 92,
    "year": 2025,
    "title": "092｜GR00T N1：面向人形操作的通用模型",
    "cardTitle": "GR00T N1：面向人形操作的通用模型",
    "question": "VLA",
    "excerpt": "机器人数据有一个根本矛盾：最接近部署条件的真机示范昂贵，最容易获得的人类视频又没有机器人电机命令。GR00T N1 用机器人专属接口连接共享的视觉语言与动作模型，并把视频转成潜在动作或逆动力学伪标签。它研究的是如何利用异构数据改善少量示范下的操作学习，而不是在线探索奖励的强化学习。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "093-pi05",
    "file": "093-pi05.md",
    "kind": "paper",
    "day": 93,
    "year": 2025,
    "title": "093｜π0.5：开放环境中的任务与动作泛化",
    "cardTitle": "π0.5：开放环境中的任务与动作泛化",
    "question": "VLA",
    "excerpt": "给机器人一条“把餐具收进水槽”的指令，难点不只是抓起盘子。机器人还要在陌生厨房辨认水槽、选择当前对象、协调底盘和手臂，并在放下后继续寻找下一件。π0.5 把这个问题拆成共享模型的两次推断：先根据整体目标与画面预测语义子任务，再根据该子任务生成连续动作。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "094-vla-rl",
    "file": "094-vla-rl.md",
    "kind": "paper",
    "day": 94,
    "year": 2025,
    "title": "094｜VLA-RL：用强化学习改进动作基础模型",
    "cardTitle": "VLA-RL：用强化学习改进动作基础模型",
    "question": "VLA",
    "excerpt": "行为克隆教机器人模仿专家，但部署时机器人会遇见自己造成的偏差：夹爪早闭合、末端停在错误位置、物体被碰偏。VLA-RL 的思路是保留预训练 OpenVLA 的视觉与动作先验，再让它在线收集轨迹，用 PPO 调整动作概率。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "095-smolvla",
    "file": "095-smolvla.md",
    "kind": "paper",
    "day": 95,
    "year": 2025,
    "title": "095｜SmolVLA：紧凑模型与异步机器人控制",
    "cardTitle": "SmolVLA：紧凑模型与异步机器人控制",
    "question": "VLA",
    "excerpt": "SmolVLA 面对的问题很实际：机器人不应每次等模型算完才继续动，大模型也未必是简单操作的唯一选择。它使用较小的视觉语言骨干，减少图像 token 和网络层数，再接一个流匹配动作专家；部署时让模型计算和机器人执行并行。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "096-xiaomi0",
    "file": "096-xiaomi0.md",
    "kind": "paper",
    "day": 96,
    "year": 2026,
    "title": "096｜Xiaomi-Robotics-0：实时执行约束下的通用动作模型",
    "cardTitle": "Xiaomi-Robotics-0：实时执行约束下的通用动作模型",
    "question": "VLA",
    "excerpt": "机器人在等待大模型推理时停住，会降低效率；继续执行旧动作又可能与新动作不连续。已有实时分块方法把“已经承诺执行的动作”作为下一块的前缀，使新预测顺着旧轨迹衔接。Xiaomi-Robotics-0 进一步指出：前缀也可能成为捷径，模型只复制原有动作，不再充分看图像与指令。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "097-mbdpo",
    "file": "097-mbdpo.md",
    "kind": "paper",
    "day": 97,
    "year": 2026,
    "title": "097｜MBDPO：世界模型中的扩散策略优化",
    "cardTitle": "MBDPO：世界模型中的扩散策略优化",
    "question": "模型学习",
    "excerpt": "世界模型能预测未来，不代表搜索一定找到真实好动作。假设价值函数主要熟悉回放数据中的行为，规划器却专门寻找其预测最高的动作，那么搜索可能不断找到估计错误的高峰。MBDPO 研究这种搜索策略与价值学习之间的不一致。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "098-continuous-reasoning",
    "file": "098-continuous-reasoning.md",
    "kind": "paper",
    "day": 98,
    "year": 2026,
    "title": "098｜连续推理：让潜在思想成为可复用的动作接口",
    "cardTitle": "连续推理：让潜在思想成为可复用的动作接口",
    "question": "VLA",
    "excerpt": "给VLA增加几个隐藏向量，成功率可能上升，但这些向量到底承载了可复用的任务结构，还是只成为一个额外参数通道？Continuous Reasoning把这个问题变成训练目标：学生生成连续“thought”编码，学生和EMA教师分别解码它，并预测同一个目标动作。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "099-worldsample",
    "file": "099-worldsample.md",
    "kind": "paper",
    "day": 99,
    "year": 2026,
    "title": "099｜WorldSample：世界模型合成经验的选择与使用",
    "cardTitle": "WorldSample：世界模型合成经验的选择与使用",
    "question": "模型学习",
    "excerpt": "机器人每做一次真实尝试，都要付出时间、复位和人工看护成本。如果视频世界模型能回答“刚才的动作稍微换一种，会发生什么”，一次真实经历就能生成多个学习样本。问题是：生成视频可能看起来合理，却把接触、成功条件或失败恢复预测错。把这些数据无限加入强化学习，可能把价值函数教坏。",
    "eraId": "模型学习",
    "eraYears": "",
    "eraLabel": "模型学习"
  },
  {
    "slug": "100-core-vla",
    "file": "100-core-vla.md",
    "kind": "paper",
    "day": 100,
    "year": 2026,
    "title": "100｜CoRE-VLA：用条件专家路由平衡规模与鲁棒性",
    "cardTitle": "CoRE-VLA：用条件专家路由平衡规模与鲁棒性",
    "question": "VLA",
    "excerpt": "给机器人增加深度相机，往往能帮助它判断物体位置；但如果训练过度依赖深度，部署时相机缺失就可能明显退化。另一个问题是，多任务动作模型使用同一套计算处理所有情境，抓蔬菜、折衣服和执行长任务可能互相干扰。",
    "eraId": "VLA",
    "eraYears": "",
    "eraLabel": "VLA"
  },
  {
    "slug": "101-epilogue",
    "file": "101-系列总结.md",
    "kind": "epilogue",
    "day": 101,
    "year": null,
    "title": "系列总结｜从学习动作到让机器人可靠行动",
    "cardTitle": "系列总结",
    "question": "跨论文比较与实验阅读方法",
    "excerpt": "机器人学习的发展，可以理解为不断重新安排“哪些知识写进结构，哪些知识从数据学习，哪些错误留给闭环反馈纠正”。运动基元把稳定性写进动力系统；深度强化学习把动作优劣交给价值函数；模仿学习利用人的行为；世界模型预测尚未执行的后果；VLA 借助语言与视觉预训练扩大任务接口。后一条路线没有使前一条消失，它们在同一台机器人上经常共存。",
    "eraId": "epilogue",
    "eraYears": "",
    "eraLabel": "收尾"
  }
];
window.SERIES_SLUG_MAP = {
  "00-发展时间线总览.md": "00-timeline",
  "00-发展时间线总览": "00-timeline",
  "001-dmp.md": "001-dmp",
  "001-dmp": "001-dmp",
  "002-apprenticeship.md": "002-apprenticeship",
  "002-apprenticeship": "002-apprenticeship",
  "003-maxent-irl.md": "003-maxent-irl",
  "003-maxent-irl": "003-maxent-irl",
  "004-power.md": "004-power",
  "004-power": "004-power",
  "005-pi2.md": "005-pi2",
  "005-pi2": "005-pi2",
  "006-dagger.md": "006-dagger",
  "006-dagger": "006-dagger",
  "007-pilco.md": "007-pilco",
  "007-pilco": "007-pilco",
  "008-promp.md": "008-promp",
  "008-promp": "008-promp",
  "009-gps.md": "009-gps",
  "009-gps": "009-gps",
  "010-visuomotor.md": "010-visuomotor",
  "010-visuomotor": "010-visuomotor",
  "011-ddpg.md": "011-ddpg",
  "011-ddpg": "011-ddpg",
  "012-guided-cost.md": "012-guided-cost",
  "012-guided-cost": "012-guided-cost",
  "013-naf.md": "013-naf",
  "013-naf": "013-naf",
  "014-hand-eye.md": "014-hand-eye",
  "014-hand-eye": "014-hand-eye",
  "015-gail.md": "015-gail",
  "015-gail": "015-gail",
  "016-visual-foresight.md": "016-visual-foresight",
  "016-visual-foresight": "016-visual-foresight",
  "017-progressive.md": "017-progressive",
  "017-progressive": "017-progressive",
  "018-domain-randomization.md": "018-domain-randomization",
  "018-domain-randomization": "018-domain-randomization",
  "019-one-shot.md": "019-one-shot",
  "019-one-shot": "019-one-shot",
  "020-dexnet2.md": "020-dexnet2",
  "020-dexnet2": "020-dexnet2",
  "021-dart.md": "021-dart",
  "021-dart": "021-dart",
  "022-her.md": "022-her",
  "022-her": "022-her",
  "023-dapg.md": "023-dapg",
  "023-dapg": "023-dapg",
  "024-dynamics-randomization.md": "024-dynamics-randomization",
  "024-dynamics-randomization": "024-dynamics-randomization",
  "025-sac.md": "025-sac",
  "025-sac": "025-sac",
  "026-td3.md": "026-td3",
  "026-td3": "026-td3",
  "027-dynamics-embedding.md": "027-dynamics-embedding",
  "027-dynamics-embedding": "027-dynamics-embedding",
  "028-deepmimic.md": "028-deepmimic",
  "028-deepmimic": "028-deepmimic",
  "029-pets.md": "029-pets",
  "029-pets": "029-pets",
  "030-qt-opt.md": "030-qt-opt",
  "030-qt-opt": "030-qt-opt",
  "031-dexterous.md": "031-dexterous",
  "031-dexterous": "031-dexterous",
  "032-anymal.md": "032-anymal",
  "032-anymal": "032-anymal",
  "033-mbpo.md": "033-mbpo",
  "033-mbpo": "033-mbpo",
  "034-rlbench.md": "034-rlbench",
  "034-rlbench": "034-rlbench",
  "035-rubiks.md": "035-rubiks",
  "035-rubiks": "035-rubiks",
  "036-metaworld.md": "036-metaworld",
  "036-metaworld": "036-metaworld",
  "037-dreamer.md": "037-dreamer",
  "037-dreamer": "037-dreamer",
  "038-cql.md": "038-cql",
  "038-cql": "038-cql",
  "039-awac.md": "039-awac",
  "039-awac": "039-awac",
  "040-transporter.md": "040-transporter",
  "040-transporter": "040-transporter",
  "041-amp.md": "041-amp",
  "041-amp": "041-amp",
  "042-rma.md": "042-rma",
  "042-rma": "042-rma",
  "043-robomimic.md": "043-robomimic",
  "043-robomimic": "043-robomimic",
  "044-ibc.md": "044-ibc",
  "044-ibc": "044-ibc",
  "045-learning-to-walk.md": "045-learning-to-walk",
  "045-learning-to-walk": "045-learning-to-walk",
  "046-clipport.md": "046-clipport",
  "046-clipport": "046-clipport",
  "047-iql.md": "047-iql",
  "047-iql": "047-iql",
  "048-calvin.md": "048-calvin",
  "048-calvin": "048-calvin",
  "049-tdmpc.md": "049-tdmpc",
  "049-tdmpc": "049-tdmpc",
  "050-r3m.md": "050-r3m",
  "050-r3m": "050-r3m",
  "051-saycan.md": "051-saycan",
  "051-saycan": "051-saycan",
  "052-gato.md": "052-gato",
  "052-gato": "052-gato",
  "053-diffuser.md": "053-diffuser",
  "053-diffuser": "053-diffuser",
  "054-daydreamer.md": "054-daydreamer",
  "054-daydreamer": "054-daydreamer",
  "055-peract.md": "055-peract",
  "055-peract": "055-peract",
  "056-vima.md": "056-vima",
  "056-vima": "056-vima",
  "057-rt1.md": "057-rt1",
  "057-rt1": "057-rt1",
  "058-uni-pi.md": "058-uni-pi",
  "058-uni-pi": "058-uni-pi",
  "059-genaug.md": "059-genaug",
  "059-genaug": "059-genaug",
  "060-palm-e.md": "060-palm-e",
  "060-palm-e": "060-palm-e",
  "061-diffusion-policy.md": "061-diffusion-policy",
  "061-diffusion-policy": "061-diffusion-policy",
  "062-act.md": "062-act",
  "062-act": "062-act",
  "063-furniturebench.md": "063-furniturebench",
  "063-furniturebench": "063-furniturebench",
  "064-voxposer.md": "064-voxposer",
  "064-voxposer": "064-voxposer",
  "065-rt2.md": "065-rt2",
  "065-rt2": "065-rt2",
  "066-bridgev2.md": "066-bridgev2",
  "066-bridgev2": "066-bridgev2",
  "067-extreme-parkour.md": "067-extreme-parkour",
  "067-extreme-parkour": "067-extreme-parkour",
  "068-openx.md": "068-openx",
  "068-openx": "068-openx",
  "069-eureka.md": "069-eureka",
  "069-eureka": "069-eureka",
  "070-tdmpc2.md": "070-tdmpc2",
  "070-tdmpc2": "070-tdmpc2",
  "071-mimicgen.md": "071-mimicgen",
  "071-mimicgen": "071-mimicgen",
  "072-gr1.md": "072-gr1",
  "072-gr1": "072-gr1",
  "073-mobile-aloha.md": "073-mobile-aloha",
  "073-mobile-aloha": "073-mobile-aloha",
  "074-serl.md": "074-serl",
  "074-serl": "074-serl",
  "075-dp3.md": "075-dp3",
  "075-dp3": "075-dp3",
  "076-human2humanoid.md": "076-human2humanoid",
  "076-human2humanoid": "076-human2humanoid",
  "077-dexcap.md": "077-dexcap",
  "077-dexcap": "077-dexcap",
  "078-droid.md": "078-droid",
  "078-droid": "078-droid",
  "079-humanoidgym.md": "079-humanoidgym",
  "079-humanoidgym": "079-humanoidgym",
  "080-octo.md": "080-octo",
  "080-octo": "080-octo",
  "081-robocasa.md": "081-robocasa",
  "081-robocasa": "081-robocasa",
  "082-openvla.md": "082-openvla",
  "082-openvla": "082-openvla",
  "083-diffusion-rl.md": "083-diffusion-rl",
  "083-diffusion-rl": "083-diffusion-rl",
  "084-robotwin.md": "084-robotwin",
  "084-robotwin": "084-robotwin",
  "085-rdt.md": "085-rdt",
  "085-rdt": "085-rdt",
  "086-hil-serl.md": "086-hil-serl",
  "086-hil-serl": "086-hil-serl",
  "087-pi0.md": "087-pi0",
  "087-pi0": "087-pi0",
  "088-dexmimicgen.md": "088-dexmimicgen",
  "088-dexmimicgen": "088-dexmimicgen",
  "089-fast.md": "089-fast",
  "089-fast": "089-fast",
  "090-asap.md": "090-asap",
  "090-asap": "090-asap",
  "091-openvla-oft.md": "091-openvla-oft",
  "091-openvla-oft": "091-openvla-oft",
  "092-groot.md": "092-groot",
  "092-groot": "092-groot",
  "093-pi05.md": "093-pi05",
  "093-pi05": "093-pi05",
  "094-vla-rl.md": "094-vla-rl",
  "094-vla-rl": "094-vla-rl",
  "095-smolvla.md": "095-smolvla",
  "095-smolvla": "095-smolvla",
  "096-xiaomi0.md": "096-xiaomi0",
  "096-xiaomi0": "096-xiaomi0",
  "097-mbdpo.md": "097-mbdpo",
  "097-mbdpo": "097-mbdpo",
  "098-continuous-reasoning.md": "098-continuous-reasoning",
  "098-continuous-reasoning": "098-continuous-reasoning",
  "099-worldsample.md": "099-worldsample",
  "099-worldsample": "099-worldsample",
  "100-core-vla.md": "100-core-vla",
  "100-core-vla": "100-core-vla",
  "101-系列总结.md": "101-epilogue",
  "101-系列总结": "101-epilogue"
};
